({
	"quarters-format-abbr": [
		"C1", 
		"C2", 
		"C3", 
		"C4"
	], 
	"dateFormat-medium": "y. 'gada' d. MMM", 
	"dateFormatItem-MMMEd": "E, d. MMM", 
	"dateFormatItem-yMEd": "EEE, dd.mm.yyyy.", 
	"dateFormatItem-MEd": "E, dd.MM.", 
	"dateFormatItem-y": "y. 'g'.", 
	"dateFormatItem-Md": "dd.mm.", 
	"months-standAlone-wide": [
		"tišri", 
		"hešvans", 
		"kisļevs", 
		"tevets", 
		"ševats", 
		"1. adars", 
		"adars", 
		"nisans", 
		"ijars", 
		"sivans", 
		"tamuzs", 
		"avs", 
		"eluls"
	], 
	"months-format-wide-leap": "2. adars", 
	"dateFormatItem-EEEd": "EEE, d.", 
	"days-standAlone-narrow": [
		"S", 
		"P", 
		"O", 
		"T", 
		"C", 
		"P", 
		"S"
	], 
	"dayPeriods-format-wide-pm": "pēcpusdienā", 
	"months-standAlone-abbr": [
		"tišri", 
		"hešvans", 
		"kisļevs", 
		"tevets", 
		"ševats", 
		"1. adars", 
		"adars", 
		"nisans", 
		"ijars", 
		"sivans", 
		"tamuzs", 
		"avs", 
		"eluls"
	], 
	"dayPeriods-format-wide-am": "priekšpusdienā", 
	"dateFormat-long": "y. 'gada' d. MMMM", 
	"dateFormat-short": "dd.MM.yy", 
	"dateFormatItem-yMMMEd": "EEE, yyyy. 'g'. dd. MMM", 
	"months-format-wide": [
		"tišri", 
		"hešvans", 
		"kisļevs", 
		"tevets", 
		"ševats", 
		"1. adars", 
		"adars", 
		"nisans", 
		"ijars", 
		"sivans", 
		"tamuzs", 
		"avs", 
		"eluls"
	], 
	"dateFormatItem-yM": "mm.yyyy.", 
	"months-format-abbr": [
		"tišri", 
		"hešvans", 
		"kisļevs", 
		"tevets", 
		"ševats", 
		"1. adars", 
		"adars", 
		"nisans", 
		"ijars", 
		"sivans", 
		"tamuzs", 
		"avs", 
		"eluls"
	], 
	"days-format-wide": [
		"svētdiena", 
		"pirmdiena", 
		"otrdiena", 
		"trešdiena", 
		"ceturtdiena", 
		"piektdiena", 
		"sestdiena"
	], 
	"dateFormatItem-yQ": "Q yyyy", 
	"dateFormatItem-yMMM": "yyyy. 'g'. MMM", 
	"quarters-format-wide": [
		"1. ceturksnis", 
		"2. ceturksnis", 
		"3. ceturksnis", 
		"4. ceturksnis"
	], 
	"dateFormat-full": "EEEE, y. 'gada' d. MMMM", 
	"dateFormatItem-MMMd": "d. MMM", 
	"days-format-abbr": [
		"Sv", 
		"Pr", 
		"Ot", 
		"Tr", 
		"Ce", 
		"Pk", 
		"Se"
	]
})