({
	"dateFormatItem-yM": "M/y", 
	"field-dayperiod": "sɔgɔma/tile/wula/su", 
	"dateFormatItem-yQ": "'T'Q y", 
	"field-minute": "miniti", 
	"eraNames": [
		"jezu krisiti ɲɛ", 
		"jezu krisiti minkɛ"
	], 
	"dateFormatItem-MMMEd": "E d MMM", 
	"field-day-relative+-1": "kunu", 
	"dateFormatItem-MMdd": "dd/MM", 
	"dateFormatItem-yQQQ": "QQQ y", 
	"field-weekday": "don", 
	"days-standAlone-wide": [
		"kari", 
		"ntɛnɛ", 
		"tarata", 
		"araba", 
		"alamisa", 
		"juma", 
		"sibiri"
	], 
	"dateFormatItem-MMM": "MMM", 
	"months-standAlone-narrow": [
		"Z", 
		"F", 
		"M", 
		"A", 
		"M", 
		"Z", 
		"Z", 
		"U", 
		"S", 
		"Ɔ", 
		"N", 
		"D"
	], 
	"field-era": "tile", 
	"field-hour": "lɛrɛ", 
	"quarters-standAlone-abbr": [
		"KS1", 
		"KS2", 
		"KS3", 
		"KS4"
	], 
	"dateFormatItem-y": "y", 
	"dateFormatItem-yyMMMEEEd": "EEE d MMM yy", 
	"dateFormatItem-MMMdd": "dd MMM", 
	"timeFormat-full": "HH:mm:ss zzzz", 
	"dateFormatItem-Med": "EEE d/M", 
	"months-standAlone-abbr": [
		"zan", 
		"feb", 
		"nar", 
		"awi", 
		"mɛ", 
		"zuw", 
		"zul", 
		"uti", 
		"sɛt", 
		"ɔku", 
		"now", 
		"des"
	], 
	"dateFormatItem-yMMM": "MMM y", 
	"field-day-relative+0": "bi", 
	"days-standAlone-narrow": [
		"K", 
		"N", 
		"T", 
		"A", 
		"A", 
		"J", 
		"S"
	], 
	"field-day-relative+1": "sini", 
	"eraAbbr": [
		"J.-C. ɲɛ", 
		"ni J.-C."
	], 
	"dateFormatItem-yyyyMMMM": "MMMM yyyy", 
	"dateFormat-long": "d MMMM y", 
	"timeFormat-medium": "HH:mm:ss", 
	"field-zone": "sigikun tilena", 
	"dateFormatItem-MMd": "d/MM", 
	"dateFormat-medium": "d MMM, y", 
	"dateFormatItem-yyMM": "MM/y", 
	"dateFormatItem-yyMMM": "MMM yy", 
	"quarters-standAlone-wide": [
		"kalo saba fɔlɔ", 
		"kalo saba filanan", 
		"kalo saba sabanan", 
		"kalo saba naaninan"
	], 
	"dateFormatItem-yMMMM": "MMMM y", 
	"dateFormatItem-ms": "m:ss", 
	"field-year": "san", 
	"dateFormatItem-yyMMMd": "d MMM yy", 
	"field-week": "dɔgɔkun", 
	"months-standAlone-wide": [
		"zanwuye", 
		"feburuye", 
		"marisi", 
		"awirili", 
		"mɛ", 
		"zuwɛn", 
		"zuluye", 
		"uti", 
		"sɛtanburu", 
		"ɔkutɔburu", 
		"nowanburu", 
		"desanburu"
	], 
	"dateFormatItem-MMMMEd": "EEE d MMMM", 
	"dateFormatItem-MMMd": "d MMM", 
	"timeFormat-long": "HH:mm:ss z", 
	"months-format-abbr": [
		"zan", 
		"feb", 
		"nar", 
		"awi", 
		"mɛ", 
		"zuw", 
		"zul", 
		"uti", 
		"sɛt", 
		"ɔku", 
		"now", 
		"des"
	], 
	"timeFormat-short": "HH:mm", 
	"field-month": "kalo", 
	"dateFormatItem-MMMMd": "d MMMM", 
	"quarters-format-abbr": [
		"KS1", 
		"KS2", 
		"KS3", 
		"KS4"
	], 
	"days-format-abbr": [
		"kar", 
		"ntɛ", 
		"tar", 
		"ara", 
		"ala", 
		"jum", 
		"sib"
	], 
	"dateFormatItem-M": "M", 
	"days-format-narrow": [
		"K", 
		"N", 
		"T", 
		"A", 
		"A", 
		"J", 
		"S"
	], 
	"field-second": "sekondi", 
	"field-day": "don", 
	"months-format-narrow": [
		"Z", 
		"F", 
		"M", 
		"A", 
		"M", 
		"Z", 
		"Z", 
		"U", 
		"S", 
		"Ɔ", 
		"N", 
		"D"
	], 
	"days-standAlone-abbr": [
		"kar", 
		"ntɛ", 
		"tar", 
		"ara", 
		"ala", 
		"jum", 
		"sib"
	], 
	"dateFormat-short": "d/M/yyyy", 
	"dateFormatItem-yMMMEd": "EEE d MMM y", 
	"dateFormat-full": "EEEE d MMMM y", 
	"dateFormatItem-Md": "d/M", 
	"dateFormatItem-yMEd": "EEE d/M/y", 
	"months-format-wide": [
		"zanwuye", 
		"feburuye", 
		"marisi", 
		"awirili", 
		"mɛ", 
		"zuwɛn", 
		"zuluye", 
		"uti", 
		"sɛtanburu", 
		"ɔkutɔburu", 
		"nowanburu", 
		"desanburu"
	], 
	"quarters-format-wide": [
		"kalo saba fɔlɔ", 
		"kalo saba filanan", 
		"kalo saba sabanan", 
		"kalo saba naaninan"
	], 
	"days-format-wide": [
		"kari", 
		"ntɛnɛ", 
		"tarata", 
		"araba", 
		"alamisa", 
		"juma", 
		"sibiri"
	], 
	"eraNarrow": [
		"J.-C. ɲɛ", 
		"ni J.-C."
	]
})