({
	"dateFormatItem-yM": "M/y", 
	"field-dayperiod": "tizi g wass: tifawt / tadggʷat", 
	"dayPeriods-format-wide-pm": "tadggʷat", 
	"dateFormatItem-yQ": "'ak'Q y", 
	"field-minute": "tusdidt", 
	"eraNames": [
		"dat n ɛisa", 
		"dffir n ɛisa"
	], 
	"dateFormatItem-MMMEd": "E d MMM", 
	"field-day-relative+-1": "iḍlli", 
	"dateFormatItem-MMdd": "dd/MM", 
	"dateFormatItem-yQQQ": "QQQ y", 
	"field-weekday": "ass g imalass", 
	"days-standAlone-wide": [
		"asamas", 
		"aynas", 
		"asinas", 
		"akṛas", 
		"akwas", 
		"asimwas", 
		"asiḍyas"
	], 
	"dateFormatItem-MMM": "MMM", 
	"months-standAlone-narrow": [
		"i", 
		"b", 
		"m", 
		"i", 
		"m", 
		"y", 
		"y", 
		"ɣ", 
		"c", 
		"k", 
		"n", 
		"d"
	], 
	"dayPeriods-format-wide-am": "tifawt", 
	"field-era": "tasut", 
	"field-hour": "tasragt", 
	"quarters-standAlone-abbr": [
		"ak 1", 
		"ak 2", 
		"ak 3", 
		"ak 4"
	], 
	"dateFormatItem-y": "y", 
	"dateFormatItem-MMMdd": "dd MMM", 
	"timeFormat-full": "HH:mm:ss zzzz", 
	"dateFormatItem-Med": "EEE d/M", 
	"months-standAlone-abbr": [
		"inn", 
		"bṛa", 
		"maṛ", 
		"ibr", 
		"may", 
		"yun", 
		"yul", 
		"ɣuc", 
		"cut", 
		"ktu", 
		"nuw", 
		"duj"
	], 
	"dateFormatItem-yMMM": "MMM y", 
	"field-day-relative+0": "assa", 
	"field-day-relative+1": "askka", 
	"eraAbbr": [
		"daɛ", 
		"dfɛ"
	], 
	"dateFormat-long": "d MMMM y", 
	"timeFormat-medium": "HH:mm:ss", 
	"field-zone": "akud n ugmmaḍ", 
	"dateFormatItem-MMd": "d/MM", 
	"dateFormat-medium": "d MMM, y", 
	"quarters-standAlone-wide": [
		"akṛaḍyur 1", 
		"akṛaḍyur 2", 
		"akṛaḍyur 3", 
		"akṛaḍyur 4"
	], 
	"dateFormatItem-yMMMM": "MMMM y", 
	"dateFormatItem-ms": "m:ss", 
	"field-year": "asggʷas", 
	"field-week": "imalass", 
	"months-standAlone-wide": [
		"innayr", 
		"bṛayṛ", 
		"maṛṣ", 
		"ibrir", 
		"mayyu", 
		"yunyu", 
		"yulyuz", 
		"ɣuct", 
		"cutanbir", 
		"ktubr", 
		"nuwanbir", 
		"dujanbir"
	], 
	"dateFormatItem-MMMMEd": "EEE d MMMM", 
	"dateFormatItem-MMMd": "d MMM", 
	"timeFormat-long": "HH:mm:ss z", 
	"months-format-abbr": [
		"inn", 
		"bṛa", 
		"maṛ", 
		"ibr", 
		"may", 
		"yun", 
		"yul", 
		"ɣuc", 
		"cut", 
		"ktu", 
		"nuw", 
		"duj"
	], 
	"timeFormat-short": "HH:mm", 
	"field-month": "ayyur", 
	"dateFormatItem-MMMMd": "d MMMM", 
	"quarters-format-abbr": [
		"ak 1", 
		"ak 2", 
		"ak 3", 
		"ak 4"
	], 
	"days-format-abbr": [
		"asi", 
		"ayn", 
		"asi", 
		"akṛ", 
		"akw", 
		"asim", 
		"Asiḍ"
	], 
	"dateFormatItem-M": "M", 
	"field-second": "tasint", 
	"field-day": "ass", 
	"months-format-narrow": [
		"i", 
		"b", 
		"m", 
		"i", 
		"m", 
		"y", 
		"y", 
		"ɣ", 
		"c", 
		"k", 
		"n", 
		"d"
	], 
	"days-standAlone-abbr": [
		"asi", 
		"ayn", 
		"asi", 
		"akṛ", 
		"akw", 
		"asim", 
		"Asiḍ"
	], 
	"dateFormat-short": "d/M/yyyy", 
	"dateFormatItem-yMMMEd": "EEE d MMM y", 
	"dateFormat-full": "EEEE d MMMM y", 
	"dateFormatItem-Md": "d/M", 
	"dateFormatItem-yMEd": "EEE d/M/y", 
	"months-format-wide": [
		"innayr", 
		"bṛayṛ", 
		"maṛṣ", 
		"ibrir", 
		"mayyu", 
		"yunyu", 
		"yulyuz", 
		"ɣuct", 
		"cutanbir", 
		"ktubr", 
		"nuwanbir", 
		"dujanbir"
	], 
	"quarters-format-wide": [
		"akṛaḍyur 1", 
		"akṛaḍyur 2", 
		"akṛaḍyur 3", 
		"akṛaḍyur 4"
	], 
	"days-format-wide": [
		"asamas", 
		"aynas", 
		"asinas", 
		"akṛas", 
		"akwas", 
		"asimwas", 
		"asiḍyas"
	], 
	"eraNarrow": [
		"daɛ", 
		"dfɛ"
	]
})