({
	"field-dayperiod": "enne/pärast lõunat", 
	"dayPeriods-format-wide-pm": "pärast keskpäeva", 
	"field-minute": "minut", 
	"eraNames": [
		"enne meie aega", 
		"meie aja järgi"
	], 
	"dateFormatItem-MMMEd": "E, d. MMM", 
	"field-day-relative+-1": "eile", 
	"dateFormatItem-hms": "h:mm.ss a", 
	"dateFormatItem-MMdd": "dd.MM", 
	"field-day-relative+-2": "üleeile", 
	"field-weekday": "nädalapäev", 
	"field-day-relative+-3": "üleüleeile", 
	"days-standAlone-wide": [
		"pühapäev", 
		"esmaspäev", 
		"teisipäev", 
		"kolmapäev", 
		"neljapäev", 
		"reede", 
		"laupäev"
	], 
	"months-standAlone-narrow": [
		"J", 
		"V", 
		"M", 
		"A", 
		"M", 
		"J", 
		"J", 
		"A", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"dayPeriods-format-wide-am": "enne keskpäeva", 
	"field-era": "ajastu", 
	"field-hour": "tund", 
	"quarters-standAlone-abbr": [
		"K1", 
		"K2", 
		"K3", 
		"K4"
	], 
	"timeFormat-full": "H:mm.ss zzzz", 
	"months-standAlone-abbr": [
		"jaan", 
		"veebr", 
		"märts", 
		"apr", 
		"mai", 
		"juuni", 
		"juuli", 
		"aug", 
		"sept", 
		"okt", 
		"nov", 
		"dets"
	], 
	"field-day-relative+0": "täna", 
	"days-standAlone-narrow": [
		"P", 
		"E", 
		"T", 
		"K", 
		"N", 
		"R", 
		"L"
	], 
	"field-day-relative+1": "homme", 
	"eraAbbr": [
		"e.m.a.", 
		"m.a.j."
	], 
	"field-day-relative+2": "ülehomme", 
	"field-day-relative+3": "üleülehomme", 
	"dateFormatItem-yyyyMM": "MM.yyyy", 
	"dateFormatItem-yyyyMMMM": "MMMM y", 
	"dateFormat-long": "d. MMMM y", 
	"timeFormat-medium": "H:mm.ss", 
	"field-zone": "vöönd", 
	"dateFormatItem-Hm": "H:mm", 
	"dateFormat-medium": "dd.MM.yyyy", 
	"dateFormatItem-Hms": "H:mm.ss", 
	"quarters-standAlone-wide": [
		"1. kvartal", 
		"2. kvartal", 
		"3. kvartal", 
		"4. kvartal"
	], 
	"field-year": "aasta", 
	"field-week": "nädal", 
	"months-standAlone-wide": [
		"jaanuar", 
		"veebruar", 
		"märts", 
		"aprill", 
		"mai", 
		"juuni", 
		"juuli", 
		"august", 
		"september", 
		"oktoober", 
		"november", 
		"detsember"
	], 
	"dateFormatItem-MMMMEd": "E, d. MMMM", 
	"dateFormatItem-MMMd": "d. MMM", 
	"dateFormatItem-yyQ": "Q. yy", 
	"timeFormat-long": "H:mm.ss z", 
	"months-format-abbr": [
		"jaan", 
		"veebr", 
		"märts", 
		"apr", 
		"mai", 
		"juuni", 
		"juuli", 
		"aug", 
		"sept", 
		"okt", 
		"nov", 
		"dets"
	], 
	"timeFormat-short": "H:mm", 
	"dateFormatItem-H": "H", 
	"field-month": "kuu", 
	"dateFormatItem-MMMMd": "d. MMMM", 
	"quarters-format-abbr": [
		"K1", 
		"K2", 
		"K3", 
		"K4"
	], 
	"days-format-abbr": [
		"P", 
		"E", 
		"T", 
		"K", 
		"N", 
		"R", 
		"L"
	], 
	"dateFormatItem-mmss": "mm.ss", 
	"days-format-narrow": [
		"P", 
		"E", 
		"T", 
		"K", 
		"N", 
		"R", 
		"L"
	], 
	"field-second": "sekund", 
	"field-day": "päev", 
	"dateFormatItem-MEd": "E, d.M", 
	"months-format-narrow": [
		"J", 
		"V", 
		"M", 
		"A", 
		"M", 
		"J", 
		"J", 
		"A", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"days-standAlone-abbr": [
		"P", 
		"E", 
		"T", 
		"K", 
		"N", 
		"R", 
		"L"
	], 
	"dayPeriods-format-abbr-pm": "p.k.", 
	"dateFormat-short": "dd.MM.yy", 
	"dateFormatItem-yMMMEd": "EEE, d. MMM y", 
	"dateFormat-full": "EEEE, d. MMMM y", 
	"months-format-wide": [
		"jaanuar", 
		"veebruar", 
		"märts", 
		"aprill", 
		"mai", 
		"juuni", 
		"juuli", 
		"august", 
		"september", 
		"oktoober", 
		"november", 
		"detsember"
	], 
	"dayPeriods-format-abbr-am": "e.k.", 
	"quarters-format-wide": [
		"1. kvartal", 
		"2. kvartal", 
		"3. kvartal", 
		"4. kvartal"
	], 
	"days-format-wide": [
		"pühapäev", 
		"esmaspäev", 
		"teisipäev", 
		"kolmapäev", 
		"neljapäev", 
		"reede", 
		"laupäev"
	], 
	"eraNarrow": [
		"e.m.a.", 
		"m.a.j."
	]
})