({
	"dateFormatItem-yM": "M/y", 
	"field-dayperiod": "N'ụtụtụ/N'anyasị", 
	"dayPeriods-format-wide-pm": "P.M.", 
	"dateFormatItem-yQ": "Q y", 
	"field-minute": "Nkeji", 
	"eraNames": [
		"Tupu Kristi", 
		"Afọ Kristi"
	], 
	"dateFormatItem-MMMEd": "E, MMM d", 
	"field-day-relative+-1": "Nnyaafụ", 
	"dateFormatItem-yQQQ": "QQQ y", 
	"field-weekday": "Ụbọchị izu", 
	"days-standAlone-wide": [
		"Mbọsị Ụka", 
		"Mọnde", 
		"Tiuzdee", 
		"Wenezdee", 
		"Tọọzdee", 
		"Fraịdee", 
		"Satọdee"
	], 
	"dateFormatItem-MMM": "LLL", 
	"dayPeriods-format-wide-am": "A.M.", 
	"field-era": "Agba", 
	"field-hour": "Elekere", 
	"quarters-standAlone-abbr": [
		"Ọ1", 
		"Ọ2", 
		"Ọ3", 
		"Ọ4"
	], 
	"dateFormatItem-y": "y", 
	"timeFormat-full": "h:mm:ss a zzzz", 
	"months-standAlone-abbr": [
		"Jen", 
		"Feb", 
		"Maa", 
		"Epr", 
		"Mee", 
		"Juu", 
		"Jul", 
		"Ọgọ", 
		"Sep", 
		"Ọkt", 
		"Nov", 
		"Dis"
	], 
	"dateFormatItem-yMMM": "MMM y", 
	"field-day-relative+0": "Taata", 
	"field-day-relative+1": "Echi", 
	"eraAbbr": [
		"T.K.", 
		"A.K."
	], 
	"dateFormat-long": "d MMMM y", 
	"timeFormat-medium": "h:mm:ss a", 
	"field-zone": "Mpaghara oge", 
	"dateFormatItem-Hm": "HH:mm", 
	"dateFormat-medium": "d MMM y", 
	"dateFormatItem-Hms": "HH:mm:ss", 
	"quarters-standAlone-wide": [
		"Ọkara 1", 
		"Ọkara 2", 
		"Ọkara 3", 
		"Ọkara 4"
	], 
	"dateFormatItem-yMMMM": "MMMM y", 
	"dateFormatItem-ms": "mm:ss", 
	"field-year": "Afọ", 
	"field-week": "Izu", 
	"months-standAlone-wide": [
		"Jenụwarị", 
		"Febrụwarị", 
		"Maachị", 
		"Eprel", 
		"Mee", 
		"Juun", 
		"Julaị", 
		"Ọgọọst", 
		"Septemba", 
		"Ọktoba", 
		"Novemba", 
		"Disemba"
	], 
	"dateFormatItem-MMMMEd": "E, MMMM d", 
	"dateFormatItem-MMMd": "MMM d", 
	"timeFormat-long": "h:mm:ss a z", 
	"months-format-abbr": [
		"Jen", 
		"Feb", 
		"Maa", 
		"Epr", 
		"Mee", 
		"Juu", 
		"Jul", 
		"Ọgọ", 
		"Sep", 
		"Ọkt", 
		"Nov", 
		"Dis"
	], 
	"timeFormat-short": "h:mm a", 
	"field-month": "Ọnwa", 
	"dateFormatItem-MMMMd": "MMMM d", 
	"quarters-format-abbr": [
		"Ọ1", 
		"Ọ2", 
		"Ọ3", 
		"Ọ4"
	], 
	"days-format-abbr": [
		"Ụka", 
		"Mọn", 
		"Tiu", 
		"Wen", 
		"Tọọ", 
		"Fraị", 
		"Sat"
	], 
	"dateFormatItem-M": "L", 
	"field-second": "Nkejinta", 
	"field-day": "Ụbọchị", 
	"dateFormatItem-MEd": "E, M/d", 
	"dateFormatItem-hm": "h:mm a", 
	"days-standAlone-abbr": [
		"Ụka", 
		"Mọn", 
		"Tiu", 
		"Wen", 
		"Tọọ", 
		"Fraị", 
		"Sat"
	], 
	"dateFormat-short": "dd/MM/yyyy", 
	"dateFormatItem-yMMMEd": "EEE, MMM d, y", 
	"dateFormat-full": "EEEE, d MMMM y", 
	"dateFormatItem-Md": "M/d", 
	"dateFormatItem-yMEd": "EEE, M/d/y", 
	"months-format-wide": [
		"Jenụwarị", 
		"Febrụwarị", 
		"Maachị", 
		"Eprel", 
		"Mee", 
		"Juun", 
		"Julaị", 
		"Ọgọọst", 
		"Septemba", 
		"Ọktoba", 
		"Novemba", 
		"Disemba"
	], 
	"dateFormatItem-d": "d", 
	"quarters-format-wide": [
		"Ọkara 1", 
		"Ọkara 2", 
		"Ọkara 3", 
		"Ọkara 4"
	], 
	"days-format-wide": [
		"Mbọsị Ụka", 
		"Mọnde", 
		"Tiuzdee", 
		"Wenezdee", 
		"Tọọzdee", 
		"Fraịdee", 
		"Satọdee"
	], 
	"eraNarrow": [
		"T.K.", 
		"A.K."
	]
})