({
	"dateFormatItem-yM": "M/y", 
	"field-dayperiod": "Na lâ", 
	"dayPeriods-format-wide-pm": "LK", 
	"dateFormatItem-yQ": "'F'Q y", 
	"field-minute": "Ndurü ngbonga", 
	"eraNames": [
		"Kôzo na Krîstu", 
		"Na pekô tî Krîstu"
	], 
	"dateFormatItem-MMMEd": "E d MMM", 
	"field-day-relative+-1": "Bîrï", 
	"dateFormatItem-MMdd": "dd/MM", 
	"dateFormatItem-yQQQ": "QQQ y", 
	"field-weekday": "Bïkua", 
	"days-standAlone-wide": [
		"Bikua-ôko", 
		"Bïkua-ûse", 
		"Bïkua-ptâ", 
		"Bïkua-usïö", 
		"Bïkua-okü", 
		"Lâpôsö", 
		"Lâyenga"
	], 
	"dateFormatItem-MMM": "MMM", 
	"months-standAlone-narrow": [
		"N", 
		"F", 
		"M", 
		"N", 
		"B", 
		"F", 
		"L", 
		"K", 
		"M", 
		"N", 
		"N", 
		"K"
	], 
	"dayPeriods-format-wide-am": "ND", 
	"field-era": "Kùotângo", 
	"field-hour": "Ngbonga", 
	"quarters-standAlone-abbr": [
		"F4-1", 
		"F4-2", 
		"F4-3", 
		"F4-4"
	], 
	"dateFormatItem-y": "y", 
	"dateFormatItem-MMMdd": "dd MMM", 
	"timeFormat-full": "HH:mm:ss zzzz", 
	"dateFormatItem-Med": "EEE d/M", 
	"months-standAlone-abbr": [
		"Nye", 
		"Ful", 
		"Mbä", 
		"Ngu", 
		"Bêl", 
		"Fön", 
		"Len", 
		"Kük", 
		"Mvu", 
		"Ngb", 
		"Nab", 
		"Kak"
	], 
	"dateFormatItem-yMMM": "MMM y", 
	"field-day-relative+0": "Lâsô", 
	"days-standAlone-narrow": [
		"K", 
		"S", 
		"T", 
		"S", 
		"K", 
		"P", 
		"Y"
	], 
	"field-day-relative+1": "Kêkerêke", 
	"eraAbbr": [
		"KnK", 
		"NpK"
	], 
	"dateFormat-long": "d MMMM y", 
	"timeFormat-medium": "HH:mm:ss", 
	"field-zone": "Zukangbonga", 
	"dateFormatItem-MMd": "d/MM", 
	"dateFormat-medium": "d MMM, y", 
	"quarters-standAlone-wide": [
		"Fângbisïö ôko", 
		"Fângbisïö ûse", 
		"Fângbisïö otâ", 
		"Fângbisïö usïö"
	], 
	"dateFormatItem-yMMMM": "MMMM y", 
	"dateFormatItem-ms": "m:ss", 
	"field-year": "Ngû", 
	"field-week": "Dimâsi", 
	"months-standAlone-wide": [
		"Nyenye", 
		"Fulundïgi", 
		"Mbängü", 
		"Ngubùe", 
		"Bêläwü", 
		"Föndo", 
		"Lengua", 
		"Kükürü", 
		"Mvuka", 
		"Ngberere", 
		"Nabändüru", 
		"Kakauka"
	], 
	"dateFormatItem-MMMMEd": "EEE d MMMM", 
	"dateFormatItem-MMMd": "d MMM", 
	"timeFormat-long": "HH:mm:ss z", 
	"months-format-abbr": [
		"Nye", 
		"Ful", 
		"Mbä", 
		"Ngu", 
		"Bêl", 
		"Fön", 
		"Len", 
		"Kük", 
		"Mvu", 
		"Ngb", 
		"Nab", 
		"Kak"
	], 
	"timeFormat-short": "HH:mm", 
	"field-month": "Nze", 
	"dateFormatItem-MMMMd": "d MMMM", 
	"quarters-format-abbr": [
		"F4-1", 
		"F4-2", 
		"F4-3", 
		"F4-4"
	], 
	"days-format-abbr": [
		"Bk1", 
		"Bk2", 
		"Bk3", 
		"Bk4", 
		"Bk5", 
		"Lâp", 
		"Lây"
	], 
	"dateFormatItem-M": "M", 
	"days-format-narrow": [
		"K", 
		"S", 
		"T", 
		"S", 
		"K", 
		"P", 
		"Y"
	], 
	"field-second": "Nzîna ngbonga", 
	"field-day": "Lâ", 
	"months-format-narrow": [
		"N", 
		"F", 
		"M", 
		"N", 
		"B", 
		"F", 
		"L", 
		"K", 
		"M", 
		"N", 
		"N", 
		"K"
	], 
	"days-standAlone-abbr": [
		"Bk1", 
		"Bk2", 
		"Bk3", 
		"Bk4", 
		"Bk5", 
		"Lâp", 
		"Lây"
	], 
	"dateFormat-short": "d/M/yyyy", 
	"dateFormatItem-yMMMEd": "EEE d MMM y", 
	"dateFormat-full": "EEEE d MMMM y", 
	"dateFormatItem-Md": "d/M", 
	"dateFormatItem-yMEd": "EEE d/M/y", 
	"months-format-wide": [
		"Nyenye", 
		"Fulundïgi", 
		"Mbängü", 
		"Ngubùe", 
		"Bêläwü", 
		"Föndo", 
		"Lengua", 
		"Kükürü", 
		"Mvuka", 
		"Ngberere", 
		"Nabändüru", 
		"Kakauka"
	], 
	"quarters-format-wide": [
		"Fângbisïö ôko", 
		"Fângbisïö ûse", 
		"Fângbisïö otâ", 
		"Fângbisïö usïö"
	], 
	"days-format-wide": [
		"Bikua-ôko", 
		"Bïkua-ûse", 
		"Bïkua-ptâ", 
		"Bïkua-usïö", 
		"Bïkua-okü", 
		"Lâpôsö", 
		"Lâyenga"
	], 
	"eraNarrow": [
		"KnK", 
		"NpK"
	]
})