({
	"dateFormatItem-yM": "M/y", 
	"field-dayperiod": "Mũthenya", 
	"dayPeriods-format-wide-pm": "UT", 
	"dateFormatItem-yQ": "Q y", 
	"field-minute": "Ndagĩka", 
	"eraNames": [
		"Mbere ya Kristo", 
		"Thutha wa Kristo"
	], 
	"dateFormatItem-MMMEd": "E, MMM d", 
	"field-day-relative+-1": "Ĩgoro", 
	"dateFormatItem-yQQQ": "QQQ y", 
	"field-weekday": "Mũthenya kiumia-inĩ", 
	"days-standAlone-wide": [
		"Kiumia", 
		"Njumatatu", 
		"Njumaine", 
		"Njumatano", 
		"Aramithi", 
		"Njumaa", 
		"NJumamothii"
	], 
	"dateFormatItem-MMM": "LLL", 
	"months-standAlone-narrow": [
		"M", 
		"K", 
		"K", 
		"K", 
		"G", 
		"G", 
		"M", 
		"K", 
		"K", 
		"I", 
		"I", 
		"I"
	], 
	"dayPeriods-format-wide-am": "KI", 
	"field-era": "Ivinda", 
	"field-hour": "Ithaa", 
	"quarters-standAlone-abbr": [
		"K1", 
		"K1", 
		"K1", 
		"K1"
	], 
	"dateFormatItem-y": "y", 
	"timeFormat-full": "h:mm:ss a zzzz", 
	"months-standAlone-abbr": [
		"Mbe", 
		"Kai", 
		"Kat", 
		"Kan", 
		"Gat", 
		"Gan", 
		"Mug", 
		"Knn", 
		"Ken", 
		"Iku", 
		"Imw", 
		"Igi"
	], 
	"dateFormatItem-yMMM": "MMM y", 
	"field-day-relative+0": "Ũmũnthĩ", 
	"days-standAlone-narrow": [
		"K", 
		"N", 
		"N", 
		"N", 
		"A", 
		"M", 
		"N"
	], 
	"field-day-relative+1": "Rũciũ", 
	"eraAbbr": [
		"MK", 
		"TK"
	], 
	"dateFormat-long": "d MMMM y", 
	"timeFormat-medium": "h:mm:ss a", 
	"field-zone": "Gĩthaa", 
	"dateFormatItem-Hm": "HH:mm", 
	"dateFormat-medium": "d MMM y", 
	"dateFormatItem-Hms": "HH:mm:ss", 
	"quarters-standAlone-wide": [
		"Kuota ya mbere", 
		"Kuota ya Kaĩrĩ", 
		"Kuota ya kathatu", 
		"Kuota ya kana"
	], 
	"dateFormatItem-yMMMM": "MMMM y", 
	"dateFormatItem-ms": "mm:ss", 
	"field-year": "Mwaka", 
	"field-week": "Kiumia", 
	"months-standAlone-wide": [
		"Mweri wa mbere", 
		"Mweri wa kaĩri", 
		"Mweri wa kathatũ", 
		"Mweri wa kana", 
		"Mweri wa gatano", 
		"Mweri wa gatantatũ", 
		"Mweri wa mũgwanja", 
		"Mweri wa kanana", 
		"Mweri wa kenda", 
		"Mweri wa ikũmi", 
		"Mweri wa ikũmi na ũmwe", 
		"Mweri wa ikũmi na Kaĩrĩ"
	], 
	"dateFormatItem-MMMMEd": "E, MMMM d", 
	"dateFormatItem-MMMd": "MMM d", 
	"timeFormat-long": "h:mm:ss a z", 
	"months-format-abbr": [
		"Mbe", 
		"Kai", 
		"Kat", 
		"Kan", 
		"Gat", 
		"Gan", 
		"Mug", 
		"Knn", 
		"Ken", 
		"Iku", 
		"Imw", 
		"Igi"
	], 
	"timeFormat-short": "h:mm a", 
	"field-month": "Mweri", 
	"dateFormatItem-MMMMd": "MMMM d", 
	"quarters-format-abbr": [
		"K1", 
		"K1", 
		"K1", 
		"K1"
	], 
	"days-format-abbr": [
		"Kma", 
		"Tat", 
		"Ine", 
		"Tan", 
		"Arm", 
		"Maa", 
		"NMM"
	], 
	"dateFormatItem-M": "L", 
	"days-format-narrow": [
		"K", 
		"N", 
		"N", 
		"N", 
		"A", 
		"M", 
		"N"
	], 
	"field-second": "Sekondi", 
	"field-day": "Mũthenya", 
	"dateFormatItem-MEd": "E, M/d", 
	"months-format-narrow": [
		"M", 
		"K", 
		"K", 
		"K", 
		"G", 
		"G", 
		"M", 
		"K", 
		"K", 
		"I", 
		"I", 
		"I"
	], 
	"dateFormatItem-hm": "h:mm a", 
	"days-standAlone-abbr": [
		"Kma", 
		"Tat", 
		"Ine", 
		"Tan", 
		"Arm", 
		"Maa", 
		"NMM"
	], 
	"dateFormat-short": "dd/MM/yyyy", 
	"dateFormatItem-yMMMEd": "EEE, MMM d, y", 
	"dateFormat-full": "EEEE, d MMMM y", 
	"dateFormatItem-Md": "M/d", 
	"dateFormatItem-yMEd": "EEE, M/d/y", 
	"months-format-wide": [
		"Mweri wa mbere", 
		"Mweri wa kaĩri", 
		"Mweri wa kathatũ", 
		"Mweri wa kana", 
		"Mweri wa gatano", 
		"Mweri wa gatantatũ", 
		"Mweri wa mũgwanja", 
		"Mweri wa kanana", 
		"Mweri wa kenda", 
		"Mweri wa ikũmi", 
		"Mweri wa ikũmi na ũmwe", 
		"Mweri wa ikũmi na Kaĩrĩ"
	], 
	"dateFormatItem-d": "d", 
	"quarters-format-wide": [
		"Kuota ya mbere", 
		"Kuota ya Kaĩrĩ", 
		"Kuota ya kathatu", 
		"Kuota ya kana"
	], 
	"days-format-wide": [
		"Kiumia", 
		"Njumatatu", 
		"Njumaine", 
		"Njumatano", 
		"Aramithi", 
		"Njumaa", 
		"NJumamothii"
	], 
	"eraNarrow": [
		"MK", 
		"TK"
	]
})