({
	"dateFormatItem-yM": "M/y", 
	"field-dayperiod": "Peryod dan lazourne", 
	"dateFormatItem-yQ": "Q y", 
	"field-minute": "Minit", 
	"eraNames": [
		"avan Zezi-Krist", 
		"apre Zezi-Krist"
	], 
	"dateFormatItem-MMMEd": "E d MMM", 
	"field-day-relative+-1": "Yer", 
	"dateFormatItem-MMdd": "dd/MM", 
	"dateFormatItem-yQQQ": "QQQ y", 
	"field-weekday": "Zour lasemenn", 
	"days-standAlone-wide": [
		"dimans", 
		"lindi", 
		"mardi", 
		"merkredi", 
		"zedi", 
		"vandredi", 
		"samdi"
	], 
	"dateFormatItem-MMM": "MMM", 
	"months-standAlone-narrow": [
		"z", 
		"f", 
		"m", 
		"a", 
		"m", 
		"z", 
		"z", 
		"o", 
		"s", 
		"o", 
		"n", 
		"d"
	], 
	"field-era": "Lepok", 
	"field-hour": "Ler", 
	"quarters-standAlone-abbr": [
		"T1", 
		"T2", 
		"T3", 
		"T4"
	], 
	"dateFormatItem-y": "y", 
	"dateFormatItem-yyMMMEEEd": "EEE d MMM yy", 
	"dateFormatItem-MMMdd": "dd MMM", 
	"timeFormat-full": "HH:mm:ss zzzz", 
	"dateFormatItem-Med": "EEE d/M", 
	"months-standAlone-abbr": [
		"zan", 
		"fev", 
		"mar", 
		"avr", 
		"me", 
		"zin", 
		"zil", 
		"out", 
		"sep", 
		"okt", 
		"nov", 
		"des"
	], 
	"dateFormatItem-yMMM": "MMM y", 
	"field-day-relative+0": "Zordi", 
	"days-standAlone-narrow": [
		"d", 
		"l", 
		"m", 
		"m", 
		"z", 
		"v", 
		"s"
	], 
	"field-day-relative+1": "Demin", 
	"eraAbbr": [
		"av. Z-K", 
		"ap. Z-K"
	], 
	"dateFormat-long": "d MMMM y", 
	"timeFormat-medium": "HH:mm:ss", 
	"field-zone": "Peryod letan", 
	"dateFormatItem-MMd": "d/MM", 
	"dateFormat-medium": "d MMM, y", 
	"dateFormatItem-yyMM": "MM/yy", 
	"dateFormatItem-yyMMM": "MMM yy", 
	"quarters-standAlone-wide": [
		"1e trimes", 
		"2em trimes", 
		"3em trimes", 
		"4em trimes"
	], 
	"dateFormatItem-yMMMM": "MMMM y", 
	"dateFormatItem-ms": "m:ss", 
	"field-year": "Lane", 
	"dateFormatItem-yyMMMd": "d MMM yy", 
	"field-week": "Semenn", 
	"months-standAlone-wide": [
		"zanvie", 
		"fevriye", 
		"mars", 
		"avril", 
		"me", 
		"zin", 
		"zilye", 
		"out", 
		"septam", 
		"oktob", 
		"novam", 
		"desam"
	], 
	"dateFormatItem-MMMMEd": "EEE d MMMM", 
	"dateFormatItem-MMMd": "d MMM", 
	"timeFormat-long": "HH:mm:ss z", 
	"months-format-abbr": [
		"zan", 
		"fev", 
		"mar", 
		"avr", 
		"me", 
		"zin", 
		"zil", 
		"out", 
		"sep", 
		"okt", 
		"nov", 
		"des"
	], 
	"timeFormat-short": "HH:mm", 
	"field-month": "Mwa", 
	"dateFormatItem-MMMMd": "d MMMM", 
	"quarters-format-abbr": [
		"T1", 
		"T2", 
		"T3", 
		"T4"
	], 
	"days-format-abbr": [
		"dim", 
		"lin", 
		"mar", 
		"mer", 
		"ze", 
		"van", 
		"sam"
	], 
	"dateFormatItem-M": "M", 
	"days-format-narrow": [
		"d", 
		"l", 
		"m", 
		"m", 
		"z", 
		"v", 
		"s"
	], 
	"field-second": "Segonn", 
	"field-day": "Zour", 
	"months-format-narrow": [
		"z", 
		"f", 
		"m", 
		"a", 
		"m", 
		"z", 
		"z", 
		"o", 
		"s", 
		"o", 
		"n", 
		"d"
	], 
	"days-standAlone-abbr": [
		"dim", 
		"lin", 
		"mar", 
		"mer", 
		"ze", 
		"van", 
		"sam"
	], 
	"dateFormat-short": "d/M/yyyy", 
	"dateFormatItem-yMMMEd": "EEE d MMM y", 
	"dateFormat-full": "EEEE d MMMM y", 
	"dateFormatItem-Md": "d/M", 
	"dateFormatItem-yMEd": "EEE d/M/y", 
	"months-format-wide": [
		"zanvie", 
		"fevriye", 
		"mars", 
		"avril", 
		"me", 
		"zin", 
		"zilye", 
		"out", 
		"septam", 
		"oktob", 
		"novam", 
		"desam"
	], 
	"quarters-format-wide": [
		"1e trimes", 
		"2em trimes", 
		"3em trimes", 
		"4em trimes"
	], 
	"days-format-wide": [
		"dimans", 
		"lindi", 
		"mardi", 
		"merkredi", 
		"zedi", 
		"vandredi", 
		"samdi"
	], 
	"eraNarrow": [
		"av. Z-K", 
		"ap. Z-K"
	]
})