({
	"field-dayperiod": "ден", 
	"dayPeriods-format-wide-pm": "сл. об.", 
	"field-minute": "минута", 
	"eraNames": [
		"пр.Хр.", 
		"сл.Хр."
	], 
	"dateFormatItem-MMMEd": "d MMM, E", 
	"field-day-relative+-1": "Вчера", 
	"dateFormatItem-hms": "h:mm:ss a", 
	"dateFormatItem-MMdd": "dd.MM", 
	"field-day-relative+-2": "Онзи ден", 
	"field-weekday": "Ден от седмицата", 
	"days-standAlone-wide": [
		"неделя", 
		"понеделник", 
		"вторник", 
		"сряда", 
		"четвъртък", 
		"петък", 
		"събота"
	], 
	"months-standAlone-narrow": [
		"я", 
		"ф", 
		"м", 
		"а", 
		"м", 
		"ю", 
		"ю", 
		"а", 
		"с", 
		"о", 
		"н", 
		"д"
	], 
	"dayPeriods-format-wide-am": "пр. об.", 
	"field-era": "ера", 
	"field-hour": "час", 
	"quarters-standAlone-abbr": [
		"I трим.", 
		"II трим.", 
		"III трим.", 
		"IV трим."
	], 
	"timeFormat-full": "HH:mm:ss zzzz", 
	"dateFormatItem-yyyy": "y", 
	"months-standAlone-abbr": [
		"ян.", 
		"февр.", 
		"март", 
		"апр.", 
		"май", 
		"юни", 
		"юли", 
		"авг.", 
		"септ.", 
		"окт.", 
		"ноем.", 
		"дек."
	], 
	"dateFormatItem-Ed": "E d", 
	"field-day-relative+0": "Днес", 
	"days-standAlone-narrow": [
		"н", 
		"п", 
		"в", 
		"с", 
		"ч", 
		"п", 
		"с"
	], 
	"field-day-relative+1": "Утре", 
	"eraAbbr": [
		"пр. н. е.", 
		"от н. е."
	], 
	"field-day-relative+2": "Вдругиден", 
	"dateFormatItem-yyyyMM": "MM.yyyy", 
	"dateFormatItem-yyyyMMMM": "MMMM y", 
	"dateFormat-long": "dd MMMM y", 
	"timeFormat-medium": "HH:mm:ss", 
	"field-zone": "зона", 
	"dateFormatItem-Hm": "HH:mm", 
	"dateFormatItem-yyMM": "MM.yy", 
	"dateFormat-medium": "dd.MM.yyyy", 
	"dateFormatItem-Hms": "HH:mm:ss", 
	"quarters-standAlone-wide": [
		"1-во тримесечие", 
		"2-ро тримесечие", 
		"3-то тримесечие", 
		"4-то тримесечие"
	], 
	"dateFormatItem-yyyyQQQQ": "QQQQ y 'г'.", 
	"field-year": "година", 
	"field-week": "седмица", 
	"months-standAlone-wide": [
		"януари", 
		"февруари", 
		"март", 
		"април", 
		"май", 
		"юни", 
		"юли", 
		"август", 
		"септември", 
		"октомври", 
		"ноември", 
		"декември"
	], 
	"dateFormatItem-yyQ": "Q yy", 
	"timeFormat-long": "HH:mm:ss z", 
	"months-format-abbr": [
		"ян.", 
		"февр.", 
		"март", 
		"апр.", 
		"май", 
		"юни", 
		"юли", 
		"авг.", 
		"септ.", 
		"окт.", 
		"ноем.", 
		"дек."
	], 
	"timeFormat-short": "HH:mm", 
	"dateFormatItem-H": "HH", 
	"field-month": "месец", 
	"dateFormatItem-MMMMd": "d MMMM", 
	"quarters-format-abbr": [
		"I трим.", 
		"II трим.", 
		"III трим.", 
		"IV трим."
	], 
	"days-format-abbr": [
		"нд", 
		"пн", 
		"вт", 
		"ср", 
		"чт", 
		"пт", 
		"сб"
	], 
	"dateFormatItem-MMMMdd": "dd MMMM", 
	"dateFormatItem-mmss": "mm:ss", 
	"days-format-narrow": [
		"н", 
		"п", 
		"в", 
		"с", 
		"ч", 
		"п", 
		"с"
	], 
	"field-second": "секунда", 
	"field-day": "Ден", 
	"months-format-narrow": [
		"я", 
		"ф", 
		"м", 
		"а", 
		"м", 
		"ю", 
		"ю", 
		"а", 
		"с", 
		"о", 
		"н", 
		"д"
	], 
	"dateFormatItem-hm": "h:mm a", 
	"days-standAlone-abbr": [
		"нд", 
		"пн", 
		"вт", 
		"ср", 
		"чт", 
		"пт", 
		"сб"
	], 
	"dateFormat-short": "dd.MM.yy", 
	"dateFormat-full": "dd MMMM y, EEEE", 
	"months-format-wide": [
		"януари", 
		"февруари", 
		"март", 
		"април", 
		"май", 
		"юни", 
		"юли", 
		"август", 
		"септември", 
		"октомври", 
		"ноември", 
		"декември"
	], 
	"quarters-format-wide": [
		"1-во тримесечие", 
		"2-ро тримесечие", 
		"3-то тримесечие", 
		"4-то тримесечие"
	], 
	"days-format-wide": [
		"неделя", 
		"понеделник", 
		"вторник", 
		"сряда", 
		"четвъртък", 
		"петък", 
		"събота"
	], 
	"eraNarrow": "сл.н.е."
})