({
	"dateFormatItem-yM": "M/y", 
	"field-dayperiod": "Àárọ̀/ọ̀sán", 
	"dayPeriods-format-wide-pm": "Ọ̀sán", 
	"dateFormatItem-yQ": "Q y", 
	"field-minute": "Ìsẹ́jú", 
	"eraNames": [
		"Saju Kristi", 
		"Lehin Kristi"
	], 
	"dateFormatItem-MMMEd": "E, MMM d", 
	"field-day-relative+-1": "Àná", 
	"dateFormatItem-yQQQ": "QQQ y", 
	"field-day-relative+-2": "íjẹta", 
	"field-weekday": "Ọjọ́ Ọ̀sẹ̀", 
	"field-day-relative+-3": "íjẹrin", 
	"days-standAlone-wide": [
		"Ọjọ́ Àìkú", 
		"Ọjọ́ Ajé", 
		"Ọjọ́ Ìsẹ́gun", 
		"Ọjọ́rú", 
		"Ọjọ́bọ", 
		"Ọjọ́ Ẹtì", 
		"Ọjọ́ Àbámẹ́ta"
	], 
	"dateFormatItem-MMM": "LLL", 
	"dayPeriods-format-wide-am": "Àárọ̀", 
	"field-era": "Ìgbà", 
	"field-hour": "wákàtí", 
	"quarters-standAlone-abbr": [
		"K1", 
		"K2", 
		"K3", 
		"K4"
	], 
	"dateFormatItem-y": "y", 
	"timeFormat-full": "h:mm:ss a zzzz", 
	"months-standAlone-abbr": [
		"Ṣẹ́rẹ̣", 
		"Èrèlè", 
		"Ẹrẹ̀nà", 
		"Ìgbé", 
		"Ẹ̀bibi", 
		"Òkúdu", 
		"Agẹmọ", 
		"Ògún", 
		"Owewe", 
		"Ọ̀wàrà", 
		"Bélú", 
		"Ọ̀pẹ̀"
	], 
	"dateFormatItem-yMMM": "MMM y", 
	"field-day-relative+0": "Òní", 
	"field-day-relative+1": "Ọ̀la", 
	"eraAbbr": [
		"SK", 
		"LK"
	], 
	"field-day-relative+2": "òtúùnla", 
	"field-day-relative+3": "ọjọ́mẹ́rin-òní", 
	"dateFormat-long": "d MMMM y", 
	"timeFormat-medium": "h:mm:ss a", 
	"field-zone": "Ibi Àkókò Àgbáyé", 
	"dateFormatItem-Hm": "HH:mm", 
	"dateFormat-medium": "d MMM y", 
	"dateFormatItem-Hms": "HH:mm:ss", 
	"quarters-standAlone-wide": [
		"Kọ́tà Kínní", 
		"Kọ́tà Kejì", 
		"Kọ́à Keta", 
		"Kọ́tà Kẹrin"
	], 
	"dateFormatItem-yMMMM": "MMMM y", 
	"dateFormatItem-ms": "mm:ss", 
	"field-year": "Ọdún", 
	"field-week": "Ọ̀sè", 
	"months-standAlone-wide": [
		"OṢù ṢẸ́rẹ́", 
		"OṢù Èrèlè", 
		"OṢù Ẹrẹ̀nà", 
		"OṢù Ìgbé", 
		"OṢù Ẹ̀bibi", 
		"OṢù Òkúdu", 
		"OṢù Agẹmọ", 
		"OṢù Ògún", 
		"OṢù Owewe", 
		"OṢù Ọ̀wàrà", 
		"OṢù Bélú", 
		"OṢù Ọ̀pẹ̀"
	], 
	"dateFormatItem-MMMMEd": "E, MMMM d", 
	"dateFormatItem-MMMd": "MMM d", 
	"timeFormat-long": "h:mm:ss a z", 
	"months-format-abbr": [
		"Ṣẹ́rẹ̣", 
		"Èrèlè", 
		"Ẹrẹ̀nà", 
		"Ìgbé", 
		"Ẹ̀bibi", 
		"Òkúdu", 
		"Agẹmọ", 
		"Ògún", 
		"Owewe", 
		"Ọ̀wàrà", 
		"Bélú", 
		"Ọ̀pẹ̀"
	], 
	"timeFormat-short": "h:mm a", 
	"field-month": "Osù", 
	"dateFormatItem-MMMMd": "MMMM d", 
	"quarters-format-abbr": [
		"K1", 
		"K2", 
		"K3", 
		"K4"
	], 
	"days-format-abbr": [
		"Àìkú", 
		"Ajé", 
		"Ìsẹ́gun", 
		"Ọjọ́rú", 
		"Ọjọ́bọ", 
		"Ẹtì", 
		"Àbámẹ́ta"
	], 
	"dateFormatItem-M": "L", 
	"field-second": "Ìsẹ́jú Ààyá", 
	"field-day": "Ọjọ́", 
	"dateFormatItem-MEd": "E, M/d", 
	"dateFormatItem-hm": "h:mm a", 
	"days-standAlone-abbr": [
		"Àìkú", 
		"Ajé", 
		"Ìsẹ́gun", 
		"Ọjọ́rú", 
		"Ọjọ́bọ", 
		"Ẹtì", 
		"Àbámẹ́ta"
	], 
	"dateFormat-short": "dd/MM/yyyy", 
	"dateFormatItem-yMMMEd": "EEE, MMM d, y", 
	"dateFormat-full": "EEEE, d MMMM y", 
	"dateFormatItem-Md": "M/d", 
	"dateFormatItem-yMEd": "EEE, M/d/y", 
	"months-format-wide": [
		"OṢù ṢẸ́rẹ́", 
		"OṢù Èrèlè", 
		"OṢù Ẹrẹ̀nà", 
		"OṢù Ìgbé", 
		"OṢù Ẹ̀bibi", 
		"OṢù Òkúdu", 
		"OṢù Agẹmọ", 
		"OṢù Ògún", 
		"OṢù Owewe", 
		"OṢù Ọ̀wàrà", 
		"OṢù Bélú", 
		"OṢù Ọ̀pẹ̀"
	], 
	"dateFormatItem-d": "d", 
	"quarters-format-wide": [
		"Kọ́tà Kínní", 
		"Kọ́tà Kejì", 
		"Kọ́à Keta", 
		"Kọ́tà Kẹrin"
	], 
	"days-format-wide": [
		"Ọjọ́ Àìkú", 
		"Ọjọ́ Ajé", 
		"Ọjọ́ Ìsẹ́gun", 
		"Ọjọ́rú", 
		"Ọjọ́bọ", 
		"Ọjọ́ Ẹtì", 
		"Ọjọ́ Àbámẹ́ta"
	], 
	"eraNarrow": [
		"SK", 
		"LK"
	]
})