({
	"dateFormatItem-yM": "M/y", 
	"field-dayperiod": "AM/PM", 
	"dateFormatItem-yQ": "Q y", 
	"field-minute": "Minitra", 
	"eraNames": [
		"Alohan'i JK", 
		"Aorian'i JK"
	], 
	"dateFormatItem-MMMEd": "E d MMM", 
	"field-day-relative+-1": "Omaly", 
	"dateFormatItem-MMdd": "dd/MM", 
	"dateFormatItem-yQQQ": "QQQ y", 
	"field-weekday": "Andro", 
	"days-standAlone-wide": [
		"Alahady", 
		"Alatsinainy", 
		"Talata", 
		"Alarobia", 
		"Alakamisy", 
		"Zoma", 
		"Asabotsy"
	], 
	"dateFormatItem-MMM": "MMM", 
	"months-standAlone-narrow": [
		"J", 
		"F", 
		"M", 
		"A", 
		"M", 
		"J", 
		"J", 
		"A", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"field-era": "Era", 
	"field-hour": "Ora", 
	"quarters-standAlone-abbr": [
		"T1", 
		"T2", 
		"T3", 
		"T4"
	], 
	"dateFormatItem-y": "y", 
	"dateFormatItem-yyMMMEEEd": "EEE d MMM yy", 
	"dateFormatItem-MMMdd": "dd MMM", 
	"timeFormat-full": "HH:mm:ss zzzz", 
	"dateFormatItem-Med": "EEE d/M", 
	"months-standAlone-abbr": [
		"Jan", 
		"Feb", 
		"Mar", 
		"Apr", 
		"Mey", 
		"Jon", 
		"Jol", 
		"Aog", 
		"Sep", 
		"Okt", 
		"Nov", 
		"Des"
	], 
	"dateFormatItem-yMMM": "MMM y", 
	"field-day-relative+0": "Anio", 
	"days-standAlone-narrow": [
		"A", 
		"A", 
		"T", 
		"A", 
		"A", 
		"Z", 
		"A"
	], 
	"field-day-relative+1": "Rahampitso", 
	"eraAbbr": [
		"BC", 
		"AD"
	], 
	"dateFormat-long": "d MMMM y", 
	"timeFormat-medium": "HH:mm:ss", 
	"field-zone": "Ora", 
	"dateFormatItem-MMd": "d/MM", 
	"dateFormat-medium": "d MMM, y", 
	"dateFormatItem-yyMM": "MM/yy", 
	"dateFormatItem-yyMMM": "MMM yy", 
	"quarters-standAlone-wide": [
		"Telovolana voalohany", 
		"Telovolana faharoa", 
		"Telovolana fahatelo", 
		"Telovolana fahefatra"
	], 
	"dateFormatItem-yMMMM": "MMMM y", 
	"dateFormatItem-ms": "m:ss", 
	"field-year": "Taona", 
	"dateFormatItem-yyMMMd": "d MMM yy", 
	"field-week": "Herinandro", 
	"months-standAlone-wide": [
		"Janoary", 
		"Febroary", 
		"Martsa", 
		"Aprily", 
		"Mey", 
		"Jona", 
		"Jolay", 
		"Aogositra", 
		"Septambra", 
		"Oktobra", 
		"Novambra", 
		"Desambra"
	], 
	"dateFormatItem-MMMMEd": "EEE d MMMM", 
	"dateFormatItem-MMMd": "d MMM", 
	"timeFormat-long": "HH:mm:ss z", 
	"months-format-abbr": [
		"Jan", 
		"Feb", 
		"Mar", 
		"Apr", 
		"Mey", 
		"Jon", 
		"Jol", 
		"Aog", 
		"Sep", 
		"Okt", 
		"Nov", 
		"Des"
	], 
	"timeFormat-short": "HH:mm", 
	"field-month": "Volana", 
	"dateFormatItem-MMMMd": "d MMMM", 
	"quarters-format-abbr": [
		"T1", 
		"T2", 
		"T3", 
		"T4"
	], 
	"days-format-abbr": [
		"Alah", 
		"Alats", 
		"Tal", 
		"Alar", 
		"Alak", 
		"Zom", 
		"Asab"
	], 
	"dateFormatItem-M": "M", 
	"days-format-narrow": [
		"A", 
		"A", 
		"T", 
		"A", 
		"A", 
		"Z", 
		"A"
	], 
	"field-second": "Segondra", 
	"field-day": "Andro", 
	"months-format-narrow": [
		"J", 
		"F", 
		"M", 
		"A", 
		"M", 
		"J", 
		"J", 
		"A", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"days-standAlone-abbr": [
		"Alah", 
		"Alats", 
		"Tal", 
		"Alar", 
		"Alak", 
		"Zom", 
		"Asab"
	], 
	"dateFormat-short": "d/M/yyyy", 
	"dateFormatItem-yMMMEd": "EEE d MMM y", 
	"dateFormat-full": "EEEE d MMMM y", 
	"dateFormatItem-Md": "d/M", 
	"dateFormatItem-yMEd": "EEE d/M/y", 
	"months-format-wide": [
		"Janoary", 
		"Febroary", 
		"Martsa", 
		"Aprily", 
		"Mey", 
		"Jona", 
		"Jolay", 
		"Aogositra", 
		"Septambra", 
		"Oktobra", 
		"Novambra", 
		"Desambra"
	], 
	"quarters-format-wide": [
		"Telovolana voalohany", 
		"Telovolana faharoa", 
		"Telovolana fahatelo", 
		"Telovolana fahefatra"
	], 
	"days-format-wide": [
		"Alahady", 
		"Alatsinainy", 
		"Talata", 
		"Alarobia", 
		"Alakamisy", 
		"Zoma", 
		"Asabotsy"
	], 
	"eraNarrow": [
		"BC", 
		"AD"
	]
})