// generated from ldml/main/*.xml, xpath: ldml/calendars/calendar-japanese
({
	'months@localeAlias282':{'target':"months", 'bundle':"gregorian"},
	'months-format-abbr@localeAlias283':{'target':"months-format-wide",'bundle':"gregorian"},
	'months-format-abbr':["1","2","3","4","5","6","7","8","9","10","11","12"],
	'months-format-narrow@localeAlias284':{'target':"months-standAlone-narrow",'bundle':"gregorian"},
	'months-format-narrow':["1","2","3","4","5","6","7","8","9","10","11","12"],
	'months-format-wide':["1","2","3","4","5","6","7","8","9","10","11","12"],
	'months-standAlone-abbr@localeAlias285':{'target':"months-format-abbr",'bundle':"gregorian"},
	'months-standAlone-abbr@localeAlias286':{'target':"months-format-wide",'bundle':"gregorian"},
	'months-standAlone-abbr':["1","2","3","4","5","6","7","8","9","10","11","12"],
	'months-standAlone-narrow':["1","2","3","4","5","6","7","8","9","10","11","12"],
	'months-standAlone-wide@localeAlias287':{'target':"months-format-wide",'bundle':"gregorian"},
	'months-standAlone-wide':["1","2","3","4","5","6","7","8","9","10","11","12"],
	'days@localeAlias288':{'target':"days", 'bundle':"gregorian"},
	'days-format-abbr@localeAlias289':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-format-abbr':["1","2","3","4","5","6","7"],
	'days-format-narrow@localeAlias290':{'target':"days-standAlone-narrow",'bundle':"gregorian"},
	'days-format-narrow':["1","2","3","4","5","6","7"],
	'days-format-wide':["1","2","3","4","5","6","7"],
	'days-standAlone-abbr@localeAlias291':{'target':"days-format-abbr",'bundle':"gregorian"},
	'days-standAlone-abbr@localeAlias292':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-standAlone-abbr':["1","2","3","4","5","6","7"],
	'days-standAlone-narrow':["1","2","3","4","5","6","7"],
	'days-standAlone-wide@localeAlias293':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-standAlone-wide':["1","2","3","4","5","6","7"],
	'quarters@localeAlias294':{'target':"quarters", 'bundle':"gregorian"},
	'quarters-format-abbr@localeAlias295':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-format-abbr':["Q1","Q2","Q3","Q4"],
	'quarters-format-narrow@localeAlias296':{'target':"quarters-standAlone-narrow",'bundle':"gregorian"},
	'quarters-format-narrow':["1","2","3","4"],
	'quarters-format-wide':["Q1","Q2","Q3","Q4"],
	'quarters-standAlone-abbr@localeAlias297':{'target':"quarters-format-abbr",'bundle':"gregorian"},
	'quarters-standAlone-abbr@localeAlias298':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-standAlone-abbr':["Q1","Q2","Q3","Q4"],
	'quarters-standAlone-narrow':["1","2","3","4"],
	'quarters-standAlone-wide@localeAlias299':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-standAlone-wide':["Q1","Q2","Q3","Q4"],
	'dayPeriods@localeAlias300':{'target':"dayPeriods", 'bundle':"gregorian"},
	'dayPeriods-format-abbr@localeAlias301':{'target':"dayPeriods-format-wide",'bundle':"gregorian"},
	'dayPeriods-format-abbr-am':"AM",
	'dayPeriods-format-abbr-pm':"PM",
	'dayPeriods-format-narrow@localeAlias302':{'target':"dayPeriods-format-abbr",'bundle':"gregorian"},
	'dayPeriods-format-narrow@localeAlias303':{'target':"dayPeriods-format-wide",'bundle':"gregorian"},
	'dayPeriods-format-narrow-am':"AM",
	'dayPeriods-format-narrow-pm':"PM",
	'dayPeriods-format-wide-am':"AM",
	'dayPeriods-format-wide-pm':"PM",
	'dayPeriods-format-abbr@localeAlias304':{'target':"dayPeriods-format-wide",'bundle':"gregorian"},
	'dayPeriods-format-abbr-am':"AM",
	'dayPeriods-format-abbr-pm':"PM",
	'dayPeriods-format-narrow@localeAlias305':{'target':"dayPeriods-format-abbr",'bundle':"gregorian"},
	'dayPeriods-format-narrow@localeAlias306':{'target':"dayPeriods-format-wide",'bundle':"gregorian"},
	'dayPeriods-format-narrow-am':"AM",
	'dayPeriods-format-narrow-pm':"PM",
	'dayPeriods-format-wide-am':"AM",
	'dayPeriods-format-wide-pm':"PM",
	'eraNames@localeAlias307':{'target':"eraAbbr", 'bundle':"japanese"},
	'eraNames':["Taika","Hakuchi","Hakuhō","Shuchō","Taihō","Keiun","Wadō","Reiki","Yōrō","Jinki","Tempyō","Tempyō-kampō","Tempyō-shōhō","Tempyō-hōji","Temphō-jingo","Jingo-keiun","Hōki","Ten-ō","Enryaku","Daidō","Kōnin","Tenchō","Shōwa","Kajō","Ninju","Saiko","Tennan","Jōgan","Genkei","Ninna","Kampyō","Shōtai","Engi","Enchō","Shōhei","Tengyō","Tenryaku","Tentoku","Ōwa","Kōhō","Anna","Tenroku","Ten-en","Jōgen","Tengen","Eikan","Kanna","Ei-en","Eiso","Shōryaku","Chōtoku","Chōhō","Kankō","Chōwa","Kannin","Jian","Manju","Chōgen","Chōryaku","Chōkyū","Kantoku","Eishō","Tengi","Kōhei","Jiryaku","Enkyū","Shōho","Shōryaku","Eiho","Ōtoku","Kanji","Kaho","Eichō","Shōtoku","Kōwa","Chōji","Kashō","Tennin","Ten-ei","Eikyū","Gen-ei","Hoan","Tenji","Daiji","Tenshō","Chōshō","Hoen","Eiji","Kōji","Tenyō","Kyūan","Ninpei","Kyūju","Hogen","Heiji","Eiryaku","Ōho","Chōkan","Eiman","Nin-an","Kaō","Shōan","Angen","Jishō","Yōwa","Juei","Genryuku","Bunji","Kenkyū","Shōji","Kennin","Genkyū","Ken-ei","Shōgen","Kenryaku","Kenpō","Shōkyū","Jōō","Gennin","Karoku","Antei","Kanki","Jōei","Tempuku","Bunryaku","Katei","Ryakunin","En-ō","Ninji","Kangen","Hōji","Kenchō","Kōgen","Shōka","Shōgen","Bun-ō","Kōchō","Bun-ei","Kenji","Kōan","Shōō","Einin","Shōan","Kengen","Kagen","Tokuji","Enkei","Ōchō","Shōwa","Bunpō","Genō","Genkyō","Shōchū","Kareki","Gentoku","Genkō","Kemmu","Engen","Kōkoku","Shōhei","Kentoku","Bunchũ","Tenju","Kōryaku","Kōwa","Genchũ","Meitoku","Kakei","Kōō","Meitoku","Ōei","Shōchō","Eikyō","Kakitsu","Bun-an","Hōtoku","Kyōtoku","Kōshō","Chōroku","Kanshō","Bunshō","Ōnin","Bunmei","Chōkyō","Entoku","Meiō","Bunki","Eishō","Taiei","Kyōroku","Tenmon","Kōji","Eiroku","Genki","Tenshō","Bunroku","Keichō","Genwa","Kan-ei","Shōho","Keian","Shōō","Meiryaku","Manji","Kanbun","Enpō","Tenwa","Jōkyō","Genroku","Hōei","Shōtoku","Kyōhō","Genbun","Kanpō","Enkyō","Kan-en","Hōryaku","Meiwa","An-ei","Tenmei","Kansei","Kyōwa","Bunka","Bunsei","Tenpō","Kōka","Kaei","Ansei","Man-en","Bunkyū","Genji","Keiō","Meiji","Taishō","Shōwa","Heisei"],
	'eraAbbr':["Taika","Hakuchi","Hakuhō","Shuchō","Taihō","Keiun","Wadō","Reiki","Yōrō","Jinki","Tempyō","Tempyō-kampō","Tempyō-shōhō","Tempyō-hōji","Temphō-jingo","Jingo-keiun","Hōki","Ten-ō","Enryaku","Daidō","Kōnin","Tenchō","Shōwa","Kajō","Ninju","Saiko","Tennan","Jōgan","Genkei","Ninna","Kampyō","Shōtai","Engi","Enchō","Shōhei","Tengyō","Tenryaku","Tentoku","Ōwa","Kōhō","Anna","Tenroku","Ten-en","Jōgen","Tengen","Eikan","Kanna","Ei-en","Eiso","Shōryaku","Chōtoku","Chōhō","Kankō","Chōwa","Kannin","Jian","Manju","Chōgen","Chōryaku","Chōkyū","Kantoku","Eishō","Tengi","Kōhei","Jiryaku","Enkyū","Shōho","Shōryaku","Eiho","Ōtoku","Kanji","Kaho","Eichō","Shōtoku","Kōwa","Chōji","Kashō","Tennin","Ten-ei","Eikyū","Gen-ei","Hoan","Tenji","Daiji","Tenshō","Chōshō","Hoen","Eiji","Kōji","Tenyō","Kyūan","Ninpei","Kyūju","Hogen","Heiji","Eiryaku","Ōho","Chōkan","Eiman","Nin-an","Kaō","Shōan","Angen","Jishō","Yōwa","Juei","Genryuku","Bunji","Kenkyū","Shōji","Kennin","Genkyū","Ken-ei","Shōgen","Kenryaku","Kenpō","Shōkyū","Jōō","Gennin","Karoku","Antei","Kanki","Jōei","Tempuku","Bunryaku","Katei","Ryakunin","En-ō","Ninji","Kangen","Hōji","Kenchō","Kōgen","Shōka","Shōgen","Bun-ō","Kōchō","Bun-ei","Kenji","Kōan","Shōō","Einin","Shōan","Kengen","Kagen","Tokuji","Enkei","Ōchō","Shōwa","Bunpō","Genō","Genkyō","Shōchū","Kareki","Gentoku","Genkō","Kemmu","Engen","Kōkoku","Shōhei","Kentoku","Bunchũ","Tenju","Kōryaku","Kōwa","Genchũ","Meitoku","Kakei","Kōō","Meitoku","Ōei","Shōchō","Eikyō","Kakitsu","Bun-an","Hōtoku","Kyōtoku","Kōshō","Chōroku","Kanshō","Bunshō","Ōnin","Bunmei","Chōkyō","Entoku","Meiō","Bunki","Eishō","Taiei","Kyōroku","Tenmon","Kōji","Eiroku","Genki","Tenshō","Bunroku","Keichō","Genwa","Kan-ei","Shōho","Keian","Shōō","Meiryaku","Manji","Kanbun","Enpō","Tenwa","Jōkyō","Genroku","Hōei","Shōtoku","Kyōhō","Genbun","Kanpō","Enkyō","Kan-en","Hōryaku","Meiwa","An-ei","Tenmei","Kansei","Kyōwa","Bunka","Bunsei","Tenpō","Kōka","Kaei","Ansei","Man-en","Bunkyū","Genji","Keiō","Meiji","Taishō","Shōwa","Heisei"],
	'eraNarrow':["M","T","S","H"],
	'dateFormat-full': "EEEE, G y MMMM dd",
	'dateFormat-long': "G y MMMM d",
	'dateFormat-medium': "G y MMM d",
	'dateFormat-short': "G yy-MM-dd",
	'timeFormat@localeAlias308':{'target':"timeFormat", 'bundle':"gregorian"},
	'timeFormat-full': "HH:mm:ss zzzz",
	'timeFormat-long': "HH:mm:ss z",
	'timeFormat-medium': "HH:mm:ss",
	'timeFormat-short': "HH:mm",
	'dateTimeFormat-full': "{1} {0}" ,
	'dateTimeFormat-long': "{1} {0}" ,
	'dateTimeFormat-medium': "{1} {0}" ,
	'dateTimeFormat-short': "{1} {0}" ,
	'dateFormatItem-Ed':"E d",
	'dateFormatItem-h':"hh a",
	'dateFormatItem-H':"HH",
	'dateFormatItem-hm':"hh:mm a",
	'dateFormatItem-Hm':"HH:mm",
	'dateFormatItem-hms':"hh:mm:ss a",
	'dateFormatItem-Hms':"HH:mm:ss",
	'dateFormatItem-Md':"M-d",
	'dateFormatItem-MMMEd':"E MMM d",
	'dateFormatItem-MMMMd':"MMMM d",
	'dateFormatItem-ms':"mm:ss",
	'dateFormatItem-yyyy':"yy GGG",
	'dateFormatItem-yyyyM':"GGGGG yy-MM",
	'dateFormatItem-yyyyMd':"GGGGG yy-MM-dd",
	'dateFormatItem-yyyyMMM':"GGGGG yy MMM",
	'dateFormatItem-yyyyMMMd':"GGGGG yy MMM d",
	'dateFormatItem-yyyyQ':"GGGGG yy Q",
	'dateTimeFormats-appendItem-Day':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Day-Of-Week':"{0} {1}",
	'dateTimeFormats-appendItem-Era':"{0} {1}",
	'dateTimeFormats-appendItem-Hour':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Minute':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Month':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Quarter':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Second':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Timezone':"{0} {1}",
	'dateTimeFormats-appendItem-Week':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Year':"{0} {1}"
})
                        