// generated from ldml/main/*.xml, xpath: ldml/calendars/calendar-roc
({
	'months@localeAlias338':{'target':"months", 'bundle':"gregorian"},
	'months-format-abbr@localeAlias339':{'target':"months-format-wide",'bundle':"gregorian"},
	'months-format-abbr':["1","2","3","4","5","6","7","8","9","10","11","12"],
	'months-format-narrow@localeAlias340':{'target':"months-standAlone-narrow",'bundle':"gregorian"},
	'months-format-narrow':["1","2","3","4","5","6","7","8","9","10","11","12"],
	'months-format-wide':["1","2","3","4","5","6","7","8","9","10","11","12"],
	'months-standAlone-abbr@localeAlias341':{'target':"months-format-abbr",'bundle':"gregorian"},
	'months-standAlone-abbr@localeAlias342':{'target':"months-format-wide",'bundle':"gregorian"},
	'months-standAlone-abbr':["1","2","3","4","5","6","7","8","9","10","11","12"],
	'months-standAlone-narrow':["1","2","3","4","5","6","7","8","9","10","11","12"],
	'months-standAlone-wide@localeAlias343':{'target':"months-format-wide",'bundle':"gregorian"},
	'months-standAlone-wide':["1","2","3","4","5","6","7","8","9","10","11","12"],
	'days@localeAlias344':{'target':"days", 'bundle':"gregorian"},
	'days-format-abbr@localeAlias345':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-format-abbr':["1","2","3","4","5","6","7"],
	'days-format-narrow@localeAlias346':{'target':"days-standAlone-narrow",'bundle':"gregorian"},
	'days-format-narrow':["1","2","3","4","5","6","7"],
	'days-format-wide':["1","2","3","4","5","6","7"],
	'days-standAlone-abbr@localeAlias347':{'target':"days-format-abbr",'bundle':"gregorian"},
	'days-standAlone-abbr@localeAlias348':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-standAlone-abbr':["1","2","3","4","5","6","7"],
	'days-standAlone-narrow':["1","2","3","4","5","6","7"],
	'days-standAlone-wide@localeAlias349':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-standAlone-wide':["1","2","3","4","5","6","7"],
	'quarters@localeAlias350':{'target':"quarters", 'bundle':"gregorian"},
	'quarters-format-abbr@localeAlias351':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-format-abbr':["Q1","Q2","Q3","Q4"],
	'quarters-format-narrow@localeAlias352':{'target':"quarters-standAlone-narrow",'bundle':"gregorian"},
	'quarters-format-narrow':["1","2","3","4"],
	'quarters-format-wide':["Q1","Q2","Q3","Q4"],
	'quarters-standAlone-abbr@localeAlias353':{'target':"quarters-format-abbr",'bundle':"gregorian"},
	'quarters-standAlone-abbr@localeAlias354':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-standAlone-abbr':["Q1","Q2","Q3","Q4"],
	'quarters-standAlone-narrow':["1","2","3","4"],
	'quarters-standAlone-wide@localeAlias355':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-standAlone-wide':["Q1","Q2","Q3","Q4"],
	'dayPeriods@localeAlias356':{'target':"dayPeriods", 'bundle':"gregorian"},
	'dayPeriods-format-abbr@localeAlias357':{'target':"dayPeriods-format-wide",'bundle':"gregorian"},
	'dayPeriods-format-abbr-am':"AM",
	'dayPeriods-format-abbr-pm':"PM",
	'dayPeriods-format-narrow@localeAlias358':{'target':"dayPeriods-format-abbr",'bundle':"gregorian"},
	'dayPeriods-format-narrow@localeAlias359':{'target':"dayPeriods-format-wide",'bundle':"gregorian"},
	'dayPeriods-format-narrow-am':"AM",
	'dayPeriods-format-narrow-pm':"PM",
	'dayPeriods-format-wide-am':"AM",
	'dayPeriods-format-wide-pm':"PM",
	'dayPeriods-format-abbr@localeAlias360':{'target':"dayPeriods-format-wide",'bundle':"gregorian"},
	'dayPeriods-format-abbr-am':"AM",
	'dayPeriods-format-abbr-pm':"PM",
	'dayPeriods-format-narrow@localeAlias361':{'target':"dayPeriods-format-abbr",'bundle':"gregorian"},
	'dayPeriods-format-narrow@localeAlias362':{'target':"dayPeriods-format-wide",'bundle':"gregorian"},
	'dayPeriods-format-narrow-am':"AM",
	'dayPeriods-format-narrow-pm':"PM",
	'dayPeriods-format-wide-am':"AM",
	'dayPeriods-format-wide-pm':"PM",
	'eraNames@localeAlias363':{'target':"eraAbbr", 'bundle':"roc"},
	'eraNames':["Before R.O.C.","R.O.C."],
	'eraAbbr':["Before R.O.C.","R.O.C."],
	'eraNarrow@localeAlias364':{'target':"eraAbbr", 'bundle':"roc"},
	'eraNarrow':["Before R.O.C.","R.O.C."],
	'dateFormat-full': "EEEE, MMMM d, G y",
	'dateFormat-long': "MMMM d, G y",
	'dateFormat-medium': "MMM d, G y",
	'dateFormat-short': "G y/M/d",
	'timeFormat@localeAlias365':{'target':"timeFormat", 'bundle':"gregorian"},
	'timeFormat-full': "HH:mm:ss zzzz",
	'timeFormat-long': "HH:mm:ss z",
	'timeFormat-medium': "HH:mm:ss",
	'timeFormat-short': "HH:mm",
	'dateTimeFormat@localeAlias366':{'target':"dateTimeFormat", 'bundle':"gregorian"},
	'dateTimeFormat': "{1} {0}" ,
	'dateTimeFormat@localeAlias367':{'target':"dateTimeFormat", 'bundle':"gregorian"},
	'dateTimeFormat': "{1} {0}" ,
	'dateTimeFormat@localeAlias368':{'target':"dateTimeFormat", 'bundle':"gregorian"},
	'dateTimeFormat': "{1} {0}" ,
	'dateTimeFormat@localeAlias369':{'target':"dateTimeFormat", 'bundle':"gregorian"},
	'dateTimeFormat': "{1} {0}" ,
	'dateFormatItem-h':"h a",
	'dateFormatItem-H':"HH",
	'dateFormatItem-hm':"h:mm a",
	'dateFormatItem-Hm':"HH:mm",
	'dateFormatItem-hms':"h:mm:ss a",
	'dateFormatItem-Hms':"HH:mm:ss",
	'dateFormatItem-Md':"M/d",
	'dateFormatItem-MEd':"E, M/d",
	'dateFormatItem-MMMd':"MMM d",
	'dateFormatItem-MMMEd':"E, MMM d",
	'dateFormatItem-ms':"mm:ss",
	'dateFormatItem-yyyy':"G y",
	'dateFormatItem-yyyyM':"G y/M",
	'dateFormatItem-yyyyMEd':"EEE, G y/M/d",
	'dateFormatItem-yyyyMMM':"MMM, G y",
	'dateFormatItem-yyyyMMMEd':"EEE, MMM d, G y",
	'dateFormatItem-yyyyQ':"Q G y",
	'dateFormatItem-yyyyQQQ':"QQQ G y",
	'dateTimeFormats-appendItem-Day':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Day-Of-Week':"{0} {1}",
	'dateTimeFormats-appendItem-Era':"{0} {1}",
	'dateTimeFormats-appendItem-Hour':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Minute':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Month':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Quarter':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Second':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Timezone':"{0} {1}",
	'dateTimeFormats-appendItem-Week':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Year':"{0} {1}"
})
                        