({
	"dateFormatItem-yM": "M/y", 
	"field-dayperiod": "AM/PM", 
	"dayPeriods-format-wide-pm": "nm.", 
	"dateFormatItem-yQ": "Q y", 
	"field-minute": "Minuut", 
	"eraNames": [
		"voor Christus", 
		"na Christus"
	], 
	"dateFormatItem-MMMEd": "E, MMM d", 
	"field-day-relative+-1": "gister", 
	"dateFormatItem-yQQQ": "QQQ y", 
	"field-day-relative+-2": "eergister", 
	"field-weekday": "Weeksdag", 
	"field-day-relative+-3": "eereergister", 
	"days-standAlone-wide": [
		"Sondag", 
		"Maandag", 
		"Dinsdag", 
		"Woensdag", 
		"Donderdag", 
		"Vrydag", 
		"Saterdag"
	], 
	"dateFormatItem-MMM": "LLL", 
	"months-standAlone-narrow": [
		"J", 
		"F", 
		"M", 
		"A", 
		"M", 
		"J", 
		"J", 
		"A", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"dayPeriods-format-wide-am": "vm.", 
	"field-hour": "Uur", 
	"quarters-standAlone-abbr": [
		"K1", 
		"K2", 
		"K3", 
		"K4"
	], 
	"dateFormatItem-y": "y", 
	"timeFormat-full": "h:mm:ss a zzzz", 
	"months-standAlone-abbr": [
		"Jan", 
		"Feb", 
		"Mar", 
		"Apr", 
		"Mei", 
		"Jun", 
		"Jul", 
		"Aug", 
		"Sep", 
		"Okt", 
		"Nov", 
		"Des"
	], 
	"dateFormatItem-yMMM": "MMM y", 
	"field-day-relative+0": "vandag", 
	"days-standAlone-narrow": [
		"S", 
		"M", 
		"D", 
		"W", 
		"D", 
		"V", 
		"S"
	], 
	"field-day-relative+1": "môre", 
	"eraAbbr": [
		"v.C.", 
		"n.C."
	], 
	"field-day-relative+2": "overmôre", 
	"field-day-relative+3": "overovermôre", 
	"dateFormat-long": "dd MMMM y", 
	"timeFormat-medium": "h:mm:ss a", 
	"field-zone": "Tydsone", 
	"dateFormatItem-Hm": "HH:mm", 
	"dateFormat-medium": "dd MMM y", 
	"dateFormatItem-Hms": "HH:mm:ss", 
	"quarters-standAlone-wide": [
		"1ste kwartaal", 
		"2de kwartaal", 
		"3de kwartaal", 
		"4de kwartaal"
	], 
	"dateFormatItem-yMMMM": "MMMM y", 
	"dateFormatItem-ms": "mm:ss", 
	"field-year": "Jaar", 
	"field-week": "Week", 
	"months-standAlone-wide": [
		"Januarie", 
		"Februarie", 
		"Maart", 
		"April", 
		"Mei", 
		"Junie", 
		"Julie", 
		"Augustus", 
		"September", 
		"Oktober", 
		"November", 
		"Desember"
	], 
	"dateFormatItem-MMMMEd": "E, MMMM d", 
	"dateFormatItem-MMMd": "MMM d", 
	"timeFormat-long": "h:mm:ss a z", 
	"months-format-abbr": [
		"Jan", 
		"Feb", 
		"Mar", 
		"Apr", 
		"Mei", 
		"Jun", 
		"Jul", 
		"Aug", 
		"Sep", 
		"Okt", 
		"Nov", 
		"Des"
	], 
	"timeFormat-short": "h:mm a", 
	"field-month": "Maand", 
	"dateFormatItem-MMMMd": "MMMM d", 
	"quarters-format-abbr": [
		"K1", 
		"K2", 
		"K3", 
		"K4"
	], 
	"days-format-abbr": [
		"So", 
		"Ma", 
		"Di", 
		"Wo", 
		"Do", 
		"Vr", 
		"Sa"
	], 
	"dateFormatItem-M": "L", 
	"days-format-narrow": [
		"S", 
		"M", 
		"D", 
		"W", 
		"D", 
		"V", 
		"S"
	], 
	"field-second": "Sekonde", 
	"field-day": "Dag", 
	"dateFormatItem-MEd": "E, M/d", 
	"months-format-narrow": [
		"J", 
		"F", 
		"M", 
		"A", 
		"M", 
		"J", 
		"J", 
		"A", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"dateFormatItem-hm": "h:mm a", 
	"days-standAlone-abbr": [
		"So", 
		"Ma", 
		"Di", 
		"Wo", 
		"Do", 
		"Vr", 
		"Sa"
	], 
	"dateFormat-short": "yyyy-MM-dd", 
	"dateFormatItem-yMMMEd": "EEE, MMM d, y", 
	"dateFormat-full": "EEEE dd MMMM y", 
	"dateFormatItem-Md": "M/d", 
	"dateFormatItem-yMEd": "EEE, y-M-d", 
	"months-format-wide": [
		"Januarie", 
		"Februarie", 
		"Maart", 
		"April", 
		"Mei", 
		"Junie", 
		"Julie", 
		"Augustus", 
		"September", 
		"Oktober", 
		"November", 
		"Desember"
	], 
	"dateFormatItem-d": "d", 
	"quarters-format-wide": [
		"1ste kwartaal", 
		"2de kwartaal", 
		"3de kwartaal", 
		"4de kwartaal"
	], 
	"days-format-wide": [
		"Sondag", 
		"Maandag", 
		"Dinsdag", 
		"Woensdag", 
		"Donderdag", 
		"Vrydag", 
		"Saterdag"
	], 
	"eraNarrow": [
		"v.C.", 
		"n.C."
	]
})