({
	"dateFormatItem-yM": "M/y", 
	"field-dayperiod": "Mambia gose Morogoba", 
	"dayPeriods-format-wide-pm": "Mambia/Mog", 
	"dateFormatItem-yQ": "Q y", 
	"field-minute": "Edakika", 
	"eraNames": [
		"Yeso ataiborwa", 
		"Yeso kaiboirwe"
	], 
	"dateFormatItem-MMMEd": "E, MMM d", 
	"field-day-relative+-1": "Igoro", 
	"dateFormatItem-yQQQ": "QQQ y", 
	"field-weekday": "Rituko r'ewiki", 
	"days-standAlone-wide": [
		"Chumapiri", 
		"Chumatato", 
		"Chumaine", 
		"Chumatano", 
		"Aramisi", 
		"Ichuma", 
		"Esabato"
	], 
	"dateFormatItem-MMM": "LLL", 
	"months-standAlone-narrow": [
		"C", 
		"F", 
		"M", 
		"A", 
		"M", 
		"J", 
		"C", 
		"A", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"dayPeriods-format-wide-am": "Ma/Mo", 
	"field-era": "Ebiro", 
	"field-hour": "Ensa", 
	"quarters-standAlone-abbr": [
		"E1", 
		"E2", 
		"E3", 
		"E4"
	], 
	"dateFormatItem-y": "y", 
	"timeFormat-full": "h:mm:ss a zzzz", 
	"months-standAlone-abbr": [
		"Can", 
		"Feb", 
		"Mac", 
		"Apr", 
		"Mei", 
		"Jun", 
		"Cul", 
		"Agt", 
		"Sep", 
		"Okt", 
		"Nob", 
		"Dis"
	], 
	"dateFormatItem-yMMM": "MMM y", 
	"field-day-relative+0": "Rero", 
	"days-standAlone-narrow": [
		"C", 
		"C", 
		"C", 
		"C", 
		"A", 
		"I", 
		"E"
	], 
	"field-day-relative+1": "Mambia", 
	"eraAbbr": [
		"YA", 
		"YK"
	], 
	"dateFormat-long": "d MMMM y", 
	"timeFormat-medium": "h:mm:ss a", 
	"field-zone": "Chinse 'chimo", 
	"dateFormatItem-Hm": "HH:mm", 
	"dateFormat-medium": "d MMM y", 
	"dateFormatItem-Hms": "HH:mm:ss", 
	"quarters-standAlone-wide": [
		"Erobo entang'ani", 
		"Erobo yakabere", 
		"Erobo yagatato", 
		"Erobo yakane"
	], 
	"dateFormatItem-yMMMM": "MMMM y", 
	"dateFormatItem-ms": "mm:ss", 
	"field-year": "Omwaka", 
	"field-week": "Omokubio", 
	"months-standAlone-wide": [
		"Chanuari", 
		"Feburari", 
		"Machi", 
		"Apiriri", 
		"Mei", 
		"Juni", 
		"Chulai", 
		"Agosti", 
		"Septemba", 
		"Okitoba", 
		"Nobemba", 
		"Disemba"
	], 
	"dateFormatItem-MMMMEd": "E, MMMM d", 
	"dateFormatItem-MMMd": "MMM d", 
	"timeFormat-long": "h:mm:ss a z", 
	"months-format-abbr": [
		"Can", 
		"Feb", 
		"Mac", 
		"Apr", 
		"Mei", 
		"Jun", 
		"Cul", 
		"Agt", 
		"Sep", 
		"Okt", 
		"Nob", 
		"Dis"
	], 
	"timeFormat-short": "h:mm a", 
	"field-month": "Omotienyi", 
	"dateFormatItem-MMMMd": "MMMM d", 
	"quarters-format-abbr": [
		"E1", 
		"E2", 
		"E3", 
		"E4"
	], 
	"days-format-abbr": [
		"Cpr", 
		"Ctt", 
		"Cmn", 
		"Cmt", 
		"Ars", 
		"Icm", 
		"Est"
	], 
	"dateFormatItem-M": "L", 
	"days-format-narrow": [
		"C", 
		"C", 
		"C", 
		"C", 
		"A", 
		"I", 
		"E"
	], 
	"field-second": "Esekendi", 
	"field-day": "Rituko", 
	"dateFormatItem-MEd": "E, M/d", 
	"months-format-narrow": [
		"C", 
		"F", 
		"M", 
		"A", 
		"M", 
		"J", 
		"C", 
		"A", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"dateFormatItem-hm": "h:mm a", 
	"days-standAlone-abbr": [
		"Cpr", 
		"Ctt", 
		"Cmn", 
		"Cmt", 
		"Ars", 
		"Icm", 
		"Est"
	], 
	"dateFormat-short": "dd/MM/yyyy", 
	"dateFormatItem-yMMMEd": "EEE, MMM d, y", 
	"dateFormat-full": "EEEE, d MMMM y", 
	"dateFormatItem-Md": "M/d", 
	"dateFormatItem-yMEd": "EEE, M/d/y", 
	"months-format-wide": [
		"Chanuari", 
		"Feburari", 
		"Machi", 
		"Apiriri", 
		"Mei", 
		"Juni", 
		"Chulai", 
		"Agosti", 
		"Septemba", 
		"Okitoba", 
		"Nobemba", 
		"Disemba"
	], 
	"dateFormatItem-d": "d", 
	"quarters-format-wide": [
		"Erobo entang'ani", 
		"Erobo yakabere", 
		"Erobo yagatato", 
		"Erobo yakane"
	], 
	"days-format-wide": [
		"Chumapiri", 
		"Chumatato", 
		"Chumaine", 
		"Chumatano", 
		"Aramisi", 
		"Ichuma", 
		"Esabato"
	], 
	"eraNarrow": [
		"YA", 
		"YK"
	]
})