({
	"field-dayperiod": "dienos metas", 
	"dayPeriods-format-wide-pm": "popiet", 
	"field-minute": "minutė", 
	"eraNames": [
		"prieš Kristų", 
		"po Kristaus"
	], 
	"field-day-relative+-1": "vakar", 
	"dateFormatItem-hms": "hh:mm:ss a", 
	"dateFormatItem-MMdd": "MM.dd", 
	"field-day-relative+-2": "užvakar", 
	"field-weekday": "savaitės diena", 
	"field-day-relative+-3": "už užvakar", 
	"days-standAlone-wide": [
		"sekmadienis", 
		"pirmadienis", 
		"antradienis", 
		"trečiadienis", 
		"ketvirtadienis", 
		"penktadienis", 
		"šeštadienis"
	], 
	"months-standAlone-narrow": [
		"S", 
		"V", 
		"K", 
		"B", 
		"G", 
		"B", 
		"L", 
		"R", 
		"R", 
		"S", 
		"L", 
		"G"
	], 
	"dayPeriods-format-wide-am": "priešpiet", 
	"field-era": "era", 
	"field-hour": "valanda", 
	"quarters-standAlone-abbr": [
		"1K", 
		"2K", 
		"3K", 
		"4K"
	], 
	"dateFormatItem-MMMdd": "MMM-dd", 
	"timeFormat-full": "HH:mm:ss zzzz", 
	"months-standAlone-abbr": [
		"Saus.", 
		"Vas.", 
		"kov", 
		"Bal.", 
		"Geg.", 
		"Bir.", 
		"Liep.", 
		"Rugpj.", 
		"Rugs.", 
		"Spal.", 
		"Lapkr.", 
		"Gruod."
	], 
	"field-day-relative+0": "šiandien", 
	"days-standAlone-narrow": [
		"S", 
		"P", 
		"A", 
		"T", 
		"K", 
		"P", 
		"Š"
	], 
	"field-day-relative+1": "rytoj", 
	"eraAbbr": [
		"pr. Kr.", 
		"po Kr."
	], 
	"field-day-relative+2": "poryt", 
	"field-day-relative+3": "užporyt", 
	"dateFormatItem-yyyyMM": "yyyy.MM", 
	"dateFormat-long": "y 'm'. MMMM d 'd'.", 
	"timeFormat-medium": "HH:mm:ss", 
	"field-zone": "juosta", 
	"dateFormatItem-Hm": "HH:mm", 
	"dateFormat-medium": "yyyy.MM.dd", 
	"dateFormatItem-Hms": "HH:mm:ss", 
	"quarters-standAlone-wide": [
		"pirmas ketvirtis", 
		"antras ketvirtis", 
		"trečias ketvirtis", 
		"ketvirtas ketvirtis"
	], 
	"field-year": "metai", 
	"months-standAlone-wide": [
		"Sausis", 
		"Vasaris", 
		"Kovas", 
		"Balandis", 
		"Gegužė", 
		"Birželis", 
		"Liepa", 
		"Rugpjūtis", 
		"Rugsėjis", 
		"Spalis", 
		"Lapkritis", 
		"Gruodis"
	], 
	"field-week": "savaitė", 
	"dateFormatItem-yyQ": "Q yy", 
	"timeFormat-long": "HH:mm:ss z", 
	"months-format-abbr": [
		"Sau", 
		"Vas", 
		"Kov", 
		"Bal", 
		"Geg", 
		"Bir", 
		"Lie", 
		"Rgp", 
		"Rgs", 
		"Spl", 
		"Lap", 
		"Grd"
	], 
	"timeFormat-short": "HH:mm", 
	"field-month": "mėnuo", 
	"quarters-format-abbr": [
		"K1", 
		"K2", 
		"K3", 
		"K4"
	], 
	"days-format-abbr": [
		"Sk", 
		"Pr", 
		"An", 
		"Tr", 
		"Kt", 
		"Pn", 
		"Št"
	], 
	"days-format-narrow": [
		"S", 
		"P", 
		"A", 
		"T", 
		"K", 
		"P", 
		"Š"
	], 
	"field-second": "sekundė", 
	"field-day": "diena", 
	"months-format-narrow": [
		"S", 
		"V", 
		"K", 
		"B", 
		"G", 
		"B", 
		"L", 
		"R", 
		"R", 
		"S", 
		"L", 
		"G"
	], 
	"dateFormatItem-hm": "hh:mm a", 
	"days-standAlone-abbr": [
		"Sk", 
		"Pi", 
		"A", 
		"T", 
		"K", 
		"Pe", 
		"Š"
	], 
	"dayPeriods-format-abbr-pm": "pop.", 
	"dateFormat-short": "yyyy-MM-dd", 
	"dateFormat-full": "y 'm'. MMMM d 'd'.,EEEE", 
	"months-format-wide": [
		"sausis", 
		"vasaris", 
		"kovas", 
		"balandis", 
		"gegužė", 
		"birželis", 
		"liepa", 
		"rugpjūtis", 
		"rugsėjis", 
		"spalis", 
		"lapkritis", 
		"gruodis"
	], 
	"dayPeriods-format-abbr-am": "pr.p.", 
	"quarters-format-wide": [
		"pirmas ketvirtis", 
		"antras ketvirtis", 
		"trečias ketvirtis", 
		"ketvirtas ketvirtis"
	], 
	"days-format-wide": [
		"sekmadienis", 
		"pirmadienis", 
		"antradienis", 
		"trečiadienis", 
		"ketvirtadienis", 
		"penktadienis", 
		"šeštadienis"
	], 
	"eraNarrow": [
		"pr. Kr.", 
		"po Kr."
	], 
	"dateFormatItem-h": "hh a"
})