// generated from ldml/main/*.xml, xpath: ldml/calendars/calendar-coptic
({
	'months-format-abbr@localeAlias56':{'target':"months-format-wide",'bundle':"coptic"},
	'months-format-abbr':["Tout","Baba","Hator","Kiahk","Toba","Amshir","Baramhat","Baramouda","Bashans","Paona","Epep","Mesra","Nasie"],
	'months-format-narrow@localeAlias57':{'target':"months-standAlone-narrow",'bundle':"coptic"},
	'months-format-narrow':["1","2","3","4","5","6","7","8","9","10","11","12","13"],
	'months-format-wide':["Tout","Baba","Hator","Kiahk","Toba","Amshir","Baramhat","Baramouda","Bashans","Paona","Epep","Mesra","Nasie"],
	'months-standAlone-abbr@localeAlias58':{'target':"months-format-abbr",'bundle':"coptic"},
	'months-standAlone-abbr@localeAlias59':{'target':"months-format-wide",'bundle':"coptic"},
	'months-standAlone-abbr':["Tout","Baba","Hator","Kiahk","Toba","Amshir","Baramhat","Baramouda","Bashans","Paona","Epep","Mesra","Nasie"],
	'months-standAlone-narrow':["1","2","3","4","5","6","7","8","9","10","11","12","13"],
	'months-standAlone-wide@localeAlias60':{'target':"months-format-wide",'bundle':"coptic"},
	'months-standAlone-wide':["Tout","Baba","Hator","Kiahk","Toba","Amshir","Baramhat","Baramouda","Bashans","Paona","Epep","Mesra","Nasie"],
	'days@localeAlias61':{'target':"days", 'bundle':"gregorian"},
	'days-format-abbr@localeAlias62':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-format-abbr':["1","2","3","4","5","6","7"],
	'days-format-narrow@localeAlias63':{'target':"days-standAlone-narrow",'bundle':"gregorian"},
	'days-format-narrow':["1","2","3","4","5","6","7"],
	'days-format-wide':["1","2","3","4","5","6","7"],
	'days-standAlone-abbr@localeAlias64':{'target':"days-format-abbr",'bundle':"gregorian"},
	'days-standAlone-abbr@localeAlias65':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-standAlone-abbr':["1","2","3","4","5","6","7"],
	'days-standAlone-narrow':["1","2","3","4","5","6","7"],
	'days-standAlone-wide@localeAlias66':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-standAlone-wide':["1","2","3","4","5","6","7"],
	'quarters@localeAlias67':{'target':"quarters", 'bundle':"gregorian"},
	'quarters-format-abbr@localeAlias68':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-format-abbr':["Q1","Q2","Q3","Q4"],
	'quarters-format-narrow@localeAlias69':{'target':"quarters-standAlone-narrow",'bundle':"gregorian"},
	'quarters-format-narrow':["1","2","3","4"],
	'quarters-format-wide':["Q1","Q2","Q3","Q4"],
	'quarters-standAlone-abbr@localeAlias70':{'target':"quarters-format-abbr",'bundle':"gregorian"},
	'quarters-standAlone-abbr@localeAlias71':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-standAlone-abbr':["Q1","Q2","Q3","Q4"],
	'quarters-standAlone-narrow':["1","2","3","4"],
	'quarters-standAlone-wide@localeAlias72':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-standAlone-wide':["Q1","Q2","Q3","Q4"],
	'dayPeriods@localeAlias73':{'target':"dayPeriods", 'bundle':"gregorian"},
	'dayPeriods-format-abbr@localeAlias74':{'target':"dayPeriods-format-wide",'bundle':"gregorian"},
	'dayPeriods-format-abbr-am':"AM",
	'dayPeriods-format-abbr-pm':"PM",
	'dayPeriods-format-narrow@localeAlias75':{'target':"dayPeriods-format-abbr",'bundle':"gregorian"},
	'dayPeriods-format-narrow@localeAlias76':{'target':"dayPeriods-format-wide",'bundle':"gregorian"},
	'dayPeriods-format-narrow-am':"AM",
	'dayPeriods-format-narrow-pm':"PM",
	'dayPeriods-format-wide-am':"AM",
	'dayPeriods-format-wide-pm':"PM",
	'dayPeriods-format-abbr@localeAlias77':{'target':"dayPeriods-format-wide",'bundle':"gregorian"},
	'dayPeriods-format-abbr-am':"AM",
	'dayPeriods-format-abbr-pm':"PM",
	'dayPeriods-format-narrow@localeAlias78':{'target':"dayPeriods-format-abbr",'bundle':"gregorian"},
	'dayPeriods-format-narrow@localeAlias79':{'target':"dayPeriods-format-wide",'bundle':"gregorian"},
	'dayPeriods-format-narrow-am':"AM",
	'dayPeriods-format-narrow-pm':"PM",
	'dayPeriods-format-wide-am':"AM",
	'dayPeriods-format-wide-pm':"PM",
	'eraNames@localeAlias80':{'target':"eraAbbr", 'bundle':"coptic"},
	'eraNames':["ERA0","ERA1"],
	'eraAbbr':["ERA0","ERA1"],
	'eraNarrow@localeAlias81':{'target':"eraAbbr", 'bundle':"coptic"},
	'eraNarrow':["ERA0","ERA1"],
	'dateFormat@localeAlias82':{'target':"dateFormat", 'bundle':"gregorian"},
	'dateFormat-full': "EEEE, y MMMM dd",
	'dateFormat-long': "y MMMM d",
	'dateFormat-medium': "y MMM d",
	'dateFormat-short': "yyyy-MM-dd",
	'timeFormat@localeAlias83':{'target':"timeFormat", 'bundle':"gregorian"},
	'timeFormat-full': "HH:mm:ss zzzz",
	'timeFormat-long': "HH:mm:ss z",
	'timeFormat-medium': "HH:mm:ss",
	'timeFormat-short': "HH:mm",
	'dateTime@localeAlias84':{'target':"dateTime", 'bundle':"gregorian"},
	'dateTimeFormat-full': "{1} {0}" ,
	'dateTimeFormat-long': "{1} {0}" ,
	'dateTimeFormat-medium': "{1} {0}" ,
	'dateTimeFormat-short': "{1} {0}" ,
	'dateFormatItem-d':"d",
	'dateFormatItem-EEEd':"d EEE",
	'dateFormatItem-h':"h a",
	'dateFormatItem-H':"HH",
	'dateFormatItem-hm':"h:mm a",
	'dateFormatItem-Hm':"HH:mm",
	'dateFormatItem-hms':"h:mm:ss a",
	'dateFormatItem-Hms':"HH:mm:ss",
	'dateFormatItem-M':"L",
	'dateFormatItem-Md':"M-d",
	'dateFormatItem-MEd':"E, M-d",
	'dateFormatItem-MMM':"LLL",
	'dateFormatItem-MMMd':"MMM d",
	'dateFormatItem-MMMEd':"E MMM d",
	'dateFormatItem-ms':"mm:ss",
	'dateFormatItem-y':"y",
	'dateFormatItem-yM':"y-M",
	'dateFormatItem-yMEd':"EEE, y-M-d",
	'dateFormatItem-yMMM':"y MMM",
	'dateFormatItem-yMMMEd':"EEE, y MMM d",
	'dateFormatItem-yQ':"y Q",
	'dateFormatItem-yQQQ':"y QQQ",
	'dateTimeFormats-appendItem-Day':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Day-Of-Week':"{0} {1}",
	'dateTimeFormats-appendItem-Era':"{0} {1}",
	'dateTimeFormats-appendItem-Hour':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Minute':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Month':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Quarter':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Second':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Timezone':"{0} {1}",
	'dateTimeFormats-appendItem-Week':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Year':"{0} {1}"
})
                        