({
	"dateFormatItem-yM": "M/y", 
	"field-dayperiod": "Zdat azal/Deffir azal", 
	"dayPeriods-format-wide-pm": "Ḍeffir aza", 
	"dateFormatItem-yQ": "Q y", 
	"field-minute": "Tusdat", 
	"eraNames": [
		"Zdat Ɛisa (TAƔ)", 
		"Ḍeffir Ɛisa (TAƔ)"
	], 
	"dateFormatItem-MMMEd": "E, MMM d", 
	"field-day-relative+-1": "Assenaṭ", 
	"dateFormatItem-yQQQ": "QQQ y", 
	"field-weekday": "Ass n Imalass", 
	"days-standAlone-wide": [
		"Asamas", 
		"Aynas", 
		"Asinas", 
		"Akras", 
		"Akwas", 
		"Asimwas", 
		"Asiḍyas"
	], 
	"dateFormatItem-MMM": "LLL", 
	"months-standAlone-narrow": [
		"Y", 
		"Y", 
		"M", 
		"I", 
		"M", 
		"Y", 
		"Y", 
		"Ɣ", 
		"C", 
		"K", 
		"N", 
		"D"
	], 
	"dayPeriods-format-wide-am": "Zdat azal", 
	"field-era": "Tallit", 
	"field-hour": "Tasragt", 
	"quarters-standAlone-abbr": [
		"IA1", 
		"IA2", 
		"IA3", 
		"IA4"
	], 
	"dateFormatItem-y": "y", 
	"timeFormat-full": "h:mm:ss a zzzz", 
	"months-standAlone-abbr": [
		"Yen", 
		"Yeb", 
		"Mar", 
		"Ibr", 
		"May", 
		"Yun", 
		"Yul", 
		"Ɣuc", 
		"Cut", 
		"Kṭu", 
		"Nwa", 
		"Duj"
	], 
	"dateFormatItem-yMMM": "MMM y", 
	"field-day-relative+0": "Assa", 
	"days-standAlone-narrow": [
		"A", 
		"A", 
		"A", 
		"A", 
		"A", 
		"A", 
		"A"
	], 
	"field-day-relative+1": "Asekka", 
	"eraAbbr": [
		"ZƐ", 
		"ḌƐ"
	], 
	"dateFormat-long": "d MMMM y", 
	"timeFormat-medium": "h:mm:ss a", 
	"field-zone": "Aseglem asergan", 
	"dateFormatItem-Hm": "HH:mm", 
	"dateFormat-medium": "d MMM y", 
	"dateFormatItem-Hms": "HH:mm:ss", 
	"quarters-standAlone-wide": [
		"Imir adamsan 1", 
		"Imir adamsan 2", 
		"Imir adamsan 3", 
		"Imir adamsan 4"
	], 
	"dateFormatItem-yMMMM": "MMMM y", 
	"dateFormatItem-ms": "mm:ss", 
	"field-year": "Asseggas", 
	"field-week": "Imalass", 
	"months-standAlone-wide": [
		"Yennayer", 
		"Yebrayer", 
		"Mars", 
		"Ibrir", 
		"Mayyu", 
		"Yunyu", 
		"Yulyuz", 
		"Ɣuct", 
		"Cutanbir", 
		"Kṭuber", 
		"Nwanbir", 
		"Dujanbir"
	], 
	"dateFormatItem-MMMMEd": "E, MMMM d", 
	"dateFormatItem-MMMd": "MMM d", 
	"timeFormat-long": "h:mm:ss a z", 
	"months-format-abbr": [
		"Yen", 
		"Yeb", 
		"Mar", 
		"Ibr", 
		"May", 
		"Yun", 
		"Yul", 
		"Ɣuc", 
		"Cut", 
		"Kṭu", 
		"Nwa", 
		"Duj"
	], 
	"timeFormat-short": "h:mm a", 
	"field-month": "Ayur", 
	"dateFormatItem-MMMMd": "MMMM d", 
	"quarters-format-abbr": [
		"IA1", 
		"IA2", 
		"IA3", 
		"IA4"
	], 
	"days-format-abbr": [
		"Asa", 
		"Ayn", 
		"Asn", 
		"Akr", 
		"Akw", 
		"Asm", 
		"Asḍ"
	], 
	"dateFormatItem-M": "L", 
	"days-format-narrow": [
		"A", 
		"A", 
		"A", 
		"A", 
		"A", 
		"A", 
		"A"
	], 
	"field-second": "Tusnat", 
	"field-day": "Ass", 
	"dateFormatItem-MEd": "E, M/d", 
	"months-format-narrow": [
		"Y", 
		"Y", 
		"M", 
		"I", 
		"M", 
		"Y", 
		"Y", 
		"Ɣ", 
		"C", 
		"K", 
		"N", 
		"D"
	], 
	"dateFormatItem-hm": "h:mm a", 
	"days-standAlone-abbr": [
		"Asa", 
		"Ayn", 
		"Asn", 
		"Akr", 
		"Akw", 
		"Asm", 
		"Asḍ"
	], 
	"dateFormat-short": "dd/MM/yyyy", 
	"dateFormatItem-yMMMEd": "EEE, MMM d, y", 
	"dateFormat-full": "EEEE, d MMMM y", 
	"dateFormatItem-Md": "M/d", 
	"dateFormatItem-yMEd": "EEE, M/d/y", 
	"months-format-wide": [
		"Yennayer", 
		"Yebrayer", 
		"Mars", 
		"Ibrir", 
		"Mayyu", 
		"Yunyu", 
		"Yulyuz", 
		"Ɣuct", 
		"Cutanbir", 
		"Kṭuber", 
		"Nwanbir", 
		"Dujanbir"
	], 
	"dateFormatItem-d": "d", 
	"quarters-format-wide": [
		"Imir adamsan 1", 
		"Imir adamsan 2", 
		"Imir adamsan 3", 
		"Imir adamsan 4"
	], 
	"days-format-wide": [
		"Asamas", 
		"Aynas", 
		"Asinas", 
		"Akras", 
		"Akwas", 
		"Asimwas", 
		"Asiḍyas"
	], 
	"eraNarrow": [
		"ZƐ", 
		"ḌƐ"
	]
})