({
	"dateFormatItem-yM": "M/y", 
	"dateFormatItem-yQ": "Q y", 
	"dayPeriods-format-wide-pm": "ᏒᎯᏱᎢᏗᏢ", 
	"field-minute": "ᎢᏯᏔᏬᏍᏔᏅ", 
	"eraNames": [
		"Ꮟ ᏥᏌ ᎾᏕᎲᏍᎬᎾ", 
		"ᎠᎩᏃᎮᎵᏓᏍᏗᏱ ᎠᏕᏘᏱᏍᎬ ᏱᎰᏩ ᏧᏓᏂᎸᎢᏍᏗ"
	], 
	"field-day-relative+-1": "ᏒᎯ", 
	"dateFormatItem-hms": "h:mm:ss a", 
	"dateFormatItem-yQQQ": "QQQ y", 
	"field-weekday": "ᏒᎾᏙᏓᏆᏍᏗ ᎠᏣᎢᎵᏒ", 
	"days-standAlone-wide": [
		"ᎤᎾᏙᏓᏆᏍᎬ", 
		"ᎤᎾᏙᏓᏉᏅᎯ", 
		"ᏔᎵᏁᎢᎦ", 
		"ᏦᎢᏁᎢᎦ", 
		"ᏅᎩᏁᎢᎦ", 
		"ᏧᎾᎩᎶᏍᏗ", 
		"ᎤᎾᏙᏓᏈᏕᎾ"
	], 
	"months-standAlone-narrow": [
		"Ꭴ", 
		"Ꭷ", 
		"Ꭰ", 
		"Ꭷ", 
		"Ꭰ", 
		"Ꮥ", 
		"Ꭻ", 
		"Ꭶ", 
		"Ꮪ", 
		"Ꮪ", 
		"Ꮕ", 
		"Ꭴ"
	], 
	"field-era": "ᎡᎶᎯ ᎠᏣᎢᎵᏒᎢ", 
	"dayPeriods-format-wide-am": "ᏌᎾᎴ", 
	"field-hour": "ᏑᏣᎶᏓ", 
	"timeFormat-full": "h:mm:ss a zzzz", 
	"months-standAlone-abbr": [
		"ᎤᏃ", 
		"ᎧᎦ", 
		"ᎠᏅ", 
		"ᎧᏬ", 
		"ᎠᏂ", 
		"ᏕᎭ", 
		"ᎫᏰ", 
		"ᎦᎶ", 
		"ᏚᎵ", 
		"ᏚᏂ", 
		"ᏅᏓ", 
		"ᎤᏍ"
	], 
	"dateFormatItem-yMMM": "MMM y", 
	"field-day-relative+0": "ᎪᎯ ᎢᎦ", 
	"days-standAlone-narrow": [
		"Ꮖ", 
		"Ꮙ", 
		"Ꮤ", 
		"Ꮶ", 
		"Ꮕ", 
		"Ꮷ", 
		"Ꭴ"
	], 
	"field-day-relative+1": "ᏌᎾᎴᎢ", 
	"eraAbbr": [
		"ᎤᏓᎷᎸ", 
		"ᎤᎶᏐᏅ"
	], 
	"dateFormat-long": "MMMM d, y", 
	"timeFormat-medium": "h:mm:ss a", 
	"field-zone": "ᎡᎶᎯ ᎠᏍᏓᏅᏅ", 
	"dateFormatItem-Hm": "H:mm", 
	"dateFormat-medium": "MMM d, y", 
	"dateFormatItem-Hms": "H:mm:ss", 
	"dateFormatItem-yMMMM": "MMMM y", 
	"field-year": "ᏑᏕᏘᏴᏓ", 
	"field-week": "ᏒᎾᏙᏓᏆᏍᏗ", 
	"months-standAlone-wide": [
		"ᎤᏃᎸᏔᏅ", 
		"ᎧᎦᎵ", 
		"ᎠᏅᏱ", 
		"ᎧᏬᏂ", 
		"ᎠᏂᏍᎬᏘ", 
		"ᏕᎭᎷᏱ", 
		"ᎫᏰᏉᏂ", 
		"ᎦᎶᏂ", 
		"ᏚᎵᏍᏗ", 
		"ᏚᏂᏅᏗ", 
		"ᏅᏓᏕᏆ", 
		"ᎤᏍᎩᏱ"
	], 
	"dateFormatItem-MMMd": "MMM d", 
	"timeFormat-long": "h:mm:ss a z", 
	"months-format-abbr": [
		"ᎤᏃ", 
		"ᎧᎦ", 
		"ᎠᏅ", 
		"ᎧᏬ", 
		"ᎠᏂ", 
		"ᏕᎭ", 
		"ᎫᏰ", 
		"ᎦᎶ", 
		"ᏚᎵ", 
		"ᏚᏂ", 
		"ᏅᏓ", 
		"ᎤᏍ"
	], 
	"dayPeriods-format-wide-noon": "ᎢᎦ", 
	"timeFormat-short": "h:mm a", 
	"field-month": "ᏏᏅᏓ", 
	"days-format-abbr": [
		"ᏆᏍᎬ", 
		"ᏉᏅᎯ", 
		"ᏔᎵᏁ", 
		"ᏦᎢᏁ", 
		"ᏅᎩᏁ", 
		"ᏧᎾᎩ", 
		"ᏈᏕᎾ"
	], 
	"days-format-narrow": [
		"Ꮖ", 
		"Ꮙ", 
		"Ꮤ", 
		"Ꮶ", 
		"Ꮕ", 
		"Ꮷ", 
		"Ꭴ"
	], 
	"field-second": "ᎠᏎᏢ", 
	"field-day": "ᏏᎦ", 
	"dateFormatItem-MEd": "E, M/d", 
	"months-format-narrow": [
		"Ꭴ", 
		"Ꭷ", 
		"Ꭰ", 
		"Ꭷ", 
		"Ꭰ", 
		"Ꮥ", 
		"Ꭻ", 
		"Ꭶ", 
		"Ꮪ", 
		"Ꮪ", 
		"Ꮕ", 
		"Ꭴ"
	], 
	"dateFormatItem-hm": "h:mm a", 
	"days-standAlone-abbr": [
		"ᏆᏍᎬ", 
		"ᏉᏅᎯ", 
		"ᏔᎵᏁ", 
		"ᏦᎢᏁ", 
		"ᏅᎩᏁ", 
		"ᏧᎾᎩ", 
		"ᏈᏕᎾ"
	], 
	"dateFormat-short": "M/d/yy", 
	"dateFormatItem-yMMMEd": "EEE, MMM d, y", 
	"dateFormat-full": "EEEE, MMMM d, y", 
	"dateFormatItem-Md": "M/d", 
	"dateFormatItem-yMEd": "EEE, M/d/y", 
	"months-format-wide": [
		"ᎤᏃᎸᏔᏅ", 
		"ᎧᎦᎵ", 
		"ᎠᏅᏱ", 
		"ᎧᏬᏂ", 
		"ᎠᏂᏍᎬᏘ", 
		"ᏕᎭᎷᏱ", 
		"ᎫᏰᏉᏂ", 
		"ᎦᎶᏂ", 
		"ᏚᎵᏍᏗ", 
		"ᏚᏂᏅᏗ", 
		"ᏅᏓᏕᏆ", 
		"ᎤᏍᎩᏱ"
	], 
	"days-format-wide": [
		"ᎤᎾᏙᏓᏆᏍᎬ", 
		"ᎤᎾᏙᏓᏉᏅᎯ", 
		"ᏔᎵᏁᎢᎦ", 
		"ᏦᎢᏁᎢᎦ", 
		"ᏅᎩᏁᎢᎦ", 
		"ᏧᎾᎩᎶᏍᏗ", 
		"ᎤᎾᏙᏓᏈᏕᎾ"
	], 
	"eraNarrow": [
		"ᎤᏓᎷᎸ", 
		"ᎤᎶᏐᏅ"
	]
})