({
	"months-standAlone-abbr": [
		"jan", 
		"feb", 
		"mar", 
		"apr", 
		"maj", 
		"jun", 
		"jul", 
		"aug", 
		"sep", 
		"okt", 
		"nov", 
		"dec"
	], 
	"days-standAlone-abbr": [
		"sab", 
		"ata", 
		"mar", 
		"pin", 
		"sis", 
		"tal", 
		"arf"
	], 
	"months-format-abbr": [
		"jan", 
		"feb", 
		"mar", 
		"apr", 
		"maj", 
		"jun", 
		"jul", 
		"aug", 
		"sep", 
		"okt", 
		"nov", 
		"dec"
	], 
	"field-day-relative+-1": "ippassaq", 
	"field-day-relative+-2": "ippassaani", 
	"field-day-relative+-3": "ippassaanissaani", 
	"days-format-abbr": [
		"sab", 
		"ata", 
		"mar", 
		"pin", 
		"sis", 
		"tal", 
		"arf"
	], 
	"field-day-relative+0": "ullumi", 
	"field-day-relative+1": "aqagu", 
	"months-standAlone-wide": [
		"januari", 
		"februari", 
		"martsi", 
		"aprili", 
		"maji", 
		"juni", 
		"juli", 
		"augustusi", 
		"septemberi", 
		"oktoberi", 
		"novemberi", 
		"decemberi"
	], 
	"field-day-relative+2": "aqaguagu", 
	"days-standAlone-wide": [
		"sabaat", 
		"ataasinngorneq", 
		"marlunngorneq", 
		"pingasunngorneq", 
		"sisamanngorneq", 
		"tallimanngorneq", 
		"arfininngorneq"
	], 
	"field-day-relative+3": "aqaguaguani", 
	"months-format-wide": [
		"januari", 
		"februari", 
		"martsi", 
		"aprili", 
		"maji", 
		"juni", 
		"juli", 
		"augustusi", 
		"septemberi", 
		"oktoberi", 
		"novemberi", 
		"decemberi"
	], 
	"days-format-wide": [
		"sabaat", 
		"ataasinngorneq", 
		"marlunngorneq", 
		"pingasunngorneq", 
		"sisamanngorneq", 
		"tallimanngorneq", 
		"arfininngorneq"
	]
})