({
	"months-format-narrow": [
		"1.", 
		"2.", 
		"3.", 
		"4.", 
		"5.", 
		"6.", 
		"7.", 
		"8.", 
		"9.", 
		"10.", 
		"11.", 
		"12."
	], 
	"field-weekday": "dan u tjednu", 
	"dateFormatItem-yyQQQQ": "QQQQ yy.", 
	"dateFormatItem-yQQQ": "QQQ y.", 
	"dateFormatItem-yMEd": "EEE, d.M.y.", 
	"dateFormatItem-MMMEd": "E, d.MMM.", 
	"eraNarrow": [
		"p. n. e.", 
		"A. D."
	], 
	"dateFormat-long": "d. MMMM y.", 
	"months-format-wide": [
		"siječnja", 
		"veljače", 
		"ožujka", 
		"travnja", 
		"svibnja", 
		"lipnja", 
		"srpnja", 
		"kolovoza", 
		"rujna", 
		"listopada", 
		"studenoga", 
		"prosinca"
	], 
	"dateFormatItem-EEEd": "EEE, d.", 
	"dayPeriods-format-wide-pm": "PM", 
	"dateFormat-full": "EEEE, d. MMMM y.", 
	"dateFormatItem-Md": "d.M.", 
	"field-era": "era", 
	"dateFormatItem-yM": "M.yyyy.", 
	"months-standAlone-wide": [
		"siječanj", 
		"veljača", 
		"ožujak", 
		"travanj", 
		"svibanj", 
		"lipanj", 
		"srpanj", 
		"kolovoz", 
		"rujan", 
		"listopad", 
		"studeni", 
		"prosinac"
	], 
	"timeFormat-short": "HH:mm", 
	"quarters-format-wide": [
		"1. kvartal", 
		"2. kvartal", 
		"3. kvartal", 
		"4. kvartal"
	], 
	"timeFormat-long": "HH:mm:ss z", 
	"field-year": "godina", 
	"dateFormatItem-yMMM": "MMM.y.", 
	"dateFormatItem-yQ": "Q. yyyy.", 
	"dateFormatItem-yyyyMMMM": "MMMM y.", 
	"field-hour": "sat", 
	"dateFormatItem-MMdd": "dd.MM.", 
	"months-format-abbr": [
		"sij", 
		"velj", 
		"ožu", 
		"tra", 
		"svi", 
		"lip", 
		"srp", 
		"kol", 
		"ruj", 
		"lis", 
		"stu", 
		"pro"
	], 
	"dateFormatItem-yyQ": "Q yy.", 
	"timeFormat-full": "HH:mm:ss zzzz", 
	"field-day-relative+0": "danas", 
	"field-day-relative+1": "sutra", 
	"field-day-relative+2": "prekosutra", 
	"dateFormatItem-H": "HH", 
	"field-day-relative+3": "za tri dana", 
	"months-standAlone-abbr": [
		"sij", 
		"velj", 
		"ožu", 
		"tra", 
		"svi", 
		"lip", 
		"srp", 
		"kol", 
		"ruj", 
		"lis", 
		"stu", 
		"pro"
	], 
	"quarters-format-abbr": [
		"1kv", 
		"2kv", 
		"3kv", 
		"4kv"
	], 
	"quarters-standAlone-wide": [
		"1. kvartal", 
		"2. kvartal", 
		"3. kvartal", 
		"4. kvartal"
	], 
	"days-standAlone-wide": [
		"nedjelja", 
		"ponedjeljak", 
		"utorak", 
		"srijeda", 
		"četvrtak", 
		"petak", 
		"subota"
	], 
	"dateFormatItem-MMMMd": "d. MMMM", 
	"dateFormatItem-yyMMMEEEd": "EEE, d.MMM.yy.", 
	"timeFormat-medium": "HH:mm:ss", 
	"dateFormatItem-Hm": "HH:mm", 
	"quarters-standAlone-abbr": [
		"1kv", 
		"2kv", 
		"3kv", 
		"4kv"
	], 
	"eraAbbr": [
		"p. n. e.", 
		"A. D."
	], 
	"field-minute": "minuta", 
	"field-dayperiod": "dio dana", 
	"days-standAlone-abbr": [
		"ned", 
		"pon", 
		"uto", 
		"sri", 
		"čet", 
		"pet", 
		"sub"
	], 
	"dateFormatItem-d": "d.", 
	"dateFormatItem-ms": "mm:ss", 
	"field-day-relative+-1": "jučer", 
	"dateFormatItem-h": "hh a", 
	"field-day-relative+-2": "prekjučer", 
	"field-day-relative+-3": "prije tri dana", 
	"dateFormatItem-MMMd": "d.MMM.", 
	"dateFormatItem-MEd": "E, d.M.", 
	"dateFormatItem-yMMMM": "MMMM y.", 
	"field-day": "dan", 
	"days-format-wide": [
		"nedjelja", 
		"ponedjeljak", 
		"utorak", 
		"srijeda", 
		"četvrtak", 
		"petak", 
		"subota"
	], 
	"field-zone": "zona", 
	"dateFormatItem-yyyyMM": "MM.yyyy.", 
	"dateFormatItem-y": "y.", 
	"months-standAlone-narrow": [
		"1.", 
		"2.", 
		"3.", 
		"4.", 
		"5.", 
		"6.", 
		"7.", 
		"8.", 
		"9.", 
		"10.", 
		"11.", 
		"12."
	], 
	"dateFormatItem-hm": "hh:mm a", 
	"days-format-abbr": [
		"ned", 
		"pon", 
		"uto", 
		"sri", 
		"čet", 
		"pet", 
		"sub"
	], 
	"eraNames": [
		"Prije Krista", 
		"Poslije Krista"
	], 
	"days-format-narrow": [
		"n", 
		"p", 
		"u", 
		"s", 
		"č", 
		"p", 
		"s"
	], 
	"field-month": "mjesec", 
	"days-standAlone-narrow": [
		"n", 
		"p", 
		"u", 
		"s", 
		"č", 
		"p", 
		"s"
	], 
	"dateFormatItem-MMM": "LLL.", 
	"dayPeriods-format-wide-am": "AM", 
	"dateFormatItem-MMMMEd": "E, d. MMMM", 
	"dateFormatItem-MMMMdd": "dd. MMMM", 
	"dateFormat-short": "dd. MM. yyyy.", 
	"field-second": "sekunda", 
	"dateFormatItem-yMMMEd": "EEE, d.MMM.y.", 
	"field-week": "tjedan", 
	"dateFormat-medium": "d. M. yyyy.", 
	"dateFormatItem-Hms": "HH:mm:ss", 
	"dateFormatItem-hms": "hh:mm:ss a"
})