({
	"dateFormatItem-yM": "M/yyyy", 
	"field-dayperiod": "Da bere", 
	"dayPeriods-format-wide-pm": "EW", 
	"dateFormatItem-yQ": "Q yyyy", 
	"field-minute": "Sema", 
	"eraNames": [
		"Ansa Kristo", 
		"Kristo Ekyiri"
	], 
	"dateFormatItem-MMMEd": "E, MMM d", 
	"field-day-relative+-1": "Ndeda", 
	"dateFormatItem-yQQQ": "QQQ yyyy", 
	"field-weekday": "Dapɛn mu da", 
	"days-standAlone-wide": [
		"Kwesida", 
		"Dwowda", 
		"Benada", 
		"Wukuda", 
		"Yawda", 
		"Fida", 
		"Memeneda"
	], 
	"dateFormatItem-MMM": "LLL", 
	"dayPeriods-format-wide-am": "AN", 
	"field-era": "Bere", 
	"field-hour": "Dɔnhwer", 
	"dateFormatItem-y": "yyyy", 
	"timeFormat-full": "HH:mm:ss zzzz", 
	"months-standAlone-abbr": [
		"S-Ɔ", 
		"K-Ɔ", 
		"E-Ɔ", 
		"E-O", 
		"E-K", 
		"O-A", 
		"A-K", 
		"D-Ɔ", 
		"F-Ɛ", 
		"Ɔ-A", 
		"Ɔ-O", 
		"M-Ɔ"
	], 
	"dateFormatItem-yMMM": "MMM yyyy", 
	"field-day-relative+0": "Ndɛ", 
	"days-standAlone-narrow": [
		"K", 
		"D", 
		"B", 
		"W", 
		"Y", 
		"F", 
		"M"
	], 
	"field-day-relative+1": "Ɔkyena", 
	"eraAbbr": [
		"AK", 
		"KE"
	], 
	"dateFormat-long": "y MMMM d", 
	"timeFormat-medium": "HH:mm:ss", 
	"field-zone": "Bere apaamu", 
	"dateFormatItem-Hm": "HH:mm", 
	"dateFormat-medium": "y MMM d", 
	"dateFormatItem-Hms": "HH:mm:ss", 
	"dateFormatItem-yMMMM": "MMMM yyyy", 
	"dateFormatItem-ms": "mm:ss", 
	"field-year": "Afe", 
	"field-week": "Dapɛn", 
	"months-standAlone-wide": [
		"Sanda-Ɔpɛpɔn", 
		"Kwakwar-Ɔgyefuo", 
		"Ebɔw-Ɔbenem", 
		"Ebɔbira-Oforisuo", 
		"Esusow Aketseaba-Kɔtɔnimba", 
		"Obirade-Ayɛwohomumu", 
		"Ayɛwoho-Kitawonsa", 
		"Difuu-Ɔsandaa", 
		"Fankwa-Ɛbɔ", 
		"Ɔbɛsɛ-Ahinime", 
		"Ɔberɛfɛw-Obubuo", 
		"Mumu-Ɔpɛnimba"
	], 
	"dateFormatItem-MMMMEd": "E, MMMM d", 
	"dateFormatItem-MMMd": "MMM d", 
	"dateFormatItem-yyQ": "Q yy", 
	"timeFormat-long": "HH:mm:ss z", 
	"months-format-abbr": [
		"S-Ɔ", 
		"K-Ɔ", 
		"E-Ɔ", 
		"E-O", 
		"E-K", 
		"O-A", 
		"A-K", 
		"D-Ɔ", 
		"F-Ɛ", 
		"Ɔ-A", 
		"Ɔ-O", 
		"M-Ɔ"
	], 
	"timeFormat-short": "HH:mm", 
	"field-month": "Bosome", 
	"dateFormatItem-MMMMd": "MMMM d", 
	"days-format-abbr": [
		"Kwe", 
		"Dwo", 
		"Ben", 
		"Wuk", 
		"Yaw", 
		"Fia", 
		"Mem"
	], 
	"dateFormatItem-M": "L", 
	"days-format-narrow": [
		"K", 
		"D", 
		"B", 
		"W", 
		"Y", 
		"F", 
		"M"
	], 
	"field-second": "Sɛkɛnd", 
	"field-day": "Da", 
	"dateFormatItem-MEd": "E, M/d", 
	"dateFormatItem-hm": "h:mm a", 
	"days-standAlone-abbr": [
		"Kwe", 
		"Dwo", 
		"Ben", 
		"Wuk", 
		"Yaw", 
		"Fia", 
		"Mem"
	], 
	"dateFormat-short": "yy/MM/dd", 
	"dateFormatItem-yMMMEd": "EEE, MMM d, yyyy", 
	"dateFormat-full": "EEEE, y MMMM dd", 
	"dateFormatItem-Md": "M/d", 
	"dateFormatItem-yMEd": "EEE, M/d/yyyy", 
	"months-format-wide": [
		"Sanda-Ɔpɛpɔn", 
		"Kwakwar-Ɔgyefuo", 
		"Ebɔw-Ɔbenem", 
		"Ebɔbira-Oforisuo", 
		"Esusow Aketseaba-Kɔtɔnimba", 
		"Obirade-Ayɛwohomumu", 
		"Ayɛwoho-Kitawonsa", 
		"Difuu-Ɔsandaa", 
		"Fankwa-Ɛbɔ", 
		"Ɔbɛsɛ-Ahinime", 
		"Ɔberɛfɛw-Obubuo", 
		"Mumu-Ɔpɛnimba"
	], 
	"dateFormatItem-d": "d", 
	"days-format-wide": [
		"Kwesida", 
		"Dwowda", 
		"Benada", 
		"Wukuda", 
		"Yawda", 
		"Fida", 
		"Memeneda"
	], 
	"eraNarrow": [
		"AK", 
		"KE"
	]
})