({
	"dateFormatItem-yM": "M/y", 
	"field-dayperiod": "Marango athiku", 
	"dayPeriods-format-wide-pm": "ichamthi", 
	"dateFormatItem-yQ": "Q y", 
	"field-minute": "Dakika", 
	"eraNames": [
		"Kabla yakwe Yethu", 
		"Baada yakwe Yethu"
	], 
	"dateFormatItem-MMMEd": "E, MMM d", 
	"field-day-relative+-1": "Ighuo", 
	"dateFormatItem-yQQQ": "QQQ y", 
	"field-weekday": "Thiku ya ndisha", 
	"days-standAlone-wide": [
		"Jumapili", 
		"Jumatatu", 
		"Jumanne", 
		"Jumatano", 
		"Alhamisi", 
		"Ijumaa", 
		"Jumamosi"
	], 
	"dateFormatItem-MMM": "LLL", 
	"months-standAlone-narrow": [
		"J", 
		"F", 
		"M", 
		"A", 
		"M", 
		"J", 
		"J", 
		"A", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"dayPeriods-format-wide-am": "icheheavo", 
	"field-era": "Edhi", 
	"field-hour": "Thaa", 
	"quarters-standAlone-abbr": [
		"R1", 
		"R2", 
		"R3", 
		"R4"
	], 
	"dateFormatItem-y": "y", 
	"timeFormat-full": "h:mm:ss a zzzz", 
	"months-standAlone-abbr": [
		"Jan", 
		"Feb", 
		"Mac", 
		"Apr", 
		"Mei", 
		"Jun", 
		"Jul", 
		"Ago", 
		"Sep", 
		"Okt", 
		"Nov", 
		"Dec"
	], 
	"dateFormatItem-yMMM": "MMM y", 
	"field-day-relative+0": "Iyoo", 
	"days-standAlone-narrow": [
		"J", 
		"J", 
		"J", 
		"J", 
		"A", 
		"I", 
		"J"
	], 
	"field-day-relative+1": "Yavo", 
	"eraAbbr": [
		"KM", 
		"BM"
	], 
	"dateFormat-long": "d MMMM y", 
	"timeFormat-medium": "h:mm:ss a", 
	"field-zone": "Majira Athaa", 
	"dateFormatItem-Hm": "HH:mm", 
	"dateFormat-medium": "d MMM y", 
	"dateFormatItem-Hms": "HH:mm:ss", 
	"quarters-standAlone-wide": [
		"Robo 1", 
		"Robo 2", 
		"Robo 3", 
		"Robo 4"
	], 
	"dateFormatItem-yMMMM": "MMMM y", 
	"dateFormatItem-ms": "mm:ss", 
	"field-year": "Mwaka", 
	"field-week": "Ndisha", 
	"months-standAlone-wide": [
		"Januari", 
		"Februari", 
		"Machi", 
		"Aprili", 
		"Mei", 
		"Juni", 
		"Julai", 
		"Agosti", 
		"Septemba", 
		"Oktoba", 
		"Novemba", 
		"Desemba"
	], 
	"dateFormatItem-MMMMEd": "E, MMMM d", 
	"dateFormatItem-MMMd": "MMM d", 
	"timeFormat-long": "h:mm:ss a z", 
	"months-format-abbr": [
		"Jan", 
		"Feb", 
		"Mac", 
		"Apr", 
		"Mei", 
		"Jun", 
		"Jul", 
		"Ago", 
		"Sep", 
		"Okt", 
		"Nov", 
		"Dec"
	], 
	"timeFormat-short": "h:mm a", 
	"field-month": "Mweji", 
	"dateFormatItem-MMMMd": "MMMM d", 
	"quarters-format-abbr": [
		"R1", 
		"R2", 
		"R3", 
		"R4"
	], 
	"days-format-abbr": [
		"Jpi", 
		"Jtt", 
		"Jnn", 
		"Jtn", 
		"Alh", 
		"Ijm", 
		"Jmo"
	], 
	"dateFormatItem-M": "L", 
	"days-format-narrow": [
		"J", 
		"J", 
		"J", 
		"J", 
		"A", 
		"I", 
		"J"
	], 
	"field-second": "Thekunde", 
	"field-day": "Thiku", 
	"dateFormatItem-MEd": "E, M/d", 
	"months-format-narrow": [
		"J", 
		"F", 
		"M", 
		"A", 
		"M", 
		"J", 
		"J", 
		"A", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"dateFormatItem-hm": "h:mm a", 
	"days-standAlone-abbr": [
		"Jpi", 
		"Jtt", 
		"Jnn", 
		"Jtn", 
		"Alh", 
		"Ijm", 
		"Jmo"
	], 
	"dateFormat-short": "dd/MM/yyyy", 
	"dateFormatItem-yMMMEd": "EEE, MMM d, y", 
	"dateFormat-full": "EEEE, d MMMM y", 
	"dateFormatItem-Md": "M/d", 
	"dateFormatItem-yMEd": "EEE, M/d/y", 
	"months-format-wide": [
		"Januari", 
		"Februari", 
		"Machi", 
		"Aprili", 
		"Mei", 
		"Juni", 
		"Julai", 
		"Agosti", 
		"Septemba", 
		"Oktoba", 
		"Novemba", 
		"Desemba"
	], 
	"dateFormatItem-d": "d", 
	"quarters-format-wide": [
		"Robo 1", 
		"Robo 2", 
		"Robo 3", 
		"Robo 4"
	], 
	"days-format-wide": [
		"Jumapili", 
		"Jumatatu", 
		"Jumanne", 
		"Jumatano", 
		"Alhamisi", 
		"Ijumaa", 
		"Jumamosi"
	], 
	"eraNarrow": [
		"KM", 
		"BM"
	]
})