({
	"quarters-format-abbr": [
		"I кв.", 
		"II кв.", 
		"III кв.", 
		"IV кв."
	], 
	"dateFormat-medium": "d MMM y", 
	"dateFormatItem-MMMEd": "E, d MMM", 
	"months-standAlone-wide": [
		"Тішри", 
		"Марчешван", 
		"Числьов", 
		"Тебет", 
		"Шеват", 
		"Адар I", 
		"Адар", 
		"Нісан", 
		"Іар", 
		"Сиван", 
		"Таммуз", 
		"Аб", 
		"Елул"
	], 
	"months-format-wide-leap": "Адар II", 
	"days-standAlone-narrow": [
		"Н", 
		"П", 
		"В", 
		"С", 
		"Ч", 
		"П", 
		"С"
	], 
	"dayPeriods-format-wide-pm": "пп", 
	"months-standAlone-abbr": [
		"Тішри", 
		"Марчешван", 
		"Числьов", 
		"Тебет", 
		"Шеват", 
		"Адар I", 
		"Адар", 
		"Нісан", 
		"Іар", 
		"Сиван", 
		"Таммуз", 
		"Аб", 
		"Елул"
	], 
	"dayPeriods-format-wide-am": "дп", 
	"dateFormat-long": "d MMMM y 'р'.", 
	"dateFormat-short": "dd.MM.yy", 
	"dateFormatItem-yMMMEd": "EEE, d MMM y", 
	"months-format-wide": [
		"Тішри", 
		"Марчешван", 
		"Числьов", 
		"Тебет", 
		"Шеват", 
		"Адар I", 
		"Адар", 
		"Нісан", 
		"Іар", 
		"Сиван", 
		"Таммуз", 
		"Аб", 
		"Елул"
	], 
	"months-format-abbr": [
		"Тішри", 
		"Марчешван", 
		"Числьов", 
		"Тебет", 
		"Шеват", 
		"Адар I", 
		"Адар", 
		"Нісан", 
		"Іар", 
		"Сиван", 
		"Таммуз", 
		"Аб", 
		"Елул"
	], 
	"days-format-wide": [
		"Неділя", 
		"Понеділок", 
		"Вівторок", 
		"Середа", 
		"Четвер", 
		"Пʼятниця", 
		"Субота"
	], 
	"dateFormatItem-yMMM": "LLL y", 
	"quarters-format-wide": [
		"I квартал", 
		"II квартал", 
		"III квартал", 
		"IV квартал"
	], 
	"dateFormat-full": "EEEE, d MMMM y 'р'.", 
	"dateFormatItem-MMMd": "d MMM", 
	"days-format-abbr": [
		"Нд", 
		"Пн", 
		"Вт", 
		"Ср", 
		"Чт", 
		"Пт", 
		"Сб"
	]
})