({
	"field-dayperiod": "pre podne/ popodne", 
	"dayPeriods-format-wide-pm": "popodne", 
	"field-minute": "minut", 
	"eraNames": [
		"Pre nove ere", 
		"Nove ere"
	], 
	"field-day-relative+-1": "juče", 
	"dateFormatItem-yQQQ": "y QQQ", 
	"field-day-relative+-2": "prekjuče", 
	"field-weekday": "dan u nedelji", 
	"field-day-relative+-3": "pre tri dana", 
	"days-standAlone-wide": [
		"nedelja", 
		"ponedeljak", 
		"utorak", 
		"sreda", 
		"četvrtak", 
		"petak", 
		"subota"
	], 
	"months-standAlone-narrow": [
		"j", 
		"f", 
		"m", 
		"a", 
		"m", 
		"j", 
		"j", 
		"a", 
		"s", 
		"o", 
		"n", 
		"d"
	], 
	"field-era": "era", 
	"dayPeriods-format-wide-am": "pre podne", 
	"field-hour": "čas", 
	"timeFormat-full": "HH.mm.ss zzzz", 
	"months-standAlone-abbr": [
		"jan", 
		"feb", 
		"mar", 
		"apr", 
		"maj", 
		"jun", 
		"jul", 
		"avg", 
		"sep", 
		"okt", 
		"nov", 
		"dec"
	], 
	"dateFormatItem-yMMM": "y MMM", 
	"field-day-relative+0": "danas", 
	"field-day-relative+1": "sutra", 
	"days-standAlone-narrow": [
		"n", 
		"p", 
		"u", 
		"s", 
		"č", 
		"p", 
		"s"
	], 
	"eraAbbr": [
		"p. n. e.", 
		"n. e"
	], 
	"field-day-relative+2": "prekosutra", 
	"field-day-relative+3": "za tri dana", 
	"dateFormat-long": "dd. MMMM y.", 
	"timeFormat-medium": "HH.mm.ss", 
	"dateFormatItem-EEEd": "d EEE", 
	"field-zone": "zona", 
	"dateFormatItem-Hm": "HH.mm", 
	"dateFormat-medium": "dd.MM.y.", 
	"dateFormatItem-Hms": "HH.mm.ss", 
	"quarters-standAlone-wide": [
		"1. kvartal", 
		"2. kvartal", 
		"3. kvartal", 
		"4. kvartal"
	], 
	"field-year": "godina", 
	"field-week": "nedelja", 
	"months-standAlone-wide": [
		"januar", 
		"februar", 
		"mart", 
		"april", 
		"maj", 
		"jun", 
		"jul", 
		"avgust", 
		"septembar", 
		"oktobar", 
		"novembar", 
		"decembar"
	], 
	"timeFormat-long": "HH.mm.ss z", 
	"months-format-abbr": [
		"jan", 
		"feb", 
		"mar", 
		"apr", 
		"maj", 
		"jun", 
		"jul", 
		"avg", 
		"sep", 
		"okt", 
		"nov", 
		"dec"
	], 
	"timeFormat-short": "HH.mm", 
	"field-month": "mesec", 
	"quarters-format-abbr": [
		"Q1", 
		"Q2", 
		"Q3", 
		"Q4"
	], 
	"days-format-abbr": [
		"ned", 
		"pon", 
		"uto", 
		"sre", 
		"čet", 
		"pet", 
		"sub"
	], 
	"days-format-narrow": [
		"n", 
		"p", 
		"u", 
		"s", 
		"č", 
		"p", 
		"s"
	], 
	"field-second": "sekund", 
	"field-day": "dan", 
	"months-format-narrow": [
		"j", 
		"f", 
		"m", 
		"a", 
		"m", 
		"j", 
		"j", 
		"a", 
		"s", 
		"o", 
		"n", 
		"d"
	], 
	"days-standAlone-abbr": [
		"ned", 
		"pon", 
		"uto", 
		"sre", 
		"čet", 
		"pet", 
		"sub"
	], 
	"dateFormat-short": "d.M.yy.", 
	"dateFormat-full": "EEEE, dd. MMMM y.", 
	"months-format-wide": [
		"januar", 
		"februar", 
		"mart", 
		"april", 
		"maj", 
		"jun", 
		"jul", 
		"avgust", 
		"septembar", 
		"oktobar", 
		"novembar", 
		"decembar"
	], 
	"quarters-format-wide": [
		"1. kvartal", 
		"2. kvartal", 
		"3. kvartal", 
		"4. kvartal"
	], 
	"days-format-wide": [
		"nedelja", 
		"ponedeljak", 
		"utorak", 
		"sreda", 
		"četvrtak", 
		"petak", 
		"subota"
	], 
	"eraNarrow": [
		"p. n. e.", 
		"n. e"
	]
})