({
	"dayPeriods-format-wide-pm": "pm", 
	"field-minute": "मिनिट", 
	"eraNames": [
		"ईसवीसनपूर्व", 
		"ईसवीसन"
	], 
	"field-day-relative+-1": "काल", 
	"field-day-relative+-2": "परवा", 
	"dateFormatItem-MMdd": "dd-MM", 
	"field-weekday": "आठवड्याचा दिवस", 
	"field-day-relative+-3": "तीन दिवसांपूर्वी", 
	"days-standAlone-wide": [
		"रविवार", 
		"सोमवार", 
		"मंगळवार", 
		"बुधवार", 
		"गुरुवार", 
		"शुक्रवार", 
		"शनिवार"
	], 
	"months-standAlone-narrow": [
		"जा", 
		"फे", 
		"मा", 
		"ए", 
		"मे", 
		"जू", 
		"जु", 
		"ऑ", 
		"स", 
		"ऑ", 
		"नो", 
		"डि"
	], 
	"field-era": "युग", 
	"dayPeriods-format-wide-am": "am", 
	"field-hour": "तास", 
	"timeFormat-full": "h-mm-ss a zzzz", 
	"months-standAlone-abbr": [
		"जानेवारी", 
		"फेब्रुवारी", 
		"मार्च", 
		"एप्रिल", 
		"मे", 
		"जून", 
		"जुलै", 
		"ऑगस्ट", 
		"सप्टेंबर", 
		"ऑक्टोबर", 
		"नोव्हेंबर", 
		"डिसेंबर"
	], 
	"field-day-relative+0": "आज", 
	"days-standAlone-narrow": [
		"र", 
		"सो", 
		"मं", 
		"बु", 
		"गु", 
		"शु", 
		"श"
	], 
	"field-day-relative+1": "उद्या", 
	"eraAbbr": [
		"ई.स.पू.", 
		"ई.स."
	], 
	"field-day-relative+2": "परवा", 
	"field-day-relative+3": "आजपासून तीन दिवस", 
	"dateFormatItem-yyyyMM": "MM-yyyy", 
	"dateFormatItem-yyyyMMMM": "MMMM y", 
	"dateFormat-long": "d MMMM y", 
	"timeFormat-medium": "h-mm-ss a", 
	"field-zone": "झोन", 
	"dateFormatItem-Hm": "H-mm", 
	"dateFormat-medium": "d MMM y", 
	"dateFormatItem-Hms": "H-mm-ss", 
	"quarters-standAlone-wide": [
		"प्रथम तिमाही", 
		"द्वितीय तिमाही", 
		"तृतीय तिमाही", 
		"चतुर्थ तिमाही"
	], 
	"field-year": "वर्ष", 
	"field-week": "आठवडा", 
	"months-standAlone-wide": [
		"जानेवारी", 
		"फेब्रुवारी", 
		"मार्च", 
		"एप्रिल", 
		"मे", 
		"जून", 
		"जुलै", 
		"ऑगस्ट", 
		"सप्टेंबर", 
		"ऑक्टोबर", 
		"नोव्हेंबर", 
		"डिसेंबर"
	], 
	"dateFormatItem-yyQ": "Q yy", 
	"timeFormat-long": "h-mm-ss a z", 
	"months-format-abbr": [
		"जानेवारी", 
		"फेब्रुवारी", 
		"मार्च", 
		"एप्रिल", 
		"मे", 
		"जून", 
		"जुलै", 
		"ऑगस्ट", 
		"सप्टेंबर", 
		"ऑक्टोबर", 
		"नोव्हेंबर", 
		"डिसेंबर"
	], 
	"timeFormat-short": "h-mm a", 
	"field-month": "महिना", 
	"dateFormatItem-MMMMd": "d MMMM", 
	"quarters-format-abbr": [
		"Q1", 
		"Q2", 
		"Q3", 
		"Q4"
	], 
	"days-format-abbr": [
		"रवि", 
		"सोम", 
		"मंगळ", 
		"बुध", 
		"गुरु", 
		"शुक्र", 
		"शनि"
	], 
	"days-format-narrow": [
		"र", 
		"सो", 
		"मं", 
		"बु", 
		"गु", 
		"शु", 
		"श"
	], 
	"field-second": "सेकंद", 
	"field-day": "दिवस", 
	"months-format-narrow": [
		"जा", 
		"फे", 
		"मा", 
		"ए", 
		"मे", 
		"जू", 
		"जु", 
		"ऑ", 
		"स", 
		"ऑ", 
		"नो", 
		"डि"
	], 
	"days-standAlone-abbr": [
		"रवि", 
		"सोम", 
		"मंगळ", 
		"बुध", 
		"गुरु", 
		"शुक्र", 
		"शनि"
	], 
	"dateFormat-short": "d-M-yy", 
	"dateFormat-full": "EEEE d MMMM y", 
	"months-format-wide": [
		"जानेवारी", 
		"फेब्रुवारी", 
		"मार्च", 
		"एप्रिल", 
		"मे", 
		"जून", 
		"जुलै", 
		"ऑगस्ट", 
		"सप्टेंबर", 
		"ऑक्टोबर", 
		"नोव्हेंबर", 
		"डिसेंबर"
	], 
	"quarters-format-wide": [
		"प्रथम तिमाही", 
		"द्वितीय तिमाही", 
		"तृतीय तिमाही", 
		"चतुर्थ तिमाही"
	], 
	"days-format-wide": [
		"रविवार", 
		"सोमवार", 
		"मंगळवार", 
		"बुधवार", 
		"गुरुवार", 
		"शुक्रवार", 
		"शनिवार"
	], 
	"eraNarrow": [
		"ई.स.पू.", 
		"ई.स."
	]
})