({
	"dateFormatItem-yM": "MM/yyyy", 
	"field-dayperiod": "Dayperiod", 
	"dayPeriods-format-wide-pm": "пасля палудня", 
	"dateFormatItem-yQ": "Q 'кв'. y", 
	"dayPeriods-standAlone-abbr-pm": "вечара", 
	"field-minute": "хвіліна", 
	"dateFormatItem-MMMEd": "E, d MMM", 
	"eraNames": [
		"да н.э.", 
		"н.э."
	], 
	"field-day-relative+-1": "учора", 
	"dateFormatItem-hms": "h.mm.ss a", 
	"dateFormatItem-yQQQ": "QQQ y", 
	"field-day-relative+-2": "пазаўчора", 
	"field-weekday": "дзень тыдня", 
	"days-standAlone-wide": [
		"нядзеля", 
		"панядзелак", 
		"аўторак", 
		"серада", 
		"чацвер", 
		"пятніца", 
		"субота"
	], 
	"dateFormatItem-MMM": "LLL", 
	"months-standAlone-narrow": [
		"с", 
		"л", 
		"с", 
		"к", 
		"м", 
		"ч", 
		"л", 
		"ж", 
		"в", 
		"к", 
		"л", 
		"с"
	], 
	"dayPeriods-format-wide-am": "да палудня", 
	"field-era": "эра", 
	"field-hour": "гадзіна", 
	"dayPeriods-standAlone-abbr-am": "раніцы", 
	"quarters-standAlone-abbr": [
		"1-шы кв.", 
		"2-гі кв.", 
		"3-ці кв.", 
		"4-ты кв."
	], 
	"dateFormatItem-y": "y", 
	"timeFormat-full": "HH.mm.ss zzzz", 
	"months-standAlone-abbr": [
		"сту", 
		"лют", 
		"сак", 
		"кра", 
		"тра", 
		"чэр", 
		"ліп", 
		"жні", 
		"вер", 
		"кас", 
		"ліс", 
		"сне"
	], 
	"dateFormatItem-yMMM": "MMM y", 
	"field-day-relative+0": "сёння", 
	"days-standAlone-narrow": [
		"н", 
		"п", 
		"а", 
		"с", 
		"ч", 
		"п", 
		"с"
	], 
	"field-day-relative+1": "заўтра", 
	"eraAbbr": [
		"да н.э.", 
		"н.э."
	], 
	"field-day-relative+2": "паслязаўтра", 
	"dateFormat-long": "d MMMM y", 
	"timeFormat-medium": "HH.mm.ss", 
	"field-zone": "Zone", 
	"dateFormatItem-Hm": "HH.mm", 
	"dateFormat-medium": "d.M.yyyy", 
	"dateFormatItem-Hms": "HH.mm.ss", 
	"quarters-standAlone-wide": [
		"1-шы квартал", 
		"2-гі квартал", 
		"3-ці квартал", 
		"4-ты квартал"
	], 
	"dateFormatItem-yMMMM": "MMMM y", 
	"dateFormatItem-ms": "mm.ss", 
	"field-year": "год", 
	"months-standAlone-wide": [
		"студзень", 
		"люты", 
		"сакавік", 
		"красавік", 
		"травень", 
		"чэрвень", 
		"ліпень", 
		"жнівень", 
		"верасень", 
		"кастрычнік", 
		"лістапад", 
		"снежань"
	], 
	"field-week": "тыдзень", 
	"dateFormatItem-MMMMEd": "MMMM d, EEEE", 
	"dateFormatItem-MMMd": "d MMM", 
	"timeFormat-long": "HH.mm.ss z", 
	"months-format-abbr": [
		"сту", 
		"лют", 
		"сак", 
		"кра", 
		"май", 
		"чэр", 
		"ліп", 
		"жні", 
		"вер", 
		"кас", 
		"ліс", 
		"сне"
	], 
	"timeFormat-short": "HH.mm", 
	"field-month": "месяц", 
	"dateFormatItem-MMMMd": "MMMM d", 
	"quarters-format-abbr": [
		"1-шы кв.", 
		"2-гі кв.", 
		"3-ці кв.", 
		"4-ты кв."
	], 
	"days-format-abbr": [
		"нд", 
		"пн", 
		"аў", 
		"ср", 
		"чц", 
		"пт", 
		"сб"
	], 
	"dateFormatItem-M": "L", 
	"days-format-narrow": [
		"н", 
		"п", 
		"а", 
		"с", 
		"ч", 
		"п", 
		"с"
	], 
	"field-second": "секунда", 
	"field-day": "дзень", 
	"dateFormatItem-MEd": "E, d MMM", 
	"months-format-narrow": [
		"с", 
		"л", 
		"с", 
		"к", 
		"т", 
		"ч", 
		"л", 
		"ж", 
		"в", 
		"к", 
		"л", 
		"с"
	], 
	"dateFormatItem-hm": "h.mm a", 
	"days-standAlone-abbr": [
		"нд", 
		"пн", 
		"аў", 
		"ср", 
		"чц", 
		"пт", 
		"сб"
	], 
	"dateFormat-short": "d.M.yy", 
	"dateFormatItem-yyyyM": "MM/yyyy", 
	"dateFormatItem-yMMMEd": "EEE, d MMM y", 
	"dateFormat-full": "EEEE, d MMMM y", 
	"dateFormatItem-yMEd": "EEE, dd/MM/yyyy", 
	"months-format-wide": [
		"студзень", 
		"люты", 
		"сакавік", 
		"красавік", 
		"май", 
		"чэрвень", 
		"ліпень", 
		"жнівень", 
		"верасень", 
		"кастрычнік", 
		"лістапад", 
		"снежань"
	], 
	"dateFormatItem-d": "d", 
	"quarters-format-wide": [
		"1-шы квартал", 
		"2-гі квартал", 
		"3-ці квартал", 
		"4-ты квартал"
	], 
	"days-format-wide": [
		"нядзеля", 
		"панядзелак", 
		"аўторак", 
		"серада", 
		"чацвер", 
		"пятніца", 
		"субота"
	], 
	"eraNarrow": [
		"да н.э.", 
		"н.э."
	]
})