({
	"dateFormatItem-yM": "M/y", 
	"field-dayperiod": "Muda wa siku", 
	"dayPeriods-format-wide-pm": "alasiri", 
	"dateFormatItem-yQ": "Q y", 
	"field-minute": "Dakika", 
	"eraNames": [
		"Kabla ya Kristo", 
		"Baada ya Kristo"
	], 
	"dateFormatItem-MMMEd": "E, MMM d", 
	"field-day-relative+-1": "Jana", 
	"dateFormatItem-yQQQ": "QQQ y", 
	"field-weekday": "Siku ya wiki", 
	"days-standAlone-wide": [
		"Jumapili", 
		"Jumatatu", 
		"Jumanne", 
		"Jumatano", 
		"Alhamisi", 
		"Ijumaa", 
		"Jumamosi"
	], 
	"dateFormatItem-MMM": "LLL", 
	"months-standAlone-narrow": [
		"J", 
		"F", 
		"M", 
		"A", 
		"M", 
		"J", 
		"J", 
		"A", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"dayPeriods-format-wide-am": "asubuhi", 
	"field-era": "Enzi", 
	"field-hour": "Saa", 
	"quarters-standAlone-abbr": [
		"R1", 
		"R2", 
		"R3", 
		"R4"
	], 
	"dateFormatItem-y": "y", 
	"timeFormat-full": "h:mm:ss a zzzz", 
	"months-standAlone-abbr": [
		"Jan", 
		"Feb", 
		"Mac", 
		"Apr", 
		"Mei", 
		"Jun", 
		"Jul", 
		"Ago", 
		"Sep", 
		"Okt", 
		"Nov", 
		"Des"
	], 
	"dateFormatItem-yMMM": "MMM y", 
	"field-day-relative+0": "Leo", 
	"days-standAlone-narrow": [
		"2", 
		"3", 
		"4", 
		"5", 
		"A", 
		"I", 
		"1"
	], 
	"field-day-relative+1": "Kesho", 
	"eraAbbr": [
		"KK", 
		"BK"
	], 
	"dateFormat-long": "d MMMM y", 
	"timeFormat-medium": "h:mm:ss a", 
	"field-zone": "Majira ya saa", 
	"dateFormatItem-Hm": "HH:mm", 
	"dateFormat-medium": "d MMM y", 
	"dateFormatItem-Hms": "HH:mm:ss", 
	"quarters-standAlone-wide": [
		"Robo 1", 
		"Robo 2", 
		"Robo 3", 
		"Robo 4"
	], 
	"dateFormatItem-yMMMM": "MMMM y", 
	"dateFormatItem-ms": "mm:ss", 
	"field-year": "Mwaka", 
	"field-week": "Wiki", 
	"months-standAlone-wide": [
		"Januari", 
		"Februari", 
		"Machi", 
		"Aprili", 
		"Mei", 
		"Juni", 
		"Julai", 
		"Agosti", 
		"Septemba", 
		"Oktoba", 
		"Novemba", 
		"Desemba"
	], 
	"dateFormatItem-MMMMEd": "E, MMMM d", 
	"dateFormatItem-MMMd": "MMM d", 
	"timeFormat-long": "h:mm:ss a z", 
	"months-format-abbr": [
		"Jan", 
		"Feb", 
		"Mac", 
		"Apr", 
		"Mei", 
		"Jun", 
		"Jul", 
		"Ago", 
		"Sep", 
		"Okt", 
		"Nov", 
		"Des"
	], 
	"timeFormat-short": "h:mm a", 
	"field-month": "Mwezi", 
	"dateFormatItem-MMMMd": "MMMM d", 
	"quarters-format-abbr": [
		"R1", 
		"R2", 
		"R3", 
		"R4"
	], 
	"days-format-abbr": [
		"J2", 
		"J3", 
		"J4", 
		"J5", 
		"Alh", 
		"Ij", 
		"J1"
	], 
	"dateFormatItem-M": "L", 
	"days-format-narrow": [
		"2", 
		"3", 
		"4", 
		"5", 
		"A", 
		"I", 
		"1"
	], 
	"field-second": "Sekunde", 
	"field-day": "Siku", 
	"dateFormatItem-MEd": "E, M/d", 
	"months-format-narrow": [
		"J", 
		"F", 
		"M", 
		"A", 
		"M", 
		"J", 
		"J", 
		"A", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"dateFormatItem-hm": "h:mm a", 
	"days-standAlone-abbr": [
		"J2", 
		"J3", 
		"J4", 
		"J5", 
		"Alh", 
		"Ij", 
		"J1"
	], 
	"dateFormat-short": "dd/MM/yyyy", 
	"dateFormatItem-yMMMEd": "EEE, MMM d, y", 
	"dateFormat-full": "EEEE, d MMMM y", 
	"dateFormatItem-Md": "M/d", 
	"dateFormatItem-yMEd": "EEE, M/d/y", 
	"months-format-wide": [
		"Januari", 
		"Februari", 
		"Machi", 
		"Aprili", 
		"Mei", 
		"Juni", 
		"Julai", 
		"Agosti", 
		"Septemba", 
		"Oktoba", 
		"Novemba", 
		"Desemba"
	], 
	"dateFormatItem-d": "d", 
	"quarters-format-wide": [
		"Robo 1", 
		"Robo 2", 
		"Robo 3", 
		"Robo 4"
	], 
	"days-format-wide": [
		"Jumapili", 
		"Jumatatu", 
		"Jumanne", 
		"Jumatano", 
		"Alhamisi", 
		"Ijumaa", 
		"Jumamosi"
	], 
	"eraNarrow": [
		"KK", 
		"BK"
	]
})