({
	"dateFormatItem-yM": "M/y", 
	"field-dayperiod": "Mũthenya", 
	"dayPeriods-format-wide-pm": "ŨG", 
	"dateFormatItem-yQ": "Q y", 
	"field-minute": "Ndagika", 
	"eraNames": [
		"Mbere ya Kristũ", 
		"Nyuma ya Kristũ"
	], 
	"dateFormatItem-MMMEd": "E, MMM d", 
	"field-day-relative+-1": "Ĩgoro", 
	"dateFormatItem-yQQQ": "QQQ y", 
	"field-weekday": "Ntukũ ya ngũgĩ", 
	"days-standAlone-wide": [
		"Kiumia", 
		"Muramuko", 
		"Wairi", 
		"Wethatu", 
		"Wena", 
		"Wetano", 
		"Jumamosi"
	], 
	"dateFormatItem-MMM": "LLL", 
	"months-standAlone-narrow": [
		"J", 
		"F", 
		"M", 
		"Ĩ", 
		"M", 
		"N", 
		"N", 
		"A", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"dayPeriods-format-wide-am": "RŨ", 
	"field-era": "Ĩgita", 
	"field-hour": "Ĩthaa", 
	"quarters-standAlone-abbr": [
		"Ĩmwe kĩrĩ inya", 
		"Ijĩrĩ kĩrĩ inya", 
		"Ithatũ kĩrĩ inya", 
		"Inya kĩrĩ inya"
	], 
	"dateFormatItem-y": "y", 
	"timeFormat-full": "h:mm:ss a zzzz", 
	"months-standAlone-abbr": [
		"JAN", 
		"FEB", 
		"MAC", 
		"ĨPU", 
		"MĨĨ", 
		"NJU", 
		"NJR", 
		"AGA", 
		"SPT", 
		"OKT", 
		"NOV", 
		"DEC"
	], 
	"dateFormatItem-yMMM": "MMM y", 
	"field-day-relative+0": "Narua", 
	"days-standAlone-narrow": [
		"K", 
		"M", 
		"W", 
		"W", 
		"W", 
		"W", 
		"J"
	], 
	"field-day-relative+1": "Rũjũ", 
	"eraAbbr": [
		"MK", 
		"NK"
	], 
	"dateFormat-long": "d MMMM y", 
	"timeFormat-medium": "h:mm:ss a", 
	"field-zone": "Gũntũ kwa thaa", 
	"dateFormatItem-Hm": "HH:mm", 
	"dateFormat-medium": "d MMM y", 
	"dateFormatItem-Hms": "HH:mm:ss", 
	"quarters-standAlone-wide": [
		"Ĩmwe kĩrĩ inya", 
		"Ijĩrĩ kĩrĩ inya", 
		"Ithatũ kĩrĩ inya", 
		"Inya kĩrĩ inya"
	], 
	"dateFormatItem-yMMMM": "MMMM y", 
	"dateFormatItem-ms": "mm:ss", 
	"field-year": "Mwaka", 
	"field-week": "Kiumia", 
	"months-standAlone-wide": [
		"Januarĩ", 
		"Feburuarĩ", 
		"Machi", 
		"Ĩpurũ", 
		"Mĩĩ", 
		"Njuni", 
		"Njuraĩ", 
		"Agasti", 
		"Septemba", 
		"Oktũba", 
		"Novemba", 
		"Dicemba"
	], 
	"dateFormatItem-MMMMEd": "E, MMMM d", 
	"dateFormatItem-MMMd": "MMM d", 
	"timeFormat-long": "h:mm:ss a z", 
	"months-format-abbr": [
		"JAN", 
		"FEB", 
		"MAC", 
		"ĨPU", 
		"MĨĨ", 
		"NJU", 
		"NJR", 
		"AGA", 
		"SPT", 
		"OKT", 
		"NOV", 
		"DEC"
	], 
	"timeFormat-short": "h:mm a", 
	"field-month": "Mweri", 
	"dateFormatItem-MMMMd": "MMMM d", 
	"quarters-format-abbr": [
		"Ĩmwe kĩrĩ inya", 
		"Ijĩrĩ kĩrĩ inya", 
		"Ithatũ kĩrĩ inya", 
		"Inya kĩrĩ inya"
	], 
	"days-format-abbr": [
		"KIU", 
		"MRA", 
		"WAI", 
		"WET", 
		"WEN", 
		"WTN", 
		"JUM"
	], 
	"dateFormatItem-M": "L", 
	"days-format-narrow": [
		"K", 
		"M", 
		"W", 
		"W", 
		"W", 
		"W", 
		"J"
	], 
	"field-second": "Sekondi", 
	"field-day": "Ntukũ", 
	"dateFormatItem-MEd": "E, M/d", 
	"months-format-narrow": [
		"J", 
		"F", 
		"M", 
		"Ĩ", 
		"M", 
		"N", 
		"N", 
		"A", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"dateFormatItem-hm": "h:mm a", 
	"days-standAlone-abbr": [
		"KIU", 
		"MRA", 
		"WAI", 
		"WET", 
		"WEN", 
		"WTN", 
		"JUM"
	], 
	"dateFormat-short": "dd/MM/yyyy", 
	"dateFormatItem-yMMMEd": "EEE, MMM d, y", 
	"dateFormat-full": "EEEE, d MMMM y", 
	"dateFormatItem-Md": "M/d", 
	"dateFormatItem-yMEd": "EEE, M/d/y", 
	"months-format-wide": [
		"Januarĩ", 
		"Feburuarĩ", 
		"Machi", 
		"Ĩpurũ", 
		"Mĩĩ", 
		"Njuni", 
		"Njuraĩ", 
		"Agasti", 
		"Septemba", 
		"Oktũba", 
		"Novemba", 
		"Dicemba"
	], 
	"dateFormatItem-d": "d", 
	"quarters-format-wide": [
		"Ĩmwe kĩrĩ inya", 
		"Ijĩrĩ kĩrĩ inya", 
		"Ithatũ kĩrĩ inya", 
		"Inya kĩrĩ inya"
	], 
	"days-format-wide": [
		"Kiumia", 
		"Muramuko", 
		"Wairi", 
		"Wethatu", 
		"Wena", 
		"Wetano", 
		"Jumamosi"
	], 
	"eraNarrow": [
		"MK", 
		"NK"
	]
})