({
	"dateFormatItem-yM": "M-y", 
	"field-dayperiod": "समय अवधि", 
	"dateFormatItem-yyMMdd": "dd-MM-yy", 
	"dateFormatItem-yQ": "y Q", 
	"dayPeriods-format-wide-pm": "अपराह्न", 
	"field-minute": "मिनट", 
	"dateFormatItem-MMMEd": "E, d MMM", 
	"eraNames": [
		"ईसापूर्व", 
		"सन"
	], 
	"field-day-relative+-1": "कल", 
	"dateFormatItem-MMdd": "dd-MM", 
	"field-day-relative+-2": "परसों", 
	"field-weekday": "सप्ताह का दिन", 
	"field-day-relative+-3": "नरसों", 
	"days-standAlone-wide": [
		"रविवार", 
		"सोमवार", 
		"मंगलवार", 
		"बुधवार", 
		"बृहस्पतिवार", 
		"शुक्रवार", 
		"शनिवार"
	], 
	"months-standAlone-narrow": [
		"ज", 
		"फ़", 
		"मा", 
		"अ", 
		"म", 
		"जू", 
		"जु", 
		"अ", 
		"सि", 
		"अ", 
		"न", 
		"दि"
	], 
	"dayPeriods-format-wide-am": "पूर्वाह्न", 
	"field-era": "युग", 
	"field-hour": "घंटा", 
	"quarters-standAlone-abbr": [
		"तिमाही", 
		"दूसरी तिमाही", 
		"तीसरी तिमाही", 
		"चौथी तिमाही"
	], 
	"dateFormatItem-y": "y", 
	"dateFormatItem-yyMMMEEEd": "EEE, d MMM yy", 
	"dateFormatItem-MMMdd": "dd MMM", 
	"timeFormat-full": "h:mm:ss a zzzz", 
	"months-standAlone-abbr": [
		"जनवरी", 
		"फरवरी", 
		"मार्च", 
		"अप्रैल", 
		"मई", 
		"जून", 
		"जुलाई", 
		"अगस्त", 
		"सितम्बर", 
		"अक्तूबर", 
		"नवम्बर", 
		"दिसम्बर"
	], 
	"dateFormatItem-yMMM": "MMM y", 
	"field-day-relative+0": "आज", 
	"days-standAlone-narrow": [
		"र", 
		"सो", 
		"मं", 
		"बु", 
		"गु", 
		"शु", 
		"श"
	], 
	"field-day-relative+1": "कल", 
	"eraAbbr": [
		"ईसापूर्व", 
		"सन"
	], 
	"field-day-relative+2": "परसों", 
	"field-day-relative+3": "नरसों", 
	"dateFormatItem-yyyyMM": "MM-yyyy", 
	"dateFormatItem-yyyyMMMM": "MMMM y", 
	"dateFormat-long": "d MMMM y", 
	"timeFormat-medium": "h:mm:ss a", 
	"field-zone": "क्षेत्र", 
	"dateFormatItem-Hm": "HH:mm", 
	"dateFormat-medium": "dd-MM-yyyy", 
	"dateFormatItem-Hms": "HH:mm:ss", 
	"quarters-standAlone-wide": [
		"तिमाही", 
		"दूसरी तिमाही", 
		"तीसरी तिमाही", 
		"चौथी तिमाही"
	], 
	"dateFormatItem-ms": "mm:ss", 
	"field-year": "वर्ष", 
	"dateFormatItem-yyMMMd": "d MMM, yy", 
	"field-week": "सप्ताह", 
	"months-standAlone-wide": [
		"जनवरी", 
		"फरवरी", 
		"मार्च", 
		"अप्रैल", 
		"मई", 
		"जून", 
		"जुलाई", 
		"अगस्त", 
		"सितम्बर", 
		"अक्तूबर", 
		"नवम्बर", 
		"दिसम्बर"
	], 
	"dateFormatItem-GGGGyMMMMEEEEdd": "EEEE,dd MMMM GGGGy", 
	"dateFormatItem-MMMMEd": "E, d MMMM", 
	"dateFormatItem-MMMd": "d MMM", 
	"dateFormatItem-yyQ": "Q yy", 
	"timeFormat-long": "h:mm:ss a z", 
	"months-format-abbr": [
		"जनवरी", 
		"फरवरी", 
		"मार्च", 
		"अप्रैल", 
		"मई", 
		"जून", 
		"जुलाई", 
		"अगस्त", 
		"सितम्बर", 
		"अक्तूबर", 
		"नवम्बर", 
		"दिसम्बर"
	], 
	"timeFormat-short": "h:mm a", 
	"field-month": "मास", 
	"dateFormatItem-MMMMd": "d MMMM", 
	"quarters-format-abbr": [
		"तिमाही", 
		"दूसरी तिमाही", 
		"तीसरी तिमाही", 
		"चौथी तिमाही"
	], 
	"days-format-abbr": [
		"रवि.", 
		"सोम.", 
		"मंगल.", 
		"बुध.", 
		"बृह.", 
		"शुक्र.", 
		"शनि."
	], 
	"days-format-narrow": [
		"र", 
		"सो", 
		"मं", 
		"बु", 
		"गु", 
		"शु", 
		"श"
	], 
	"field-second": "सेकेंड", 
	"field-day": "दिन", 
	"dateFormatItem-MEd": "E, d/M", 
	"months-format-narrow": [
		"ज", 
		"फ़", 
		"मा", 
		"अ", 
		"म", 
		"जू", 
		"जु", 
		"अ", 
		"सि", 
		"अ", 
		"न", 
		"दि"
	], 
	"days-standAlone-abbr": [
		"रवि.", 
		"सोम.", 
		"मंगल.", 
		"बुध.", 
		"बृह.", 
		"शुक्र.", 
		"शनि."
	], 
	"dateFormat-short": "d-M-yy", 
	"dateFormatItem-yMMMEd": "EEE, d MMM y", 
	"dateFormat-full": "EEEE, d MMMM y", 
	"dateFormatItem-Md": "d/M", 
	"months-format-wide": [
		"जनवरी", 
		"फरवरी", 
		"मार्च", 
		"अप्रैल", 
		"मई", 
		"जून", 
		"जुलाई", 
		"अगस्त", 
		"सितम्बर", 
		"अक्तूबर", 
		"नवम्बर", 
		"दिसम्बर"
	], 
	"dateFormatItem-d": "d", 
	"quarters-format-wide": [
		"तिमाही", 
		"दूसरी तिमाही", 
		"तीसरी तिमाही", 
		"चौथी तिमाही"
	], 
	"days-format-wide": [
		"रविवार", 
		"सोमवार", 
		"मंगलवार", 
		"बुधवार", 
		"बृहस्पतिवार", 
		"शुक्रवार", 
		"शनिवार"
	], 
	"eraNarrow": [
		"ईसापूर्व", 
		"सन"
	]
})