({
	"dateFormatItem-yM": "M/y", 
	"field-dayperiod": "Adduha wala Aluula", 
	"dayPeriods-format-wide-pm": "Aluula", 
	"dateFormatItem-yQ": "'T'Q y", 
	"field-minute": "Miniti", 
	"eraNames": [
		"Isaa jine", 
		"Isaa zamanoo"
	], 
	"dateFormatItem-MMMEd": "E d MMM", 
	"field-day-relative+-1": "Bi", 
	"dateFormatItem-MMdd": "dd/MM", 
	"dateFormatItem-yQQQ": "QQQ y", 
	"field-weekday": "Zaari", 
	"days-standAlone-wide": [
		"Alhadi", 
		"Atinni", 
		"Atalaata", 
		"Alarba", 
		"Alhamiisa", 
		"Alzuma", 
		"Asibti"
	], 
	"dateFormatItem-MMM": "MMM", 
	"months-standAlone-narrow": [
		"Ž", 
		"F", 
		"M", 
		"A", 
		"M", 
		"Ž", 
		"Ž", 
		"U", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"dayPeriods-format-wide-am": "Adduha", 
	"field-era": "Zaman", 
	"field-hour": "Guuru", 
	"quarters-standAlone-abbr": [
		"A1", 
		"A2", 
		"A3", 
		"A4"
	], 
	"dateFormatItem-y": "y", 
	"dateFormatItem-yyMMMEEEd": "EEE d MMM yy", 
	"dateFormatItem-MMMdd": "dd MMM", 
	"timeFormat-full": "HH:mm:ss zzzz", 
	"dateFormatItem-Med": "EEE d/M", 
	"months-standAlone-abbr": [
		"Žan", 
		"Fee", 
		"Mar", 
		"Awi", 
		"Me", 
		"Žuw", 
		"Žuy", 
		"Ut", 
		"Sek", 
		"Okt", 
		"Noo", 
		"Dee"
	], 
	"dateFormatItem-yMMM": "MMM y", 
	"field-day-relative+0": "Hõo", 
	"days-standAlone-narrow": [
		"H", 
		"T", 
		"T", 
		"L", 
		"L", 
		"L", 
		"S"
	], 
	"field-day-relative+1": "Suba", 
	"eraAbbr": [
		"IJ", 
		"IZ"
	], 
	"dateFormatItem-yyyyMMMM": "MMMM yyyy", 
	"dateFormat-long": "d MMMM y", 
	"timeFormat-medium": "HH:mm:ss", 
	"field-zone": "Leerazuu", 
	"dateFormatItem-MMd": "d/MM", 
	"dateFormat-medium": "d MMM, y", 
	"dateFormatItem-yyMM": "MM/yy", 
	"dateFormatItem-yyMMM": "MMM yy", 
	"quarters-standAlone-wide": [
		"Arrubu 1", 
		"Arrubu 2", 
		"Arrubu 3", 
		"Arrubu 4"
	], 
	"dateFormatItem-yMMMM": "MMMM y", 
	"dateFormatItem-ms": "m:ss", 
	"field-year": "Jiiri", 
	"dateFormatItem-yyMMMd": "d MMM yy", 
	"field-week": "Hebu", 
	"months-standAlone-wide": [
		"Žanwiye", 
		"Feewiriye", 
		"Marsi", 
		"Awiril", 
		"Me", 
		"Žuweŋ", 
		"Žuyye", 
		"Ut", 
		"Sektanbur", 
		"Oktoobur", 
		"Noowanbur", 
		"Deesanbur"
	], 
	"dateFormatItem-MMMMEd": "EEE d MMMM", 
	"dateFormatItem-MMMd": "d MMM", 
	"timeFormat-long": "HH:mm:ss z", 
	"months-format-abbr": [
		"Žan", 
		"Fee", 
		"Mar", 
		"Awi", 
		"Me", 
		"Žuw", 
		"Žuy", 
		"Ut", 
		"Sek", 
		"Okt", 
		"Noo", 
		"Dee"
	], 
	"timeFormat-short": "HH:mm", 
	"field-month": "Handu", 
	"dateFormatItem-MMMMd": "d MMMM", 
	"quarters-format-abbr": [
		"A1", 
		"A2", 
		"A3", 
		"A4"
	], 
	"days-format-abbr": [
		"Alh", 
		"Ati", 
		"Ata", 
		"Ala", 
		"Alm", 
		"Alz", 
		"Asi"
	], 
	"dateFormatItem-M": "M", 
	"days-format-narrow": [
		"H", 
		"T", 
		"T", 
		"L", 
		"L", 
		"L", 
		"S"
	], 
	"field-second": "Miti", 
	"field-day": "Zaari", 
	"months-format-narrow": [
		"Ž", 
		"F", 
		"M", 
		"A", 
		"M", 
		"Ž", 
		"Ž", 
		"U", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"days-standAlone-abbr": [
		"Alh", 
		"Ati", 
		"Ata", 
		"Ala", 
		"Alm", 
		"Alz", 
		"Asi"
	], 
	"dateFormat-short": "d/M/yyyy", 
	"dateFormatItem-yMMMEd": "EEE d MMM y", 
	"dateFormat-full": "EEEE d MMMM y", 
	"dateFormatItem-Md": "d/M", 
	"dateFormatItem-yMEd": "EEE d/M/y", 
	"months-format-wide": [
		"Žanwiye", 
		"Feewiriye", 
		"Marsi", 
		"Awiril", 
		"Me", 
		"Žuweŋ", 
		"Žuyye", 
		"Ut", 
		"Sektanbur", 
		"Oktoobur", 
		"Noowanbur", 
		"Deesanbur"
	], 
	"quarters-format-wide": [
		"Arrubu 1", 
		"Arrubu 2", 
		"Arrubu 3", 
		"Arrubu 4"
	], 
	"days-format-wide": [
		"Alhadi", 
		"Atinni", 
		"Atalaata", 
		"Alarba", 
		"Alhamiisa", 
		"Alzuma", 
		"Asibti"
	], 
	"eraNarrow": [
		"IJ", 
		"IZ"
	]
})