({
	"dateFormat-medium": "dd-MM-yyyy", 
	"dateFormatItem-MMMEd": "E, d MMM", 
	"dateFormatItem-MEd": "E, d/M", 
	"timeFormat-full": "h:mm:ss a zzzz", 
	"dateFormatItem-Md": "d/M", 
	"months-standAlone-wide": [
		"मुहर्रम", 
		"सफर", 
		"राबी प्रथम", 
		"राबी द्वितीय", 
		"जुम्डा प्रथम", 
		"जुम्डा द्वितीय", 
		"रजब", 
		"शावन", 
		"रमजान", 
		"शव्व्ल"
	], 
	"days-standAlone-narrow": [
		"र", 
		"सो", 
		"मं", 
		"बु", 
		"गु", 
		"शु", 
		"श"
	], 
	"dayPeriods-format-wide-pm": "अपराह्न", 
	"months-standAlone-abbr": [
		"मुहर्रम", 
		"सफर", 
		"राबी प्रथम", 
		"राबी द्वितीय", 
		"जुम्डा प्रथम", 
		"जुम्डा द्वितीय", 
		"रजब", 
		"शावन", 
		"रमजान", 
		"शव्व्ल"
	], 
	"dayPeriods-format-wide-am": "पूर्वाह्न", 
	"timeFormat-medium": "h:mm:ss a", 
	"dateFormat-long": "d MMMM y", 
	"dateFormat-short": "d-M-yy", 
	"dateFormatItem-yMMMEd": "EEE, d MMM y", 
	"months-format-wide": [
		"मुहर्रम", 
		"सफर", 
		"राबी प्रथम", 
		"राबी द्वितीय", 
		"जुम्डा प्रथम", 
		"जुम्डा द्वितीय", 
		"रजब", 
		"शावन", 
		"रमजान", 
		"शव्व्ल"
	], 
	"dateFormatItem-yM": "M-y", 
	"timeFormat-short": "h:mm a", 
	"months-format-abbr": [
		"मुहर्रम", 
		"सफर", 
		"राबी प्रथम", 
		"राबी द्वितीय", 
		"जुम्डा प्रथम", 
		"जुम्डा द्वितीय", 
		"रजब", 
		"शावन", 
		"रमजान", 
		"शव्व्ल"
	], 
	"timeFormat-long": "h:mm:ss a z", 
	"days-format-wide": [
		"रविवार", 
		"सोमवार", 
		"मंगलवार", 
		"बुधवार", 
		"बृहस्पतिवार", 
		"शुक्रवार", 
		"शनिवार"
	], 
	"dateFormatItem-yMMM": "MMM y", 
	"quarters-format-wide": [
		"तिमाही", 
		"दूसरी तिमाही", 
		"तीसरी तिमाही", 
		"चौथी तिमाही"
	], 
	"dateFormat-full": "EEEE, d MMMM y", 
	"dateFormatItem-MMMd": "d MMM", 
	"days-format-abbr": [
		"रवि.", 
		"सोम.", 
		"मंगल.", 
		"बुध.", 
		"बृह.", 
		"शुक्र.", 
		"शनि."
	]
})