({
	"dateFormatItem-yM": "M/y", 
	"field-dayperiod": "Ŋkɛkɛ", 
	"dayPeriods-format-wide-pm": "EW", 
	"dateFormatItem-yQ": "Q y", 
	"field-minute": "Mintigaƒoƒo", 
	"eraNames": [
		"Hafi Yesu Va Do ŋgɔ", 
		"Yesu Ŋɔli"
	], 
	"dateFormatItem-MMMEd": "E, MMM d", 
	"field-day-relative+-1": "Nyitsɔ", 
	"dateFormatItem-yQQQ": "QQQ y", 
	"field-weekday": "Ŋkɛkɛ", 
	"days-standAlone-wide": [
		"Kɔsiɖa", 
		"Dzoɖa", 
		"Braɖa", 
		"Kuɖa", 
		"Yawoɖa", 
		"Fiɖa", 
		"Memleɖa"
	], 
	"dateFormatItem-MMM": "LLL", 
	"months-standAlone-narrow": [
		"D", 
		"D", 
		"T", 
		"A", 
		"D", 
		"M", 
		"S", 
		"D", 
		"A", 
		"K", 
		"A", 
		"D"
	], 
	"dayPeriods-format-wide-am": "AN", 
	"field-era": "Ɛra", 
	"field-hour": "Gaƒoƒo", 
	"dateFormatItem-y": "y", 
	"timeFormat-full": "h:mm:ss a zzzz", 
	"months-standAlone-abbr": [
		"Dzv", 
		"Dzd", 
		"Ted", 
		"Afɔ", 
		"Dam", 
		"Mas", 
		"Sia", 
		"Dea", 
		"Any", 
		"Kel", 
		"Ade", 
		"Dzm"
	], 
	"dateFormatItem-yMMM": "MMM y", 
	"field-day-relative+0": "Egbe", 
	"days-standAlone-narrow": [
		"K", 
		"D", 
		"B", 
		"K", 
		"Y", 
		"F", 
		"M"
	], 
	"field-day-relative+1": "Etsɔ", 
	"eraAbbr": [
		"HY", 
		"YŊ"
	], 
	"dateFormat-long": "d MMMM y", 
	"timeFormat-medium": "h:mm:ss a", 
	"field-zone": "Gamɛ", 
	"dateFormatItem-Hm": "HH:mm", 
	"dateFormat-medium": "d MMM y", 
	"dateFormatItem-Hms": "HH:mm:ss", 
	"dateFormatItem-yMMMM": "MMMM y", 
	"dateFormatItem-ms": "mm:ss", 
	"field-year": "Efe", 
	"field-week": "Kwasida deka", 
	"months-standAlone-wide": [
		"Dzove", 
		"Dzodze", 
		"Tedoxe", 
		"Afɔfiɛ", 
		"Dama", 
		"Masa", 
		"Siamlɔm", 
		"Deasiamime", 
		"Anyɔnyɔ", 
		"Kele", 
		"Adeɛmekpɔxe", 
		"Dzome"
	], 
	"dateFormatItem-MMMMEd": "E, MMMM d", 
	"dateFormatItem-MMMd": "MMM d", 
	"timeFormat-long": "h:mm:ss a z", 
	"months-format-abbr": [
		"Dzv", 
		"Dzd", 
		"Ted", 
		"Afɔ", 
		"Dam", 
		"Mas", 
		"Sia", 
		"Dea", 
		"Any", 
		"Kel", 
		"Ade", 
		"Dzm"
	], 
	"timeFormat-short": "h:mm a", 
	"field-month": "Xleti", 
	"dateFormatItem-MMMMd": "MMMM d", 
	"days-format-abbr": [
		"Kɔs Kwe", 
		"Dzo", 
		"Bra", 
		"Kuɖ", 
		"Yaw", 
		"Fiɖ", 
		"Mem"
	], 
	"dateFormatItem-M": "L", 
	"days-format-narrow": [
		"K", 
		"D", 
		"B", 
		"K", 
		"Y", 
		"F", 
		"M"
	], 
	"field-second": "Sekondgaƒoƒo", 
	"field-day": "Ŋkɛkɛ", 
	"dateFormatItem-MEd": "E, M/d", 
	"months-format-narrow": [
		"D", 
		"D", 
		"T", 
		"A", 
		"D", 
		"M", 
		"S", 
		"D", 
		"A", 
		"K", 
		"A", 
		"D"
	], 
	"dateFormatItem-hm": "h:mm a", 
	"days-standAlone-abbr": [
		"Kɔs Kwe", 
		"Dzo", 
		"Bra", 
		"Kuɖ", 
		"Yaw", 
		"Fiɖ", 
		"Mem"
	], 
	"dateFormat-short": "dd/MM/yyyy", 
	"dateFormatItem-yMMMEd": "EEE, MMM d, y", 
	"dateFormat-full": "EEEE, d MMMM y", 
	"dateFormatItem-Md": "M/d", 
	"dateFormatItem-yMEd": "EEE, M/d/y", 
	"months-format-wide": [
		"Dzove", 
		"Dzodze", 
		"Tedoxe", 
		"Afɔfiɛ", 
		"Dama", 
		"Masa", 
		"Siamlɔm", 
		"Deasiamime", 
		"Anyɔnyɔ", 
		"Kele", 
		"Adeɛmekpɔxe", 
		"Dzome"
	], 
	"dateFormatItem-d": "d", 
	"days-format-wide": [
		"Kɔsiɖa", 
		"Dzoɖa", 
		"Braɖa", 
		"Kuɖa", 
		"Yawoɖa", 
		"Fiɖa", 
		"Memleɖa"
	], 
	"eraNarrow": [
		"HY", 
		"YŊ"
	]
})