({
	"dateFormatItem-yM": "y-M", 
	"field-dayperiod": "претпладне/попладне", 
	"dayPeriods-format-wide-pm": "попладне", 
	"dateFormatItem-yQ": "y Q", 
	"field-minute": "Минута", 
	"dateFormatItem-MMMEd": "E MMM d", 
	"eraNames": [
		"пр.н.е.", 
		"ае."
	], 
	"field-day-relative+-1": "Вчера", 
	"dateFormatItem-hms": "h:mm:ss a", 
	"dateFormatItem-yQQQ": "y QQQ", 
	"field-day-relative+-2": "завчера", 
	"field-weekday": "Ден во неделата", 
	"field-day-relative+-3": "пред три дена", 
	"days-standAlone-wide": [
		"недела", 
		"понеделник", 
		"вторник", 
		"среда", 
		"четврток", 
		"петок", 
		"сабота"
	], 
	"dateFormatItem-MMM": "LLL", 
	"months-standAlone-narrow": [
		"ј", 
		"ф", 
		"м", 
		"а", 
		"м", 
		"ј", 
		"ј", 
		"а", 
		"с", 
		"о", 
		"н", 
		"д"
	], 
	"dayPeriods-format-wide-am": "претпладне", 
	"field-era": "Ера", 
	"field-hour": "Час", 
	"quarters-standAlone-abbr": [
		"јан-мар", 
		"апр-јун", 
		"јул-сеп", 
		"окт-дек"
	], 
	"dateFormatItem-y": "y", 
	"months-standAlone-abbr": [
		"јан.", 
		"фев.", 
		"мар.", 
		"апр.", 
		"мај", 
		"јун.", 
		"јул.", 
		"авг.", 
		"септ.", 
		"окт.", 
		"ноем.", 
		"декем."
	], 
	"dateFormatItem-yMMM": "y MMM", 
	"field-day-relative+0": "Денес", 
	"days-standAlone-narrow": [
		"н", 
		"п", 
		"в", 
		"с", 
		"ч", 
		"п", 
		"с"
	], 
	"field-day-relative+1": "Утре", 
	"eraAbbr": [
		"пр.н.е.", 
		"ае."
	], 
	"field-day-relative+2": "задутре", 
	"field-day-relative+3": "по три дена", 
	"dateFormatItem-yyyyMMMM": "MMMM y", 
	"dateFormat-long": "dd MMMM y", 
	"dateFormatItem-EEEd": "d EEE", 
	"field-zone": "зона", 
	"dateFormatItem-Hm": "HH:mm", 
	"dateFormat-medium": "dd.M.yyyy", 
	"dateFormatItem-Hms": "HH:mm:ss", 
	"quarters-standAlone-wide": [
		"прво тромесечје", 
		"второ тромесечје", 
		"трето тромесечје", 
		"четврто тромесечје"
	], 
	"dateFormatItem-yMMMM": "y MMMM", 
	"dateFormatItem-ms": "mm:ss", 
	"field-year": "година", 
	"field-week": "Недела", 
	"months-standAlone-wide": [
		"јануари", 
		"февруари", 
		"март", 
		"април", 
		"мај", 
		"јуни", 
		"јули", 
		"август", 
		"септември", 
		"октомври", 
		"ноември", 
		"декември"
	], 
	"dateFormatItem-MMMMEd": "E MMMM d", 
	"dateFormatItem-MMMd": "MMM d", 
	"dateFormatItem-yyQ": "Q yy", 
	"months-format-abbr": [
		"јан.", 
		"фев.", 
		"мар.", 
		"апр.", 
		"мај", 
		"јун.", 
		"јул.", 
		"авг.", 
		"септ.", 
		"окт.", 
		"ноем.", 
		"декем."
	], 
	"field-month": "Месец", 
	"dateFormatItem-MMMMd": "MMMM d", 
	"quarters-format-abbr": [
		"Q1", 
		"Q2", 
		"Q3", 
		"Q4"
	], 
	"days-format-abbr": [
		"нед.", 
		"пон.", 
		"вт.", 
		"сре.", 
		"чет.", 
		"пет.", 
		"саб."
	], 
	"dateFormatItem-MMMMdd": "dd MMMM", 
	"dateFormatItem-M": "L", 
	"days-format-narrow": [
		"н", 
		"п", 
		"в", 
		"с", 
		"ч", 
		"п", 
		"с"
	], 
	"field-second": "Секунда", 
	"field-day": "ден", 
	"dateFormatItem-MEd": "E, M-d", 
	"months-format-narrow": [
		"ј", 
		"ф", 
		"м", 
		"а", 
		"м", 
		"ј", 
		"ј", 
		"а", 
		"с", 
		"о", 
		"н", 
		"д"
	], 
	"dateFormatItem-hm": "h:mm a", 
	"days-standAlone-abbr": [
		"нед.", 
		"пон.", 
		"вт.", 
		"сре.", 
		"чет.", 
		"пет.", 
		"саб."
	], 
	"dateFormat-short": "dd.M.yy", 
	"dateFormatItem-Mdd": "dd.M", 
	"dateFormatItem-yyyyM": "M.yyyy", 
	"dateFormatItem-yMMMEd": "EEE, y MMM d", 
	"dateFormat-full": "EEEE, dd MMMM y", 
	"dateFormatItem-Md": "M-d", 
	"dateFormatItem-yMEd": "EEE, y-M-d", 
	"months-format-wide": [
		"јануари", 
		"февруари", 
		"март", 
		"април", 
		"мај", 
		"јуни", 
		"јули", 
		"август", 
		"септември", 
		"октомври", 
		"ноември", 
		"декември"
	], 
	"dateFormatItem-d": "d", 
	"quarters-format-wide": [
		"прво тромесечје", 
		"второ тромесечје", 
		"трето тромесечје", 
		"четврто тромесечје"
	], 
	"days-format-wide": [
		"недела", 
		"понеделник", 
		"вторник", 
		"среда", 
		"четврток", 
		"петок", 
		"сабота"
	], 
	"eraNarrow": [
		"пр.н.е.", 
		"ае."
	]
})