({
	"months-format-narrow": [
		"ژ", 
		"ف", 
		"م", 
		"آ", 
		"می", 
		"ژ", 
		"ژ", 
		"ا", 
		"س", 
		"ا", 
		"ن", 
		"د"
	], 
	"quarters-standAlone-narrow": [
		"۱", 
		"۲", 
		"۳", 
		"۴"
	], 
	"field-weekday": "روز هفته", 
	"dateFormatItem-yQQQ": "y QQQ", 
	"dateFormatItem-yMEd": "E yyyy/M/d", 
	"dateFormatItem-MMMEd": "E d LLL", 
	"eraNarrow": [
		"ق", 
		"م"
	], 
	"dateTimeFormats-appendItem-Day-Of-Week": "{1} {0}", 
	"dateFormat-long": "MMMM d, y", 
	"months-format-wide": [
		"ژانویهٔ", 
		"فوریهٔ", 
		"مارس", 
		"آوریل", 
		"می", 
		"جون", 
		"جولای", 
		"آگوست", 
		"سپتامبر", 
		"اکتبر", 
		"نوامبر", 
		"دسامبر"
	], 
	"dateTimeFormat-medium": "{1}،‏ {0}", 
	"dateFormatItem-EEEd": "EEE d", 
	"dayPeriods-format-wide-pm": "بعد از ظهر", 
	"dateFormat-full": "EEEE, MMMM d, y", 
	"dateFormatItem-Md": "M/d", 
	"field-era": "دوره", 
	"dateFormatItem-yM": "yyyy/M", 
	"months-standAlone-wide": [
		"ژانویه", 
		"فوریه", 
		"مارس", 
		"آوریل", 
		"مه", 
		"ژوئن", 
		"ژوئیه", 
		"اوت", 
		"سپتامبر", 
		"اکتبر", 
		"نوامبر", 
		"دسامبر"
	], 
	"timeFormat-short": "H:mm", 
	"quarters-format-wide": [
		"سهماههٔ اول", 
		"سهماههٔ دوم", 
		"سهماههٔ سوم", 
		"سهماههٔ چهارم"
	], 
	"timeFormat-long": "H:mm:ss (z)", 
	"field-year": "سال", 
	"dateFormatItem-yMMM": "MMM y", 
	"dateFormatItem-yQ": "yyyy Q", 
	"dateFormatItem-yyyyMMMM": "MMMM y", 
	"field-hour": "ساعت", 
	"months-format-abbr": [
		"ژانویهٔ", 
		"فوریهٔ", 
		"مارس", 
		"آوریل", 
		"می", 
		"جون", 
		"جولای", 
		"اوت", 
		"سپتامبر", 
		"اکتبر", 
		"نوامبر", 
		"دسامبر"
	], 
	"timeFormat-full": "H:mm:ss (zzzz)", 
	"dateFormatItem-GGGGyyyyMMMMd": "d MMMM y GGGG", 
	"field-day-relative+0": "امروز", 
	"field-day-relative+1": "فردا", 
	"field-day-relative+2": "پسفردا", 
	"dateFormatItem-H": "H", 
	"field-day-relative+3": "سه روز بعد", 
	"months-standAlone-abbr": [
		"ژانویهٔ", 
		"فوریهٔ", 
		"مارس", 
		"آوریل", 
		"می", 
		"جون", 
		"جولای", 
		"اوت", 
		"سپتامبر", 
		"اکتبر", 
		"نوامبر", 
		"دسامبر"
	], 
	"quarters-format-abbr": [
		"سم۱", 
		"سم۲", 
		"سم۳", 
		"سم۴"
	], 
	"quarters-standAlone-wide": [
		"سهماههٔ اول", 
		"سهماههٔ دوم", 
		"سهماههٔ سوم", 
		"سهماههٔ چهارم"
	], 
	"dateFormatItem-M": "L", 
	"days-standAlone-wide": [
		"یکشنبه", 
		"دوشنبه", 
		"سهشنبه", 
		"چهارشنبه", 
		"پنجشنبه", 
		"جمعه", 
		"شنبه"
	], 
	"dateFormatItem-MMMMd": "d LLLL", 
	"timeFormat-medium": "H:mm:ss", 
	"dateFormatItem-Hm": "H:mm", 
	"quarters-standAlone-abbr": [
		"سم۱", 
		"سم۲", 
		"سم۳", 
		"سم۴"
	], 
	"eraAbbr": [
		"ق.م.", 
		"ب. م."
	], 
	"field-minute": "دقیقه", 
	"field-dayperiod": "قبل/بعد از ظهر", 
	"days-standAlone-abbr": [
		"یکشنبه", 
		"دوشنبه", 
		"سهشنبه", 
		"چهارشنبه", 
		"پنجشنبه", 
		"جمعه", 
		"شنبه"
	], 
	"dateFormatItem-d": "d", 
	"dateFormatItem-ms": "mm:ss", 
	"quarters-format-narrow": [
		"۱", 
		"۲", 
		"۳", 
		"۴"
	], 
	"field-day-relative+-1": "دیروز", 
	"dateTimeFormat-long": "{1}، ساعت {0}", 
	"field-day-relative+-2": "پریروز", 
	"field-day-relative+-3": "سه روز پیش", 
	"dateFormatItem-MMMd": "d LLL", 
	"dateFormatItem-MEd": "E M/d", 
	"dateTimeFormat-full": "{1}، ساعت {0}", 
	"dateFormatItem-yMMMM": "MMMM y", 
	"field-day": "روز", 
	"days-format-wide": [
		"یکشنبه", 
		"دوشنبه", 
		"سهشنبه", 
		"چهارشنبه", 
		"پنجشنبه", 
		"جمعه", 
		"شنبه"
	], 
	"field-zone": "منطقهٔ زمانی", 
	"dateFormatItem-y": "y", 
	"months-standAlone-narrow": [
		"ژ", 
		"ف", 
		"م", 
		"آ", 
		"می", 
		"ژ", 
		"ژ", 
		"ا", 
		"س", 
		"ا", 
		"ن", 
		"د"
	], 
	"days-format-abbr": [
		"یکشنبه", 
		"دوشنبه", 
		"سهشنبه", 
		"چهارشنبه", 
		"پنجشنبه", 
		"جمعه", 
		"شنبه"
	], 
	"eraNames": [
		"قبل از میلاد", 
		"میلادی"
	], 
	"days-format-narrow": [
		"ی", 
		"د", 
		"س", 
		"چ", 
		"پ", 
		"ج", 
		"ش"
	], 
	"field-month": "ماه", 
	"dateFormatItem-HHmmZ": "HH:mm (Z)", 
	"days-standAlone-narrow": [
		"ی", 
		"د", 
		"س", 
		"چ", 
		"پ", 
		"ج", 
		"ش"
	], 
	"dateFormatItem-MMM": "LLL", 
	"dayPeriods-format-wide-am": "قبل از ظهر", 
	"dateFormatItem-MMMMEd": "E d LLLL", 
	"dateFormat-short": "M/d/yy", 
	"dateFormatItem-yyyyMMMMEEEEd": "EEEE d MMMM y", 
	"field-second": "ثانیه", 
	"dateFormatItem-yMMMEd": "E d MMM y", 
	"field-week": "هفته", 
	"dateFormat-medium": "MMM d, y", 
	"dateFormatItem-yyyyM": "yyyy/M", 
	"dateFormatItem-mmss": "mm:ss", 
	"dateTimeFormat-short": "{1}،‏ {0}", 
	"dateFormatItem-Hms": "H:mm:ss"
})