({
	"dateFormatItem-yM": "yyyy/M", 
	"dateFormatItem-yQ": "yyyy Q", 
	"dayPeriods-format-wide-pm": "بعد از ظهر", 
	"dateFormatItem-MMMEd": "E d LLL", 
	"dateTimeFormat-full": "{1}، ساعت {0}", 
	"months-standAlone-narrow": [
		"ت", 
		"ح", 
		"ک", 
		"ط", 
		"ش", 
		"آ", 
		"و", 
		"ن", 
		"ا", 
		"س", 
		"ت", 
		"آ", 
		"ا"
	], 
	"dateTimeFormat-short": "{1}،‏ {0}", 
	"dayPeriods-format-wide-am": "قبل از ظهر", 
	"dateTimeFormat-medium": "{1}،‏ {0}", 
	"timeFormat-full": "H:mm:ss (zzzz)", 
	"months-standAlone-narrow-leap": "و", 
	"months-standAlone-abbr": [
		"تشری", 
		"حشوان", 
		"کسلو", 
		"طوت", 
		"شباط", 
		"آذار", 
		"واذار", 
		"نیسان", 
		"ایار", 
		"سیوان", 
		"تموز", 
		"آب", 
		"ایلول"
	], 
	"dateFormatItem-yMMM": "MMM y", 
	"days-standAlone-narrow": [
		"ی", 
		"د", 
		"س", 
		"چ", 
		"پ", 
		"ج", 
		"ش"
	], 
	"dateFormat-long": "MMMM d, y", 
	"timeFormat-medium": "H:mm:ss", 
	"dateFormatItem-EEEd": "EEE d", 
	"dateFormatItem-Hm": "H:mm", 
	"dateFormat-medium": "MMM d, y", 
	"dateFormatItem-Hms": "H:mm:ss", 
	"quarters-standAlone-narrow": [
		"۱", 
		"۲", 
		"۳", 
		"۴"
	], 
	"dateTimeFormat-long": "{1}، ساعت {0}", 
	"months-standAlone-wide": [
		"تشری", 
		"حشوان", 
		"کسلو", 
		"طوت", 
		"شباط", 
		"آذار", 
		"واذار", 
		"نیسان", 
		"ایار", 
		"سیوان", 
		"تموز", 
		"آب", 
		"ایلول"
	], 
	"dateFormatItem-MMMd": "d LLL", 
	"timeFormat-long": "H:mm:ss (z)", 
	"months-format-abbr": [
		"تشری", 
		"حشوان", 
		"کسلو", 
		"طوت", 
		"شباط", 
		"آذار", 
		"واذار", 
		"نیسان", 
		"ایار", 
		"سیوان", 
		"تموز", 
		"آب", 
		"ایلول"
	], 
	"timeFormat-short": "H:mm", 
	"dateFormatItem-H": "H", 
	"quarters-format-abbr": [
		"سم۱", 
		"سم۲", 
		"سم۳", 
		"سم۴"
	], 
	"dateFormatItem-MEd": "E M/d", 
	"dateTimeFormats-appendItem-Day-Of-Week": "{1} {0}", 
	"months-format-narrow": [
		"ت", 
		"ح", 
		"ک", 
		"ط", 
		"ش", 
		"آ", 
		"و", 
		"ن", 
		"ا", 
		"س", 
		"ت", 
		"آ", 
		"ا"
	], 
	"dateFormat-short": "M/d/yy", 
	"dateFormatItem-yMMMEd": "E d MMM y", 
	"dateFormat-full": "EEEE, MMMM d, y", 
	"dateFormatItem-Md": "M/d", 
	"dateFormatItem-yMEd": "E yyyy/M/d", 
	"months-format-wide": [
		"تشری", 
		"حشوان", 
		"کسلو", 
		"طوت", 
		"شباط", 
		"آذار", 
		"واذار", 
		"نیسان", 
		"ایار", 
		"سیوان", 
		"تموز", 
		"آب", 
		"ایلول"
	], 
	"quarters-format-wide": [
		"سهماههٔ اول", 
		"سهماههٔ دوم", 
		"سهماههٔ سوم", 
		"سهماههٔ چهارم"
	], 
	"months-format-wide-leap": "واذار الثانی", 
	"days-format-wide": [
		"یکشنبه", 
		"دوشنبه", 
		"سهشنبه", 
		"چهارشنبه", 
		"پنجشنبه", 
		"جمعه", 
		"شنبه"
	]
})