({
	"dateFormatItem-yM": "MM/y", 
	"dateFormatItem-yQ": "y Q", 
	"field-minute": "Minuto", 
	"eraNames": [
		"Antes de Cristo", 
		"Anno Domini"
	], 
	"dateFormatItem-MMMEd": "EEE, d MMM", 
	"field-day-relative+-1": "Zuro", 
	"dateFormatItem-MMdd": "dd/MM", 
	"dateFormatItem-yQQQ": "y QQQ", 
	"field-weekday": "Ntsiku", 
	"days-standAlone-wide": [
		"Dimingu", 
		"Chiposi", 
		"Chipiri", 
		"Chitatu", 
		"Chinai", 
		"Chishanu", 
		"Sabudu"
	], 
	"dateFormatItem-MMM": "LLL", 
	"months-standAlone-narrow": [
		"J", 
		"F", 
		"M", 
		"A", 
		"M", 
		"J", 
		"J", 
		"A", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"field-hour": "Hora", 
	"dateFormatItem-y": "y", 
	"dateFormatItem-yyMMMEEEd": "EEE, d 'de' MMM 'de' yy", 
	"timeFormat-full": "HH:mm:ss zzzz", 
	"months-standAlone-abbr": [
		"Jan", 
		"Fev", 
		"Mar", 
		"Abr", 
		"Mai", 
		"Jun", 
		"Jul", 
		"Aug", 
		"Set", 
		"Otu", 
		"Nov", 
		"Dec"
	], 
	"dateFormatItem-yMMM": "MMM 'de' y", 
	"field-day-relative+0": "Lero", 
	"days-standAlone-narrow": [
		"D", 
		"P", 
		"C", 
		"T", 
		"N", 
		"S", 
		"S"
	], 
	"field-day-relative+1": "Manguana", 
	"eraAbbr": [
		"AC", 
		"AD"
	], 
	"dateFormat-long": "d 'de' MMMM 'de' y", 
	"timeFormat-medium": "HH:mm:ss", 
	"dateFormatItem-Hm": "H:mm", 
	"dateFormat-medium": "d 'de' MMM 'de' y", 
	"dateFormatItem-yyMM": "MM/yy", 
	"dateFormatItem-yyMMM": "MMM yy", 
	"dateFormatItem-yMMMM": "MMMM 'de' y", 
	"dateFormatItem-ms": "mm:ss", 
	"field-year": "Chaka", 
	"dateFormatItem-HHmmss": "HH:mm:ss", 
	"dateFormatItem-yyMMMd": "d 'de' MMM 'de' yy", 
	"months-standAlone-wide": [
		"Janeiro", 
		"Fevreiro", 
		"Marco", 
		"Abril", 
		"Maio", 
		"Junho", 
		"Julho", 
		"Augusto", 
		"Setembro", 
		"Otubro", 
		"Novembro", 
		"Decembro"
	], 
	"dateFormatItem-MMMMEd": "EEE, d MMMM", 
	"dateFormatItem-MMMd": "d MMM", 
	"dateFormatItem-HHmm": "HH:mm", 
	"dateFormatItem-yyQ": "Q yy", 
	"timeFormat-long": "HH:mm:ss z", 
	"months-format-abbr": [
		"Jan", 
		"Fev", 
		"Mar", 
		"Abr", 
		"Mai", 
		"Jun", 
		"Jul", 
		"Aug", 
		"Set", 
		"Otu", 
		"Nov", 
		"Dec"
	], 
	"timeFormat-short": "HH:mm", 
	"field-month": "Mwezi", 
	"dateFormatItem-MMMMd": "d MMMM", 
	"days-format-abbr": [
		"Dim", 
		"Pos", 
		"Pir", 
		"Tat", 
		"Nai", 
		"Sha", 
		"Sab"
	], 
	"dateFormatItem-mmss": "mm:ss", 
	"dateFormatItem-M": "L", 
	"days-format-narrow": [
		"D", 
		"P", 
		"C", 
		"T", 
		"N", 
		"S", 
		"S"
	], 
	"field-second": "Segundo", 
	"field-day": "Ntsiku", 
	"dateFormatItem-MEd": "dd/MM", 
	"months-format-narrow": [
		"J", 
		"F", 
		"M", 
		"A", 
		"M", 
		"J", 
		"J", 
		"A", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"days-standAlone-abbr": [
		"Dim", 
		"Pos", 
		"Pir", 
		"Tat", 
		"Nai", 
		"Sha", 
		"Sab"
	], 
	"dateFormat-short": "d/M/yyyy", 
	"dateFormatItem-yMMMEd": "EEE, d 'de' MMM 'de' y", 
	"dateFormat-full": "EEEE, d 'de' MMMM 'de' y", 
	"dateFormatItem-Md": "d/M", 
	"dateFormatItem-yMEd": "EEE, dd/MM/y", 
	"months-format-wide": [
		"Janeiro", 
		"Fevreiro", 
		"Marco", 
		"Abril", 
		"Maio", 
		"Junho", 
		"Julho", 
		"Augusto", 
		"Setembro", 
		"Otubro", 
		"Novembro", 
		"Decembro"
	], 
	"dateFormatItem-d": "d", 
	"days-format-wide": [
		"Dimingu", 
		"Chiposi", 
		"Chipiri", 
		"Chitatu", 
		"Chinai", 
		"Chishanu", 
		"Sabudu"
	], 
	"eraNarrow": [
		"AC", 
		"AD"
	]
})