// generated from ldml/main/*.xml, xpath: ldml/calendars/calendar-ethiopic
({
	'months-format-abbr@localeAlias85':{'target':"months-format-wide",'bundle':"ethiopic"},
	'months-format-abbr':["Meskerem","Tekemt","Hedar","Tahsas","Ter","Yekatit","Megabit","Miazia","Genbot","Sene","Hamle","Nehasse","Pagumen"],
	'months-format-narrow@localeAlias86':{'target':"months-standAlone-narrow",'bundle':"ethiopic"},
	'months-format-narrow':["1","2","3","4","5","6","7","8","9","10","11","12","13"],
	'months-format-wide':["Meskerem","Tekemt","Hedar","Tahsas","Ter","Yekatit","Megabit","Miazia","Genbot","Sene","Hamle","Nehasse","Pagumen"],
	'months-standAlone-abbr@localeAlias87':{'target':"months-format-abbr",'bundle':"ethiopic"},
	'months-standAlone-abbr@localeAlias88':{'target':"months-format-wide",'bundle':"ethiopic"},
	'months-standAlone-abbr':["Meskerem","Tekemt","Hedar","Tahsas","Ter","Yekatit","Megabit","Miazia","Genbot","Sene","Hamle","Nehasse","Pagumen"],
	'months-standAlone-narrow':["1","2","3","4","5","6","7","8","9","10","11","12","13"],
	'months-standAlone-wide@localeAlias89':{'target':"months-format-wide",'bundle':"ethiopic"},
	'months-standAlone-wide':["Meskerem","Tekemt","Hedar","Tahsas","Ter","Yekatit","Megabit","Miazia","Genbot","Sene","Hamle","Nehasse","Pagumen"],
	'days@localeAlias90':{'target':"days", 'bundle':"gregorian"},
	'days-format-abbr@localeAlias91':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-format-abbr':["1","2","3","4","5","6","7"],
	'days-format-narrow@localeAlias92':{'target':"days-standAlone-narrow",'bundle':"gregorian"},
	'days-format-narrow':["1","2","3","4","5","6","7"],
	'days-format-wide':["1","2","3","4","5","6","7"],
	'days-standAlone-abbr@localeAlias93':{'target':"days-format-abbr",'bundle':"gregorian"},
	'days-standAlone-abbr@localeAlias94':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-standAlone-abbr':["1","2","3","4","5","6","7"],
	'days-standAlone-narrow':["1","2","3","4","5","6","7"],
	'days-standAlone-wide@localeAlias95':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-standAlone-wide':["1","2","3","4","5","6","7"],
	'quarters@localeAlias96':{'target':"quarters", 'bundle':"gregorian"},
	'quarters-format-abbr@localeAlias97':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-format-abbr':["Q1","Q2","Q3","Q4"],
	'quarters-format-narrow@localeAlias98':{'target':"quarters-standAlone-narrow",'bundle':"gregorian"},
	'quarters-format-narrow':["1","2","3","4"],
	'quarters-format-wide':["Q1","Q2","Q3","Q4"],
	'quarters-standAlone-abbr@localeAlias99':{'target':"quarters-format-abbr",'bundle':"gregorian"},
	'quarters-standAlone-abbr@localeAlias100':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-standAlone-abbr':["Q1","Q2","Q3","Q4"],
	'quarters-standAlone-narrow':["1","2","3","4"],
	'quarters-standAlone-wide@localeAlias101':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-standAlone-wide':["Q1","Q2","Q3","Q4"],
	'dayPeriods@localeAlias102':{'target':"dayPeriods", 'bundle':"gregorian"},
	'dayPeriods-format-abbr@localeAlias103':{'target':"dayPeriods-format-wide",'bundle':"gregorian"},
	'dayPeriods-format-abbr-am':"AM",
	'dayPeriods-format-abbr-pm':"PM",
	'dayPeriods-format-narrow@localeAlias104':{'target':"dayPeriods-format-abbr",'bundle':"gregorian"},
	'dayPeriods-format-narrow@localeAlias105':{'target':"dayPeriods-format-wide",'bundle':"gregorian"},
	'dayPeriods-format-narrow-am':"AM",
	'dayPeriods-format-narrow-pm':"PM",
	'dayPeriods-format-wide-am':"AM",
	'dayPeriods-format-wide-pm':"PM",
	'dayPeriods-format-abbr@localeAlias106':{'target':"dayPeriods-format-wide",'bundle':"gregorian"},
	'dayPeriods-format-abbr-am':"AM",
	'dayPeriods-format-abbr-pm':"PM",
	'dayPeriods-format-narrow@localeAlias107':{'target':"dayPeriods-format-abbr",'bundle':"gregorian"},
	'dayPeriods-format-narrow@localeAlias108':{'target':"dayPeriods-format-wide",'bundle':"gregorian"},
	'dayPeriods-format-narrow-am':"AM",
	'dayPeriods-format-narrow-pm':"PM",
	'dayPeriods-format-wide-am':"AM",
	'dayPeriods-format-wide-pm':"PM",
	'eraNames@localeAlias109':{'target':"eraAbbr", 'bundle':"ethiopic"},
	'eraNames':["ERA0","ERA1"],
	'eraAbbr':["ERA0","ERA1"],
	'eraNarrow@localeAlias110':{'target':"eraAbbr", 'bundle':"ethiopic"},
	'eraNarrow':["ERA0","ERA1"],
	'dateFormat@localeAlias111':{'target':"dateFormat", 'bundle':"gregorian"},
	'dateFormat-full': "EEEE, y MMMM dd",
	'dateFormat-long': "y MMMM d",
	'dateFormat-medium': "y MMM d",
	'dateFormat-short': "yyyy-MM-dd",
	'timeFormat@localeAlias112':{'target':"timeFormat", 'bundle':"gregorian"},
	'timeFormat-full': "HH:mm:ss zzzz",
	'timeFormat-long': "HH:mm:ss z",
	'timeFormat-medium': "HH:mm:ss",
	'timeFormat-short': "HH:mm",
	'dateTime@localeAlias113':{'target':"dateTime", 'bundle':"gregorian"},
	'dateTimeFormat-full': "{1} {0}" ,
	'dateTimeFormat-long': "{1} {0}" ,
	'dateTimeFormat-medium': "{1} {0}" ,
	'dateTimeFormat-short': "{1} {0}" ,
	'dateFormatItem-d':"d",
	'dateFormatItem-EEEd':"d EEE",
	'dateFormatItem-h':"h a",
	'dateFormatItem-H':"HH",
	'dateFormatItem-hm':"h:mm a",
	'dateFormatItem-Hm':"HH:mm",
	'dateFormatItem-hms':"h:mm:ss a",
	'dateFormatItem-Hms':"HH:mm:ss",
	'dateFormatItem-M':"L",
	'dateFormatItem-Md':"M-d",
	'dateFormatItem-MEd':"E, M-d",
	'dateFormatItem-MMM':"LLL",
	'dateFormatItem-MMMd':"MMM d",
	'dateFormatItem-MMMEd':"E MMM d",
	'dateFormatItem-ms':"mm:ss",
	'dateFormatItem-y':"y",
	'dateFormatItem-yM':"y-M",
	'dateFormatItem-yMEd':"EEE, y-M-d",
	'dateFormatItem-yMMM':"y MMM",
	'dateFormatItem-yMMMEd':"EEE, y MMM d",
	'dateFormatItem-yQ':"y Q",
	'dateFormatItem-yQQQ':"y QQQ",
	'dateTimeFormats-appendItem-Day':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Day-Of-Week':"{0} {1}",
	'dateTimeFormats-appendItem-Era':"{0} {1}",
	'dateTimeFormats-appendItem-Hour':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Minute':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Month':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Quarter':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Second':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Timezone':"{0} {1}",
	'dateTimeFormats-appendItem-Week':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Year':"{0} {1}"
})
                        