// generated from ldml/main/*.xml, xpath: ldml/calendars/calendar-indian
({
	'months-format-abbr@localeAlias198':{'target':"months-format-wide",'bundle':"indian"},
	'months-format-abbr':["Chaitra","Vaisakha","Jyaistha","Asadha","Sravana","Bhadra","Asvina","Kartika","Agrahayana","Pausa","Magha","Phalguna"],
	'months-format-narrow@localeAlias199':{'target':"months-standAlone-narrow",'bundle':"indian"},
	'months-format-narrow':["1","2","3","4","5","6","7","8","9","10","11","12"],
	'months-format-wide':["Chaitra","Vaisakha","Jyaistha","Asadha","Sravana","Bhadra","Asvina","Kartika","Agrahayana","Pausa","Magha","Phalguna"],
	'months-standAlone-abbr@localeAlias200':{'target':"months-format-abbr",'bundle':"indian"},
	'months-standAlone-abbr@localeAlias201':{'target':"months-format-wide",'bundle':"indian"},
	'months-standAlone-abbr':["Chaitra","Vaisakha","Jyaistha","Asadha","Sravana","Bhadra","Asvina","Kartika","Agrahayana","Pausa","Magha","Phalguna"],
	'months-standAlone-narrow':["1","2","3","4","5","6","7","8","9","10","11","12"],
	'months-standAlone-wide@localeAlias202':{'target':"months-format-wide",'bundle':"indian"},
	'months-standAlone-wide':["Chaitra","Vaisakha","Jyaistha","Asadha","Sravana","Bhadra","Asvina","Kartika","Agrahayana","Pausa","Magha","Phalguna"],
	'days@localeAlias203':{'target':"days", 'bundle':"gregorian"},
	'days-format-abbr@localeAlias204':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-format-abbr':["1","2","3","4","5","6","7"],
	'days-format-narrow@localeAlias205':{'target':"days-standAlone-narrow",'bundle':"gregorian"},
	'days-format-narrow':["1","2","3","4","5","6","7"],
	'days-format-wide':["1","2","3","4","5","6","7"],
	'days-standAlone-abbr@localeAlias206':{'target':"days-format-abbr",'bundle':"gregorian"},
	'days-standAlone-abbr@localeAlias207':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-standAlone-abbr':["1","2","3","4","5","6","7"],
	'days-standAlone-narrow':["1","2","3","4","5","6","7"],
	'days-standAlone-wide@localeAlias208':{'target':"days-format-wide",'bundle':"gregorian"},
	'days-standAlone-wide':["1","2","3","4","5","6","7"],
	'quarters@localeAlias209':{'target':"quarters", 'bundle':"gregorian"},
	'quarters-format-abbr@localeAlias210':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-format-abbr':["Q1","Q2","Q3","Q4"],
	'quarters-format-narrow@localeAlias211':{'target':"quarters-standAlone-narrow",'bundle':"gregorian"},
	'quarters-format-narrow':["1","2","3","4"],
	'quarters-format-wide':["Q1","Q2","Q3","Q4"],
	'quarters-standAlone-abbr@localeAlias212':{'target':"quarters-format-abbr",'bundle':"gregorian"},
	'quarters-standAlone-abbr@localeAlias213':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-standAlone-abbr':["Q1","Q2","Q3","Q4"],
	'quarters-standAlone-narrow':["1","2","3","4"],
	'quarters-standAlone-wide@localeAlias214':{'target':"quarters-format-wide",'bundle':"gregorian"},
	'quarters-standAlone-wide':["Q1","Q2","Q3","Q4"],
	'dayPeriods@localeAlias215':{'target':"dayPeriods", 'bundle':"gregorian"},
	'dayPeriods-format-abbr@localeAlias216':{'target':"dayPeriods-format-wide",'bundle':"gregorian"},
	'dayPeriods-format-abbr-am':"AM",
	'dayPeriods-format-abbr-pm':"PM",
	'dayPeriods-format-narrow@localeAlias217':{'target':"dayPeriods-format-abbr",'bundle':"gregorian"},
	'dayPeriods-format-narrow@localeAlias218':{'target':"dayPeriods-format-wide",'bundle':"gregorian"},
	'dayPeriods-format-narrow-am':"AM",
	'dayPeriods-format-narrow-pm':"PM",
	'dayPeriods-format-wide-am':"AM",
	'dayPeriods-format-wide-pm':"PM",
	'dayPeriods-format-abbr@localeAlias219':{'target':"dayPeriods-format-wide",'bundle':"gregorian"},
	'dayPeriods-format-abbr-am':"AM",
	'dayPeriods-format-abbr-pm':"PM",
	'dayPeriods-format-narrow@localeAlias220':{'target':"dayPeriods-format-abbr",'bundle':"gregorian"},
	'dayPeriods-format-narrow@localeAlias221':{'target':"dayPeriods-format-wide",'bundle':"gregorian"},
	'dayPeriods-format-narrow-am':"AM",
	'dayPeriods-format-narrow-pm':"PM",
	'dayPeriods-format-wide-am':"AM",
	'dayPeriods-format-wide-pm':"PM",
	'eraNames@localeAlias222':{'target':"eraAbbr", 'bundle':"indian"},
	'eraNames':["SAKA"],
	'eraAbbr':["SAKA"],
	'eraNarrow@localeAlias223':{'target':"eraAbbr", 'bundle':"indian"},
	'eraNarrow':["SAKA"],
	'dateFormat@localeAlias224':{'target':"dateFormat", 'bundle':"gregorian"},
	'dateFormat-full': "EEEE, y MMMM dd",
	'dateFormat-long': "y MMMM d",
	'dateFormat-medium': "y MMM d",
	'dateFormat-short': "yyyy-MM-dd",
	'timeFormat@localeAlias225':{'target':"timeFormat", 'bundle':"gregorian"},
	'timeFormat-full': "HH:mm:ss zzzz",
	'timeFormat-long': "HH:mm:ss z",
	'timeFormat-medium': "HH:mm:ss",
	'timeFormat-short': "HH:mm",
	'dateTime@localeAlias226':{'target':"dateTime", 'bundle':"gregorian"},
	'dateTimeFormat-full': "{1} {0}" ,
	'dateTimeFormat-long': "{1} {0}" ,
	'dateTimeFormat-medium': "{1} {0}" ,
	'dateTimeFormat-short': "{1} {0}" ,
	'dateFormatItem-d':"d",
	'dateFormatItem-EEEd':"d EEE",
	'dateFormatItem-h':"h a",
	'dateFormatItem-H':"HH",
	'dateFormatItem-hm':"h:mm a",
	'dateFormatItem-Hm':"HH:mm",
	'dateFormatItem-hms':"h:mm:ss a",
	'dateFormatItem-Hms':"HH:mm:ss",
	'dateFormatItem-M':"L",
	'dateFormatItem-Md':"M-d",
	'dateFormatItem-MEd':"E, M-d",
	'dateFormatItem-MMM':"LLL",
	'dateFormatItem-MMMd':"MMM d",
	'dateFormatItem-MMMEd':"E MMM d",
	'dateFormatItem-ms':"mm:ss",
	'dateFormatItem-y':"y",
	'dateFormatItem-yM':"y-M",
	'dateFormatItem-yMEd':"EEE, y-M-d",
	'dateFormatItem-yMMM':"y MMM",
	'dateFormatItem-yMMMEd':"EEE, y MMM d",
	'dateFormatItem-yQ':"y Q",
	'dateFormatItem-yQQQ':"y QQQ",
	'dateTimeFormats-appendItem-Day':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Day-Of-Week':"{0} {1}",
	'dateTimeFormats-appendItem-Era':"{0} {1}",
	'dateTimeFormats-appendItem-Hour':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Minute':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Month':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Quarter':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Second':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Timezone':"{0} {1}",
	'dateTimeFormats-appendItem-Week':"{0} ({2}: {1})",
	'dateTimeFormats-appendItem-Year':"{0} {1}"
})
                        