({
	"dateFormatItem-yM": "M.yyyy", 
	"field-dayperiod": "perioada zilei", 
	"dateFormatItem-yQ": "'trimestrul' Q y", 
	"field-minute": "minut", 
	"dateFormatItem-MMMEd": "E, d MMM", 
	"eraNames": [
		"î.Hr.", 
		"d.Hr."
	], 
	"dateTimeFormat-full": "{1}, {0}", 
	"field-day-relative+-1": "ieri", 
	"field-weekday": "zi a săptămânii", 
	"dateFormatItem-yQQQ": "QQQ y", 
	"field-day-relative+-2": "alaltăieri", 
	"dateFormatItem-MMdd": "dd.MM", 
	"field-day-relative+-3": "răsalaltăieri", 
	"days-standAlone-wide": [
		"duminică", 
		"luni", 
		"marți", 
		"miercuri", 
		"joi", 
		"vineri", 
		"sâmbătă"
	], 
	"months-standAlone-narrow": [
		"I", 
		"F", 
		"M", 
		"A", 
		"M", 
		"I", 
		"I", 
		"A", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"dateTimeFormat-short": "{1}, {0}", 
	"field-era": "eră", 
	"field-hour": "oră", 
	"dateTimeFormat-medium": "{1}, {0}", 
	"quarters-standAlone-abbr": [
		"trimestrul I", 
		"trimestrul al II-lea", 
		"trimestrul al III-lea", 
		"trimestrul al IV-lea"
	], 
	"months-standAlone-abbr": [
		"ianuarie", 
		"februarie", 
		"martie", 
		"aprilie", 
		"mai", 
		"iunie", 
		"iulie", 
		"august", 
		"septembrie", 
		"octombrie", 
		"noiembrie", 
		"decembrie"
	], 
	"dateFormatItem-yMMM": "MMM y", 
	"field-day-relative+0": "azi", 
	"field-day-relative+1": "mâine", 
	"days-standAlone-narrow": [
		"D", 
		"L", 
		"M", 
		"M", 
		"J", 
		"V", 
		"S"
	], 
	"eraAbbr": [
		"î.Hr.", 
		"d.Hr."
	], 
	"field-day-relative+2": "poimâine", 
	"field-day-relative+3": "răspoimâine", 
	"dateFormatItem-yyyyMM": "MM.yyyy", 
	"dateFormatItem-yyyyMMMM": "MMMM y", 
	"dateFormat-long": "d MMMM y", 
	"dateFormatItem-EEEd": "EEE d", 
	"field-zone": "zonă", 
	"dateFormatItem-yyMM": "MM.yy", 
	"dateFormat-medium": "dd.MM.yyyy", 
	"dateFormatItem-yyMMM": "MMM yy", 
	"quarters-standAlone-wide": [
		"trimestrul I", 
		"trimestrul al II-lea", 
		"trimestrul al III-lea", 
		"trimestrul al IV-lea"
	], 
	"dateFormatItem-yMMMM": "MMMM y", 
	"field-year": "an", 
	"quarters-standAlone-narrow": [
		"T1", 
		"T2", 
		"T3", 
		"T4"
	], 
	"dateTimeFormat-long": "{1}, {0}", 
	"field-week": "săptămână", 
	"months-standAlone-wide": [
		"ianuarie", 
		"februarie", 
		"martie", 
		"aprilie", 
		"mai", 
		"iunie", 
		"iulie", 
		"august", 
		"septembrie", 
		"octombrie", 
		"noiembrie", 
		"decembrie"
	], 
	"dateFormatItem-MMMMEd": "E, d MMMM", 
	"dateFormatItem-MMMd": "d MMM", 
	"quarters-format-narrow": [
		"T1", 
		"T2", 
		"T3", 
		"T4"
	], 
	"dateFormatItem-yyQ": "Q yy", 
	"months-format-abbr": [
		"ianuarie", 
		"februarie", 
		"martie", 
		"aprilie", 
		"mai", 
		"iunie", 
		"iulie", 
		"august", 
		"septembrie", 
		"octombrie", 
		"noiembrie", 
		"decembrie"
	], 
	"field-month": "lună", 
	"dateFormatItem-MMMMd": "d MMMM", 
	"quarters-format-abbr": [
		"trimestrul I", 
		"trimestrul al II-lea", 
		"trimestrul al III-lea", 
		"trimestrul al IV-lea"
	], 
	"days-format-abbr": [
		"duminică", 
		"luni", 
		"marți", 
		"miercuri", 
		"joi", 
		"vineri", 
		"sâmbătă"
	], 
	"days-format-narrow": [
		"D", 
		"L", 
		"M", 
		"M", 
		"J", 
		"V", 
		"S"
	], 
	"field-second": "secundă", 
	"field-day": "zi", 
	"dateFormatItem-MEd": "E, d MMM", 
	"months-format-narrow": [
		"I", 
		"F", 
		"M", 
		"A", 
		"M", 
		"I", 
		"I", 
		"A", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"dateFormatItem-MMMEEEd": "EEE, d MMM", 
	"days-standAlone-abbr": [
		"duminică", 
		"luni", 
		"marți", 
		"miercuri", 
		"joi", 
		"vineri", 
		"sâmbătă"
	], 
	"dateFormat-short": "dd.MM.yyyy", 
	"dateFormatItem-yMMMEd": "EEE, d MMM y", 
	"dateFormat-full": "EEEE, d MMMM y", 
	"dateFormatItem-Md": "d.M", 
	"dateFormatItem-yMEd": "EEE, d/M/yyyy", 
	"months-format-wide": [
		"ianuarie", 
		"februarie", 
		"martie", 
		"aprilie", 
		"mai", 
		"iunie", 
		"iulie", 
		"august", 
		"septembrie", 
		"octombrie", 
		"noiembrie", 
		"decembrie"
	], 
	"quarters-format-wide": [
		"trimestrul I", 
		"trimestrul al II-lea", 
		"trimestrul al III-lea", 
		"trimestrul al IV-lea"
	], 
	"days-format-wide": [
		"duminică", 
		"luni", 
		"marți", 
		"miercuri", 
		"joi", 
		"vineri", 
		"sâmbătă"
	], 
	"eraNarrow": [
		"î.Hr.", 
		"d.Hr."
	]
})