({
	"months-format-narrow": [
		"J", 
		"F", 
		"M", 
		"A", 
		"M", 
		"J", 
		"J", 
		"A", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"field-weekday": "Nedēļas diena", 
	"dateFormatItem-yQQQ": "y QQQ", 
	"dateFormatItem-yMEd": "EEE, dd.mm.yyyy.", 
	"dateFormatItem-MMMEd": "E, d. MMM", 
	"eraNarrow": [
		"p.m.ē.", 
		"m.ē."
	], 
	"dateFormat-long": "y. 'gada' d. MMMM", 
	"months-format-wide": [
		"janvāris", 
		"februāris", 
		"marts", 
		"aprīlis", 
		"maijs", 
		"jūnijs", 
		"jūlijs", 
		"augusts", 
		"septembris", 
		"oktobris", 
		"novembris", 
		"decembris"
	], 
	"dateFormatItem-EEEd": "EEE, d.", 
	"dayPeriods-format-wide-pm": "pēcpusdienā", 
	"dateFormat-full": "EEEE, y. 'gada' d. MMMM", 
	"dateFormatItem-Md": "dd.mm.", 
	"field-era": "ēra", 
	"dateFormatItem-yM": "mm.yyyy.", 
	"months-standAlone-wide": [
		"janvāris", 
		"februāris", 
		"marts", 
		"aprīlis", 
		"maijs", 
		"jūnijs", 
		"jūlijs", 
		"augusts", 
		"septembris", 
		"oktobris", 
		"novembris", 
		"decembris"
	], 
	"timeFormat-short": "HH:mm", 
	"quarters-format-wide": [
		"1. ceturksnis", 
		"2. ceturksnis", 
		"3. ceturksnis", 
		"4. ceturksnis"
	], 
	"timeFormat-long": "HH:mm:ss z", 
	"field-year": "Gads", 
	"dateFormatItem-yMMM": "yyyy. 'g'. MMM", 
	"dateFormatItem-yQ": "Q yyyy", 
	"field-hour": "Stundas", 
	"months-format-abbr": [
		"janv.", 
		"febr.", 
		"marts", 
		"apr.", 
		"maijs", 
		"jūn.", 
		"jūl.", 
		"aug.", 
		"sept.", 
		"okt.", 
		"nov.", 
		"dec."
	], 
	"dateFormatItem-yyQ": "Q yy", 
	"timeFormat-full": "HH:mm:ss zzzz", 
	"field-day-relative+0": "šodien", 
	"field-day-relative+1": "rīt", 
	"field-day-relative+2": "parīt", 
	"dateFormatItem-H": "HH", 
	"field-day-relative+3": "aizparīt", 
	"months-standAlone-abbr": [
		"janv.", 
		"febr.", 
		"marts", 
		"apr.", 
		"maijs", 
		"jūn.", 
		"jūl.", 
		"aug.", 
		"sept.", 
		"okt.", 
		"nov.", 
		"dec."
	], 
	"quarters-format-abbr": [
		"C1", 
		"C2", 
		"C3", 
		"C4"
	], 
	"quarters-standAlone-wide": [
		"1. ceturksnis", 
		"2. ceturksnis", 
		"3. ceturksnis", 
		"4. ceturksnis"
	], 
	"dateFormatItem-M": "L", 
	"days-standAlone-wide": [
		"svētdiena", 
		"pirmdiena", 
		"otrdiena", 
		"trešdiena", 
		"ceturtdiena", 
		"piektdiena", 
		"sestdiena"
	], 
	"dateFormatItem-MMMMd": "d. MMMM", 
	"timeFormat-medium": "HH:mm:ss", 
	"dateFormatItem-Hm": "HH:mm", 
	"quarters-standAlone-abbr": [
		"C1", 
		"C2", 
		"C3", 
		"C4"
	], 
	"eraAbbr": [
		"p.m.ē.", 
		"m.ē."
	], 
	"field-minute": "Minūtes", 
	"field-dayperiod": "Dayperiod", 
	"days-standAlone-abbr": [
		"Sv", 
		"Pr", 
		"Ot", 
		"Tr", 
		"Ce", 
		"Pk", 
		"Se"
	], 
	"dateFormatItem-d": "d", 
	"dateFormatItem-ms": "mm:ss", 
	"field-day-relative+-1": "vakar", 
	"dateFormatItem-h": "h a", 
	"field-day-relative+-2": "aizvakar", 
	"field-day-relative+-3": "aizaizvakar", 
	"dateFormatItem-MMMd": "d. MMM", 
	"dateFormatItem-MEd": "E, dd.MM.", 
	"dateFormatItem-yMMMM": "y. 'g'. MMMM", 
	"field-day": "diena", 
	"days-format-wide": [
		"svētdiena", 
		"pirmdiena", 
		"otrdiena", 
		"trešdiena", 
		"ceturtdiena", 
		"piektdiena", 
		"sestdiena"
	], 
	"field-zone": "Josla", 
	"dateFormatItem-y": "y. 'g'.", 
	"months-standAlone-narrow": [
		"J", 
		"F", 
		"M", 
		"A", 
		"M", 
		"J", 
		"J", 
		"A", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"dateFormatItem-hm": "h:mm a", 
	"days-format-abbr": [
		"Sv", 
		"Pr", 
		"Ot", 
		"Tr", 
		"Ce", 
		"Pk", 
		"Se"
	], 
	"eraNames": [
		"pirms mūsu ēras", 
		"mūsu ērā"
	], 
	"days-format-narrow": [
		"S", 
		"P", 
		"O", 
		"T", 
		"C", 
		"P", 
		"S"
	], 
	"field-month": "Mēnesis", 
	"days-standAlone-narrow": [
		"S", 
		"P", 
		"O", 
		"T", 
		"C", 
		"P", 
		"S"
	], 
	"dateFormatItem-MMM": "LLL", 
	"dayPeriods-format-wide-am": "priekšpusdienā", 
	"dateFormatItem-MMMMEd": "E, d. MMMM", 
	"dateFormat-short": "dd.MM.yy", 
	"field-second": "Sekundes", 
	"dateFormatItem-yMMMEd": "EEE, yyyy. 'g'. dd. MMM", 
	"dateFormatItem-Ed": "EEE, d.", 
	"field-week": "Nedēļa", 
	"dateFormat-medium": "y. 'gada' d. MMM", 
	"dateFormatItem-mmss": "mm:ss", 
	"dateFormatItem-Hms": "HH:mm:ss", 
	"dateFormatItem-hms": "h:mm:ss a", 
	"dateFormatItem-yyyy": "y. 'g'."
})