({
	"dateFormatItem-yM": "M/y", 
	"field-dayperiod": "Nyomushana/nyekiro", 
	"dateFormatItem-yQ": "Q y", 
	"field-minute": "Edakiika", 
	"eraNames": [
		"Kurisito Atakaijire", 
		"Kurisito Yaijire"
	], 
	"dateFormatItem-MMMEd": "E, MMM d", 
	"field-day-relative+-1": "Nyomwabazyo", 
	"dateFormatItem-yQQQ": "QQQ y", 
	"field-weekday": "Eizooba ry'okukora", 
	"days-standAlone-wide": [
		"Sande", 
		"Orwokubanza", 
		"Orwakabiri", 
		"Orwakashatu", 
		"Orwakana", 
		"Orwakataano", 
		"Orwamukaaga"
	], 
	"dateFormatItem-MMM": "LLL", 
	"months-standAlone-narrow": [
		"J", 
		"F", 
		"M", 
		"A", 
		"M", 
		"J", 
		"J", 
		"A", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"field-era": "Obunaku", 
	"field-hour": "Shaaha", 
	"quarters-standAlone-abbr": [
		"K1", 
		"K2", 
		"K3", 
		"K4"
	], 
	"dateFormatItem-y": "y", 
	"timeFormat-full": "h:mm:ss a zzzz", 
	"months-standAlone-abbr": [
		"KBZ", 
		"KBR", 
		"KST", 
		"KKN", 
		"KTN", 
		"KMK", 
		"KMS", 
		"KMN", 
		"KMN", 
		"KKM", 
		"KNK", 
		"KNB"
	], 
	"dateFormatItem-yMMM": "MMM y", 
	"field-day-relative+0": "Erizooba", 
	"days-standAlone-narrow": [
		"S", 
		"K", 
		"R", 
		"S", 
		"N", 
		"T", 
		"M"
	], 
	"field-day-relative+1": "Nyenkyakare", 
	"eraAbbr": [
		"BC", 
		"AD"
	], 
	"dateFormat-long": "d MMMM y", 
	"timeFormat-medium": "h:mm:ss a", 
	"dateFormatItem-Hm": "HH:mm", 
	"dateFormat-medium": "d MMM y", 
	"dateFormatItem-Hms": "HH:mm:ss", 
	"quarters-standAlone-wide": [
		"KWOTA 1", 
		"KWOTA 2", 
		"KWOTA 3", 
		"KWOTA 4"
	], 
	"dateFormatItem-yMMMM": "MMMM y", 
	"dateFormatItem-ms": "mm:ss", 
	"field-year": "Omwaka", 
	"field-week": "Esande", 
	"months-standAlone-wide": [
		"Okwokubanza", 
		"Okwakabiri", 
		"Okwakashatu", 
		"Okwakana", 
		"Okwakataana", 
		"Okwamukaaga", 
		"Okwamushanju", 
		"Okwamunaana", 
		"Okwamwenda", 
		"Okwaikumi", 
		"Okwaikumi na kumwe", 
		"Okwaikumi na ibiri"
	], 
	"dateFormatItem-MMMMEd": "E, MMMM d", 
	"dateFormatItem-MMMd": "MMM d", 
	"timeFormat-long": "h:mm:ss a z", 
	"months-format-abbr": [
		"KBZ", 
		"KBR", 
		"KST", 
		"KKN", 
		"KTN", 
		"KMK", 
		"KMS", 
		"KMN", 
		"KMN", 
		"KKM", 
		"KNK", 
		"KNB"
	], 
	"timeFormat-short": "h:mm a", 
	"field-month": "Omwezi", 
	"dateFormatItem-MMMMd": "MMMM d", 
	"quarters-format-abbr": [
		"K1", 
		"K2", 
		"K3", 
		"K4"
	], 
	"days-format-abbr": [
		"SAN", 
		"ORK", 
		"OKB", 
		"OKS", 
		"OKN", 
		"OKT", 
		"OMK"
	], 
	"dateFormatItem-M": "L", 
	"days-format-narrow": [
		"S", 
		"K", 
		"R", 
		"S", 
		"N", 
		"T", 
		"M"
	], 
	"field-second": "Obucweka/Esekendi", 
	"field-day": "Eizooba", 
	"dateFormatItem-MEd": "E, M/d", 
	"months-format-narrow": [
		"J", 
		"F", 
		"M", 
		"A", 
		"M", 
		"J", 
		"J", 
		"A", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"dateFormatItem-hm": "h:mm a", 
	"days-standAlone-abbr": [
		"SAN", 
		"ORK", 
		"OKB", 
		"OKS", 
		"OKN", 
		"OKT", 
		"OMK"
	], 
	"dateFormat-short": "dd/MM/yyyy", 
	"dateFormatItem-yMMMEd": "EEE, MMM d, y", 
	"dateFormat-full": "EEEE, d MMMM y", 
	"dateFormatItem-Md": "M/d", 
	"dateFormatItem-yMEd": "EEE, M/d/y", 
	"months-format-wide": [
		"Okwokubanza", 
		"Okwakabiri", 
		"Okwakashatu", 
		"Okwakana", 
		"Okwakataana", 
		"Okwamukaaga", 
		"Okwamushanju", 
		"Okwamunaana", 
		"Okwamwenda", 
		"Okwaikumi", 
		"Okwaikumi na kumwe", 
		"Okwaikumi na ibiri"
	], 
	"dateFormatItem-d": "d", 
	"quarters-format-wide": [
		"KWOTA 1", 
		"KWOTA 2", 
		"KWOTA 3", 
		"KWOTA 4"
	], 
	"days-format-wide": [
		"Sande", 
		"Orwokubanza", 
		"Orwakabiri", 
		"Orwakashatu", 
		"Orwakana", 
		"Orwakataano", 
		"Orwamukaaga"
	], 
	"eraNarrow": [
		"BC", 
		"AD"
	]
})