({
	"dateFormatItem-yM": "M. yyyy", 
	"field-dayperiod": "f.h./e.h.", 
	"dayPeriods-format-wide-pm": "e.h.", 
	"dateFormatItem-yQ": "Q. yyyy", 
	"field-minute": "mínúta", 
	"dateFormatItem-MMMEd": "E d. MMM", 
	"eraNames": [
		"fyrir Krist", 
		"eftir Krist"
	], 
	"field-day-relative+-1": "í gær", 
	"dateFormatItem-yQQQ": "QQQ y", 
	"field-day-relative+-2": "í fyrradag", 
	"field-weekday": "vikudagur", 
	"field-day-relative+-3": "í fyrrafyrradag", 
	"days-standAlone-wide": [
		"sunnudagur", 
		"mánudagur", 
		"þriðjudagur", 
		"miðvikudagur", 
		"fimmtudagur", 
		"föstudagur", 
		"laugardagur"
	], 
	"dateFormatItem-MMM": "LLL", 
	"months-standAlone-narrow": [
		"j", 
		"f", 
		"m", 
		"a", 
		"m", 
		"j", 
		"j", 
		"á", 
		"s", 
		"o", 
		"n", 
		"d"
	], 
	"dayPeriods-format-wide-am": "f.h.", 
	"field-era": "tímabil", 
	"field-hour": "klukkustund", 
	"quarters-standAlone-abbr": [
		"1F", 
		"2F", 
		"3F", 
		"4F"
	], 
	"dateFormatItem-y": "y", 
	"timeFormat-full": "HH:mm:ss zzzz", 
	"months-standAlone-abbr": [
		"jan", 
		"feb", 
		"mar", 
		"apr", 
		"maí", 
		"jún", 
		"júl", 
		"ágú", 
		"sep", 
		"okt", 
		"nóv", 
		"des"
	], 
	"dateFormatItem-yMMM": "MMM y", 
	"field-day-relative+0": "í dag", 
	"days-standAlone-narrow": [
		"s", 
		"m", 
		"þ", 
		"m", 
		"f", 
		"f", 
		"l"
	], 
	"field-day-relative+1": "á morgun", 
	"eraAbbr": [
		"fyrir Krist", 
		"eftir Krist"
	], 
	"field-day-relative+2": "í overmorgun", 
	"field-day-relative+3": "í overovermorgun", 
	"dateFormatItem-yyyyMMMM": "MMMM y", 
	"dateFormat-long": "d. MMMM y", 
	"timeFormat-medium": "HH:mm:ss", 
	"field-zone": "svæði", 
	"dateFormatItem-Hm": "HH:mm", 
	"dateFormat-medium": "d.M.yyyy", 
	"dateFormatItem-Hms": "HH:mm:ss", 
	"quarters-standAlone-wide": [
		"1. fjórðungur", 
		"2. fjórðungur", 
		"3. fjórðungur", 
		"4. fjórðungur"
	], 
	"dateFormatItem-yMMMM": "MMMM y", 
	"dateFormatItem-ms": "mm:ss", 
	"field-year": "ár", 
	"field-week": "vika", 
	"months-standAlone-wide": [
		"janúar", 
		"febrúar", 
		"mars", 
		"apríl", 
		"maí", 
		"júní", 
		"júlí", 
		"ágúst", 
		"september", 
		"október", 
		"nóvember", 
		"desember"
	], 
	"dateFormatItem-MMMMEd": "E d. MMMM", 
	"dateFormatItem-MMMd": "d. MMM", 
	"dateFormatItem-yyQ": "Q yy", 
	"timeFormat-long": "HH:mm:ss z", 
	"months-format-abbr": [
		"jan", 
		"feb", 
		"mar", 
		"apr", 
		"maí", 
		"jún", 
		"júl", 
		"ágú", 
		"sep", 
		"okt", 
		"nóv", 
		"des"
	], 
	"timeFormat-short": "HH:mm", 
	"field-month": "mánuður", 
	"dateFormatItem-MMMMd": "d. MMMM", 
	"quarters-format-abbr": [
		"F1", 
		"F2", 
		"F3", 
		"F4"
	], 
	"days-format-abbr": [
		"sun", 
		"mán", 
		"þri", 
		"mið", 
		"fim", 
		"fös", 
		"lau"
	], 
	"dateFormatItem-M": "L.", 
	"days-format-narrow": [
		"s", 
		"m", 
		"þ", 
		"m", 
		"f", 
		"f", 
		"l"
	], 
	"field-second": "sekúnda", 
	"field-day": "dagur", 
	"dateFormatItem-MEd": "E d.M.", 
	"months-format-narrow": [
		"j", 
		"f", 
		"m", 
		"a", 
		"m", 
		"j", 
		"j", 
		"á", 
		"s", 
		"o", 
		"n", 
		"d"
	], 
	"days-standAlone-abbr": [
		"sun", 
		"mán", 
		"þri", 
		"mið", 
		"fim", 
		"fös", 
		"lau"
	], 
	"dateFormat-short": "d.M.yyyy", 
	"dateFormatItem-yyyyM": "M.yyyy", 
	"dateFormatItem-yMMMEd": "EEE d. MMM y", 
	"dateFormat-full": "EEEE, d. MMMM y", 
	"dateFormatItem-Md": "d.M", 
	"dateFormatItem-yMEd": "EEE d.M.yyyy", 
	"months-format-wide": [
		"janúar", 
		"febrúar", 
		"mars", 
		"apríl", 
		"maí", 
		"júní", 
		"júlí", 
		"ágúst", 
		"september", 
		"október", 
		"nóvember", 
		"desember"
	], 
	"dateFormatItem-d": "d", 
	"quarters-format-wide": [
		"1st fjórðungur", 
		"2nd fjórðungur", 
		"3rd fjórðungur", 
		"4th fjórðungur"
	], 
	"days-format-wide": [
		"sunnudagur", 
		"mánudagur", 
		"þriðjudagur", 
		"miðvikudagur", 
		"fimmtudagur", 
		"föstudagur", 
		"laugardagur"
	], 
	"eraNarrow": [
		"f.k.", 
		"e.k."
	]
})