({
	"dateFormatItem-yM": "M/y", 
	"field-dayperiod": "Akasuba", 
	"dayPeriods-format-wide-pm": "akasuba", 
	"dateFormatItem-yQ": "Q y", 
	"field-minute": "Mineti", 
	"eraNames": [
		"Before Yesu", 
		"After Yesu"
	], 
	"dateFormatItem-MMMEd": "E, MMM d", 
	"field-day-relative+-1": "Mailo", 
	"dateFormatItem-yQQQ": "QQQ y", 
	"field-weekday": "Ubushiku", 
	"days-standAlone-wide": [
		"Pa Mulungu", 
		"Palichimo", 
		"Palichibuli", 
		"Palichitatu", 
		"Palichine", 
		"Palichisano", 
		"Pachibelushi"
	], 
	"dateFormatItem-MMM": "LLL", 
	"months-standAlone-narrow": [
		"J", 
		"F", 
		"M", 
		"E", 
		"M", 
		"J", 
		"J", 
		"O", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"dayPeriods-format-wide-am": "uluchelo", 
	"field-era": "Inkulo", 
	"field-hour": "Insa", 
	"dateFormatItem-y": "y", 
	"timeFormat-full": "h:mm:ss a zzzz", 
	"months-standAlone-abbr": [
		"Jan", 
		"Feb", 
		"Mac", 
		"Epr", 
		"Mei", 
		"Jun", 
		"Jul", 
		"Oga", 
		"Sep", 
		"Okt", 
		"Nov", 
		"Dis"
	], 
	"dateFormatItem-yMMM": "MMM y", 
	"field-day-relative+0": "Lelo", 
	"field-day-relative+1": "Mailo", 
	"eraAbbr": [
		"BC", 
		"AD"
	], 
	"dateFormat-long": "d MMMM y", 
	"timeFormat-medium": "h:mm:ss a", 
	"dateFormatItem-Hm": "HH:mm", 
	"dateFormat-medium": "d MMM y", 
	"dateFormatItem-Hms": "HH:mm:ss", 
	"dateFormatItem-yMMMM": "MMMM y", 
	"dateFormatItem-ms": "mm:ss", 
	"field-year": "Umwaka", 
	"field-week": "Umulungu", 
	"months-standAlone-wide": [
		"Januari", 
		"Februari", 
		"Machi", 
		"Epreo", 
		"Mei", 
		"Juni", 
		"Julai", 
		"Ogasti", 
		"Septemba", 
		"Oktoba", 
		"Novemba", 
		"Disemba"
	], 
	"dateFormatItem-MMMMEd": "E, MMMM d", 
	"dateFormatItem-MMMd": "MMM d", 
	"timeFormat-long": "h:mm:ss a z", 
	"months-format-abbr": [
		"Jan", 
		"Feb", 
		"Mac", 
		"Epr", 
		"Mei", 
		"Jun", 
		"Jul", 
		"Oga", 
		"Sep", 
		"Okt", 
		"Nov", 
		"Dis"
	], 
	"timeFormat-short": "h:mm a", 
	"field-month": "Umweshi", 
	"dateFormatItem-MMMMd": "MMMM d", 
	"days-format-abbr": [
		"Pa Mulungu", 
		"Palichimo", 
		"Palichibuli", 
		"Palichitatu", 
		"Palichine", 
		"Palichisano", 
		"Pachibelushi"
	], 
	"dateFormatItem-M": "L", 
	"field-second": "Sekondi", 
	"field-day": "Ubushiku", 
	"dateFormatItem-MEd": "E, M/d", 
	"months-format-narrow": [
		"J", 
		"F", 
		"M", 
		"E", 
		"M", 
		"J", 
		"J", 
		"O", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"dateFormatItem-hm": "h:mm a", 
	"days-standAlone-abbr": [
		"Pa Mulungu", 
		"Palichimo", 
		"Palichibuli", 
		"Palichitatu", 
		"Palichine", 
		"Palichisano", 
		"Pachibelushi"
	], 
	"dateFormat-short": "dd/MM/yyyy", 
	"dateFormatItem-yMMMEd": "EEE, MMM d, y", 
	"dateFormat-full": "EEEE, d MMMM y", 
	"dateFormatItem-Md": "M/d", 
	"dateFormatItem-yMEd": "EEE, M/d/y", 
	"months-format-wide": [
		"Januari", 
		"Februari", 
		"Machi", 
		"Epreo", 
		"Mei", 
		"Juni", 
		"Julai", 
		"Ogasti", 
		"Septemba", 
		"Oktoba", 
		"Novemba", 
		"Disemba"
	], 
	"dateFormatItem-d": "d", 
	"days-format-wide": [
		"Pa Mulungu", 
		"Palichimo", 
		"Palichibuli", 
		"Palichitatu", 
		"Palichine", 
		"Palichisano", 
		"Pachibelushi"
	], 
	"eraNarrow": [
		"BC", 
		"AD"
	]
})