({
	"dateFormatItem-yM": "M/y", 
	"field-dayperiod": "ጡዎት/ከሰአት", 
	"dayPeriods-format-wide-pm": "ከሳዓት", 
	"dateFormatItem-yQ": "Q y", 
	"field-minute": "ደቂቃ", 
	"eraNames": [
		"ዓመተ ዓለም", 
		"ዓመተ ምሕረት"
	], 
	"dateFormatItem-MMMEd": "E, MMM d", 
	"field-day-relative+-1": "ትናንት", 
	"dateFormatItem-yQQQ": "QQQ y", 
	"field-weekday": "አዘቦት", 
	"days-standAlone-wide": [
		"እሑድ", 
		"ሰኞ", 
		"ማክሰኞ", 
		"ረቡዕ", 
		"ሐሙስ", 
		"ዓርብ", 
		"ቅዳሜ"
	], 
	"dateFormatItem-MMM": "LLL", 
	"months-standAlone-narrow": [
		"ጃ", 
		"ፌ", 
		"ማ", 
		"ኤ", 
		"ሜ", 
		"ጁ", 
		"ጁ", 
		"ኦ", 
		"ሴ", 
		"ኦ", 
		"ኖ", 
		"ዲ"
	], 
	"dayPeriods-format-wide-am": "ጡዋት", 
	"field-era": "ዘመን", 
	"field-hour": "ሰዓት", 
	"dateFormatItem-y": "y", 
	"timeFormat-full": "h:mm:ss a zzzz", 
	"months-standAlone-abbr": [
		"ጃንዩ", 
		"ፌብሩ", 
		"ማርች", 
		"ኤፕረ", 
		"ሜይ", 
		"ጁን", 
		"ጁላይ", 
		"ኦገስ", 
		"ሴፕቴ", 
		"ኦክተ", 
		"ኖቬም", 
		"ዲሴም"
	], 
	"dateFormatItem-yMMM": "MMM y", 
	"field-day-relative+0": "ዛሬ", 
	"days-standAlone-narrow": [
		"እ", 
		"ሰ", 
		"ማ", 
		"ረ", 
		"ሐ", 
		"ዓ", 
		"ቅ"
	], 
	"field-day-relative+1": "ነገ", 
	"eraAbbr": [
		"ዓ/ዓ", 
		"ዓ/ም"
	], 
	"dateFormat-long": "d MMMM y", 
	"timeFormat-medium": "h:mm:ss a", 
	"field-zone": "የሰዓት ሰቅ", 
	"dateFormatItem-Hm": "HH:mm", 
	"dateFormat-medium": "d MMM y", 
	"dateFormatItem-Hms": "HH:mm:ss", 
	"dateFormatItem-yMMMM": "MMMM y", 
	"dateFormatItem-ms": "mm:ss", 
	"field-year": "ዓመት", 
	"field-week": "ሳምንት", 
	"months-standAlone-wide": [
		"ጃንዩወሪ", 
		"ፌብሩወሪ", 
		"ማርች", 
		"ኤፕረል", 
		"ሜይ", 
		"ጁን", 
		"ጁላይ", 
		"ኦገስት", 
		"ሴፕቴምበር", 
		"ኦክተውበር", 
		"ኖቬምበር", 
		"ዲሴምበር"
	], 
	"dateFormatItem-MMMMEd": "E, MMMM d", 
	"dateFormatItem-MMMd": "MMM d", 
	"timeFormat-long": "h:mm:ss a z", 
	"months-format-abbr": [
		"ጃንዩ", 
		"ፌብሩ", 
		"ማርች", 
		"ኤፕረ", 
		"ሜይ", 
		"ጁን", 
		"ጁላይ", 
		"ኦገስ", 
		"ሴፕቴ", 
		"ኦክተ", 
		"ኖቬም", 
		"ዲሴም"
	], 
	"timeFormat-short": "h:mm a", 
	"field-month": "ወር", 
	"dateFormatItem-MMMMd": "MMMM d", 
	"days-format-abbr": [
		"እሑድ", 
		"ሰኞ", 
		"ማክሰ", 
		"ረቡዕ", 
		"ሐሙስ", 
		"ዓርብ", 
		"ቅዳሜ"
	], 
	"dateFormatItem-M": "L", 
	"days-format-narrow": [
		"እ", 
		"ሰ", 
		"ማ", 
		"ረ", 
		"ሐ", 
		"ዓ", 
		"ቅ"
	], 
	"field-second": "ሰከንድ", 
	"field-day": "ቀን", 
	"dateFormatItem-MEd": "E, M/d", 
	"months-format-narrow": [
		"ጃ", 
		"ፌ", 
		"ማ", 
		"ኤ", 
		"ሜ", 
		"ጁ", 
		"ጁ", 
		"ኦ", 
		"ሴ", 
		"ኦ", 
		"ኖ", 
		"ዲ"
	], 
	"dateFormatItem-hm": "h:mm a", 
	"days-standAlone-abbr": [
		"እሑድ", 
		"ሰኞ", 
		"ማክሰ", 
		"ረቡዕ", 
		"ሐሙስ", 
		"ዓርብ", 
		"ቅዳሜ"
	], 
	"dateFormat-short": "dd/MM/yyyy", 
	"dateFormatItem-yMMMEd": "EEE, MMM d, y", 
	"dateFormat-full": "EEEE, d MMMM y", 
	"dateFormatItem-Md": "M/d", 
	"dateFormatItem-yMEd": "EEE, M/d/y", 
	"months-format-wide": [
		"ጃንዩወሪ", 
		"ፌብሩወሪ", 
		"ማርች", 
		"ኤፕረል", 
		"ሜይ", 
		"ጁን", 
		"ጁላይ", 
		"ኦገስት", 
		"ሴፕቴምበር", 
		"ኦክተውበር", 
		"ኖቬምበር", 
		"ዲሴምበር"
	], 
	"dateFormatItem-d": "d", 
	"days-format-wide": [
		"እሑድ", 
		"ሰኞ", 
		"ማክሰኞ", 
		"ረቡዕ", 
		"ሐሙስ", 
		"ዓርብ", 
		"ቅዳሜ"
	], 
	"eraNarrow": [
		"ዓ/ዓ", 
		"ዓ/ም"
	]
})