({
	"dateFormat-medium": "d MMM, y G", 
	"dateFormatItem-MMMEd": "E d MMM", 
	"dateFormatItem-MEd": "E, d-M", 
	"dateFormatItem-yMEd": "EEE, d/M/y", 
	"timeFormat-full": "h:mm:ss a zzzz", 
	"dateFormatItem-Md": "d-M", 
	"dateFormatItem-EEEd": "d EEE", 
	"months-standAlone-narrow": [
		"J", 
		"F", 
		"M", 
		"A", 
		"M", 
		"J", 
		"J", 
		"A", 
		"S", 
		"O", 
		"N", 
		"D"
	], 
	"dateFormatItem-MMMMEd": "E d MMMM", 
	"days-standAlone-narrow": [
		"S", 
		"M", 
		"T", 
		"W", 
		"T", 
		"F", 
		"S"
	], 
	"dateFormatItem-MMMMd": "d MMMM", 
	"dateFormatItem-yQQQ": "QQQ y", 
	"timeFormat-medium": "h:mm:ss a", 
	"dateFormat-long": "d MMMM, y G", 
	"dateFormat-short": "d/M/yyyy", 
	"dateFormatItem-yMMMEd": "EEE, d MMM, y", 
	"months-format-wide": [
		"January", 
		"February", 
		"March", 
		"April", 
		"May", 
		"June", 
		"July", 
		"August", 
		"September", 
		"October", 
		"November", 
		"December"
	], 
	"dateFormatItem-yM": "M/y", 
	"timeFormat-short": "h:mm a", 
	"months-format-abbr": [
		"Jan", 
		"Feb", 
		"Mar", 
		"Apr", 
		"May", 
		"Jun", 
		"Jul", 
		"Aug", 
		"Sep", 
		"Oct", 
		"Nov", 
		"Dec"
	], 
	"timeFormat-long": "h:mm:ss a z", 
	"days-format-wide": [
		"Sunday", 
		"Monday", 
		"Tuesday", 
		"Wednesday", 
		"Thursday", 
		"Friday", 
		"Saturday"
	], 
	"dateFormatItem-yQ": "Q y", 
	"dateFormatItem-yMMM": "MMM y", 
	"quarters-format-wide": [
		"1st quarter", 
		"2nd quarter", 
		"3rd quarter", 
		"4th quarter"
	], 
	"dateFormat-full": "EEEE, d MMMM, y G", 
	"dateFormatItem-MMMd": "d MMM", 
	"days-format-abbr": [
		"Sun", 
		"Mon", 
		"Tue", 
		"Wed", 
		"Thu", 
		"Fri", 
		"Sat"
	]
})