({
	"quarters-format-abbr": [
		"К1", 
		"К2", 
		"К3", 
		"К4"
	], 
	"dateFormat-medium": "dd.MM.y.", 
	"dateFormatItem-MMMEd": "E d. MMM", 
	"dateFormatItem-yMEd": "EEE, d. M. yyyy.", 
	"dateFormatItem-Hm": "HH.mm", 
	"dateFormatItem-y": "y.", 
	"timeFormat-full": "HH.mm.ss zzzz", 
	"dateFormatItem-Md": "d/M", 
	"dateFormatItem-hm": "hh.mm a", 
	"months-standAlone-wide": [
		"Тишри", 
		"Хешван", 
		"Кислев", 
		"Тевет", 
		"Шеват", 
		"Адар I", 
		"Адар", 
		"Нисан", 
		"Ијар", 
		"Сиван", 
		"Тамуз", 
		"Ав", 
		"Елул"
	], 
	"months-format-wide-leap": "Адар II", 
	"dateFormatItem-EEEd": "d. EEE", 
	"days-standAlone-narrow": [
		"н", 
		"п", 
		"у", 
		"с", 
		"ч", 
		"п", 
		"с"
	], 
	"dayPeriods-format-wide-pm": "поподне", 
	"months-standAlone-abbr": [
		"Тишри", 
		"Хешван", 
		"Кислев", 
		"Тевет", 
		"Шеват", 
		"Адар I", 
		"Адар", 
		"Нисан", 
		"Ијар", 
		"Сиван", 
		"Тамуз", 
		"Ав", 
		"Елул"
	], 
	"dateFormatItem-yQQQ": "QQQ. y", 
	"dayPeriods-format-wide-am": "пре подне", 
	"timeFormat-medium": "HH.mm.ss", 
	"dateFormat-long": "dd. MMMM y.", 
	"dateFormatItem-Hms": "HH.mm.ss", 
	"dateFormatItem-ms": "mm.ss", 
	"dateFormat-short": "d.M.yy.", 
	"dateFormatItem-yMMMEd": "EEE, d. MMM y.", 
	"months-format-wide": [
		"Тишри", 
		"Хешван", 
		"Кислев", 
		"Тевет", 
		"Шеват", 
		"Адар I", 
		"Адар", 
		"Нисан", 
		"Ијар", 
		"Сиван", 
		"Тамуз", 
		"Ав", 
		"Елул"
	], 
	"timeFormat-short": "HH.mm", 
	"months-format-abbr": [
		"Тишри", 
		"Хешван", 
		"Кислев", 
		"Тевет", 
		"Шеват", 
		"Адар I", 
		"Адар", 
		"Нисан", 
		"Ијар", 
		"Сиван", 
		"Тамуз", 
		"Ав", 
		"Елул"
	], 
	"dateFormatItem-h": "hh a", 
	"timeFormat-long": "HH.mm.ss z", 
	"days-format-wide": [
		"недеља", 
		"понедељак", 
		"уторак", 
		"среда", 
		"четвртак", 
		"петак", 
		"субота"
	], 
	"dateFormatItem-hms": "hh.mm.ss a", 
	"dateFormatItem-yMMM": "MMM. y", 
	"quarters-format-wide": [
		"Прво тромесечје", 
		"Друго тромесечје", 
		"Треће тромесечје", 
		"Четврто тромесечје"
	], 
	"dateFormat-full": "EEEE, dd. MMMM y.", 
	"dateFormatItem-MMMd": "MMM d.", 
	"days-format-abbr": [
		"нед", 
		"пон", 
		"уто", 
		"сре", 
		"чет", 
		"пет", 
		"суб"
	]
})