({
	"dateFormatItem-yM": "M/y", 
	"field-dayperiod": "n tufat / n tmeddit", 
	"dayPeriods-format-wide-pm": "n tmeddit", 
	"dateFormatItem-yQ": "'T'Q y", 
	"field-minute": "Tamrect", 
	"eraNames": [
		"send talalit n Ɛisa", 
		"seld talalit n Ɛisa"
	], 
	"dateFormatItem-MMMEd": "E d MMM", 
	"field-day-relative+-1": "Iḍelli", 
	"dateFormatItem-MMdd": "dd/MM", 
	"dateFormatItem-yQQQ": "QQQ y", 
	"field-weekday": "Ussan n ddurt", 
	"days-standAlone-wide": [
		"Yanass", 
		"Sanass", 
		"Kraḍass", 
		"Kuẓass", 
		"Samass", 
		"Sḍisass", 
		"Sayass"
	], 
	"dateFormatItem-MMM": "MMM", 
	"months-standAlone-narrow": [
		"Y", 
		"F", 
		"M", 
		"Y", 
		"M", 
		"Y", 
		"Y", 
		"Ɣ", 
		"C", 
		"T", 
		"N", 
		"D"
	], 
	"dayPeriods-format-wide-am": "n tufat", 
	"field-era": "Tallit", 
	"field-hour": "Tamert", 
	"quarters-standAlone-abbr": [
		"Kḍg1", 
		"Kḍg2", 
		"Kḍg3", 
		"Kḍg4"
	], 
	"dateFormatItem-y": "y", 
	"dateFormatItem-yyMMMEEEd": "EEE d MMM yy", 
	"dateFormatItem-MMMdd": "dd MMM", 
	"timeFormat-full": "HH:mm:ss zzzz", 
	"dateFormatItem-Med": "EEE d/M", 
	"months-standAlone-abbr": [
		"Yen", 
		"Fur", 
		"Meɣ", 
		"Yeb", 
		"May", 
		"Yun", 
		"Yul", 
		"Ɣuc", 
		"Cte", 
		"Tub", 
		"Nun", 
		"Duǧ"
	], 
	"dateFormatItem-yMMM": "MMM y", 
	"field-day-relative+0": "Ass-a", 
	"days-standAlone-narrow": [
		"Y", 
		"S", 
		"K", 
		"K", 
		"S", 
		"S", 
		"S"
	], 
	"field-day-relative+1": "Azekka", 
	"eraAbbr": [
		"snd. T.Ɛ", 
		"sld. T.Ɛ"
	], 
	"dateFormatItem-yyyyMMMM": "MMMM yyyy", 
	"dateFormat-long": "d MMMM y", 
	"timeFormat-medium": "HH:mm:ss", 
	"field-zone": "Aseglem asergan", 
	"dateFormatItem-MMd": "d/MM", 
	"dateFormat-medium": "d MMM, y", 
	"dateFormatItem-yyMM": "MM/y", 
	"dateFormatItem-yyMMM": "MMM yy", 
	"quarters-standAlone-wide": [
		"akraḍaggur amenzu", 
		"akraḍaggur wis-sin", 
		"akraḍaggur wis-kraḍ", 
		"akraḍaggur wis-kuẓ"
	], 
	"dateFormatItem-yMMMM": "MMMM y", 
	"dateFormatItem-ms": "m:ss", 
	"field-year": "Aseggas", 
	"dateFormatItem-yyMMMd": "d MMM yy", 
	"field-week": "Ddurt", 
	"months-standAlone-wide": [
		"Yennayer", 
		"Fuṛar", 
		"Meɣres", 
		"Yebrir", 
		"Mayyu", 
		"Yunyu", 
		"Yulyu", 
		"Ɣuct", 
		"Ctembeṛ", 
		"Tubeṛ", 
		"Nunembeṛ", 
		"Duǧembeṛ"
	], 
	"dateFormatItem-MMMMEd": "EEE d MMMM", 
	"dateFormatItem-MMMd": "d MMM", 
	"timeFormat-long": "HH:mm:ss z", 
	"months-format-abbr": [
		"Yen", 
		"Fur", 
		"Meɣ", 
		"Yeb", 
		"May", 
		"Yun", 
		"Yul", 
		"Ɣuc", 
		"Cte", 
		"Tub", 
		"Nun", 
		"Duǧ"
	], 
	"timeFormat-short": "HH:mm", 
	"field-month": "Aggur", 
	"dateFormatItem-MMMMd": "d MMMM", 
	"quarters-format-abbr": [
		"Kḍg1", 
		"Kḍg2", 
		"Kḍg3", 
		"Kḍg4"
	], 
	"days-format-abbr": [
		"Yan", 
		"San", 
		"Kraḍ", 
		"Kuẓ", 
		"Sam", 
		"Sḍis", 
		"Say"
	], 
	"dateFormatItem-M": "M", 
	"days-format-narrow": [
		"Y", 
		"S", 
		"K", 
		"K", 
		"S", 
		"S", 
		"S"
	], 
	"field-second": "Tasint", 
	"field-day": "Ass", 
	"months-format-narrow": [
		"Y", 
		"F", 
		"M", 
		"Y", 
		"M", 
		"Y", 
		"Y", 
		"Ɣ", 
		"C", 
		"T", 
		"N", 
		"D"
	], 
	"days-standAlone-abbr": [
		"Yan", 
		"San", 
		"Kraḍ", 
		"Kuẓ", 
		"Sam", 
		"Sḍis", 
		"Say"
	], 
	"dateFormat-short": "d/M/yyyy", 
	"dateFormatItem-yMMMEd": "EEE d MMM y", 
	"dateFormat-full": "EEEE d MMMM y", 
	"dateFormatItem-Md": "d/M", 
	"dateFormatItem-yMEd": "EEE d/M/y", 
	"months-format-wide": [
		"Yennayer", 
		"Fuṛar", 
		"Meɣres", 
		"Yebrir", 
		"Mayyu", 
		"Yunyu", 
		"Yulyu", 
		"Ɣuct", 
		"Ctembeṛ", 
		"Tubeṛ", 
		"Nunembeṛ", 
		"Duǧembeṛ"
	], 
	"quarters-format-wide": [
		"akraḍaggur amenzu", 
		"akraḍaggur wis-sin", 
		"akraḍaggur wis-kraḍ", 
		"akraḍaggur wis-kuẓ"
	], 
	"days-format-wide": [
		"Yanass", 
		"Sanass", 
		"Kraḍass", 
		"Kuẓass", 
		"Samass", 
		"Sḍisass", 
		"Sayass"
	], 
	"eraNarrow": [
		"snd. T.Ɛ", 
		"sld. T.Ɛ"
	]
})