({
	"dateFormatItem-yQ": "Q yyyy", 
	"dayPeriods-format-wide-pm": "CH", 
	"dateFormatItem-MMMEd": "E d MMM", 
	"eraNames": [
		"tr. CN", 
		"sau CN"
	], 
	"dateTimeFormat-full": "{0} {1}", 
	"field-day-relative+-1": "Yesterday", 
	"dateFormatItem-yQQQ": "QQQ y", 
	"dateFormatItem-MMdd": "dd-MM", 
	"days-standAlone-wide": [
		"Chủ nhật", 
		"Thứ hai", 
		"Thứ ba", 
		"Thứ tư", 
		"Thứ năm", 
		"Thứ sáu", 
		"Thứ bảy"
	], 
	"dateTimeFormat-short": "{0} {1}", 
	"dayPeriods-format-wide-am": "SA", 
	"dateTimeFormat-medium": "{0} {1}", 
	"timeFormat-full": "HH:mm:ss zzzz", 
	"dateFormatItem-yyyy": "y", 
	"months-standAlone-abbr": [
		"thg 1", 
		"thg 2", 
		"thg 3", 
		"thg 4", 
		"thg 5", 
		"thg 6", 
		"thg 7", 
		"thg 8", 
		"thg 9", 
		"thg 10", 
		"thg 11", 
		"thg 12"
	], 
	"dateFormatItem-yMMM": "MMM y", 
	"field-day-relative+0": "Today", 
	"field-day-relative+1": "Tomorrow", 
	"eraAbbr": [
		"tr. CN", 
		"sau CN"
	], 
	"dateFormatItem-yyyyMM": "MM-yyyy", 
	"dateFormat-long": "'Ngày' dd 'tháng' M 'năm' y", 
	"timeFormat-medium": "HH:mm:ss", 
	"dateFormat-medium": "dd-MM-yyyy", 
	"dateFormatItem-yMMMM": "MMMM y", 
	"dateTimeFormat-long": "{0} {1}", 
	"months-standAlone-wide": [
		"tháng một", 
		"tháng hai", 
		"tháng ba", 
		"tháng tư", 
		"tháng năm", 
		"tháng sáu", 
		"tháng bảy", 
		"tháng tám", 
		"tháng chín", 
		"tháng mười", 
		"tháng mười một", 
		"tháng mười hai"
	], 
	"dateFormatItem-MMMMEd": "E d MMMM", 
	"dateFormatItem-MMMd": "d MMM", 
	"dateFormatItem-yyQ": "Q yy", 
	"timeFormat-long": "HH:mm:ss z", 
	"months-format-abbr": [
		"thg 1", 
		"thg 2", 
		"thg 3", 
		"thg 4", 
		"thg 5", 
		"thg 6", 
		"thg 7", 
		"thg 8", 
		"thg 9", 
		"thg 10", 
		"thg 11", 
		"thg 12"
	], 
	"timeFormat-short": "HH:mm", 
	"dateFormatItem-MMMMd": "d MMMM", 
	"days-format-abbr": [
		"CN", 
		"Th 2", 
		"Th 3", 
		"Th 4", 
		"Th 5", 
		"Th 6", 
		"Th 7"
	], 
	"dateFormatItem-mmss": "mm:ss", 
	"dateFormatItem-MEd": "E, d-M", 
	"days-standAlone-abbr": [
		"CN", 
		"Th 2", 
		"Th 3", 
		"Th 4", 
		"Th 5", 
		"Th 6", 
		"Th 7"
	], 
	"dateFormat-short": "dd/MM/yyyy", 
	"dateFormatItem-yMMMEd": "EEE, d MMM y", 
	"dateFormat-full": "EEEE, 'ngày' dd MMMM 'năm' y", 
	"dateFormatItem-Md": "d-M", 
	"dateFormatItem-yMEd": "EEE, d-M-yyyy", 
	"months-format-wide": [
		"tháng một", 
		"tháng hai", 
		"tháng ba", 
		"tháng tư", 
		"tháng năm", 
		"tháng sáu", 
		"tháng bảy", 
		"tháng tám", 
		"tháng chín", 
		"tháng mười", 
		"tháng mười một", 
		"tháng mười hai"
	], 
	"days-format-wide": [
		"Chủ nhật", 
		"Thứ hai", 
		"Thứ ba", 
		"Thứ tư", 
		"Thứ năm", 
		"Thứ sáu", 
		"Thứ bảy"
	], 
	"eraNarrow": [
		"tr. CN", 
		"sau CN"
	]
})