({
	"dateFormatItem-yM": "M/y", 
	"field-dayperiod": "Sahnga", 
	"dayPeriods-format-wide-pm": "kikiiɗe", 
	"dateFormatItem-yQ": "'T'Q y", 
	"field-minute": "Hoƴom", 
	"eraNames": [
		"Hade Iisa", 
		"Caggal Iisa"
	], 
	"dateFormatItem-MMMEd": "E d MMM", 
	"field-day-relative+-1": "Haŋki", 
	"dateFormatItem-MMdd": "dd/MM", 
	"dateFormatItem-yQQQ": "QQQ y", 
	"field-weekday": "Ñalɗi yontere", 
	"days-standAlone-wide": [
		"dewo", 
		"aaɓnde", 
		"mawbaare", 
		"njeslaare", 
		"naasaande", 
		"mawnde", 
		"hoore-biir"
	], 
	"dateFormatItem-MMM": "MMM", 
	"months-standAlone-narrow": [
		"s", 
		"c", 
		"m", 
		"s", 
		"d", 
		"k", 
		"m", 
		"j", 
		"s", 
		"y", 
		"j", 
		"b"
	], 
	"dayPeriods-format-wide-am": "subaka", 
	"field-era": "Jamaanu", 
	"field-hour": "Waktu", 
	"quarters-standAlone-abbr": [
		"T1", 
		"T2", 
		"T3", 
		"T4"
	], 
	"dateFormatItem-y": "y", 
	"dateFormatItem-yyMMMEEEd": "EEE d MMM yy", 
	"dateFormatItem-MMMdd": "dd MMM", 
	"timeFormat-full": "HH:mm:ss zzzz", 
	"dateFormatItem-Med": "EEE d/M", 
	"months-standAlone-abbr": [
		"sii", 
		"col", 
		"mbo", 
		"see", 
		"duu", 
		"kor", 
		"mor", 
		"juk", 
		"slt", 
		"yar", 
		"jol", 
		"bow"
	], 
	"dateFormatItem-yMMM": "MMM y", 
	"field-day-relative+0": "Hannde", 
	"days-standAlone-narrow": [
		"d", 
		"a", 
		"m", 
		"n", 
		"n", 
		"m", 
		"h"
	], 
	"field-day-relative+1": "Jaŋngo", 
	"eraAbbr": [
		"H-I", 
		"C-I"
	], 
	"dateFormatItem-yyyyMMMM": "MMMM yyyy", 
	"dateFormat-long": "d MMMM y", 
	"timeFormat-medium": "HH:mm:ss", 
	"field-zone": "Diiwaan waktu", 
	"dateFormatItem-MMd": "d/MM", 
	"dateFormat-medium": "d MMM, y", 
	"dateFormatItem-yyMM": "MM/y", 
	"dateFormatItem-yyMMM": "MMM yy", 
	"quarters-standAlone-wide": [
		"Termes 1", 
		"Termes 2", 
		"Termes 3", 
		"Termes 4"
	], 
	"dateFormatItem-yMMMM": "MMMM y", 
	"dateFormatItem-ms": "m:ss", 
	"field-year": "Hitaande", 
	"dateFormatItem-yyMMMd": "d MMM yy", 
	"field-week": "Yontere", 
	"months-standAlone-wide": [
		"siilo", 
		"colte", 
		"mbooy", 
		"seeɗto", 
		"duujal", 
		"korse", 
		"morso", 
		"juko", 
		"siilto", 
		"yarkomaa", 
		"jolal", 
		"bowte"
	], 
	"dateFormatItem-MMMMEd": "EEE d MMMM", 
	"dateFormatItem-MMMd": "d MMM", 
	"timeFormat-long": "HH:mm:ss z", 
	"months-format-abbr": [
		"sii", 
		"col", 
		"mbo", 
		"see", 
		"duu", 
		"kor", 
		"mor", 
		"juk", 
		"slt", 
		"yar", 
		"jol", 
		"bow"
	], 
	"timeFormat-short": "HH:mm", 
	"field-month": "Lewru", 
	"dateFormatItem-MMMMd": "d MMMM", 
	"quarters-format-abbr": [
		"T1", 
		"T2", 
		"T3", 
		"T4"
	], 
	"days-format-abbr": [
		"dew", 
		"aaɓ", 
		"maw", 
		"nje", 
		"naa", 
		"mwd", 
		"hbi"
	], 
	"dateFormatItem-M": "M", 
	"days-format-narrow": [
		"d", 
		"a", 
		"m", 
		"n", 
		"n", 
		"m", 
		"h"
	], 
	"field-second": "Majaango", 
	"field-day": "Ñalnde", 
	"months-format-narrow": [
		"s", 
		"c", 
		"m", 
		"s", 
		"d", 
		"k", 
		"m", 
		"j", 
		"s", 
		"y", 
		"j", 
		"b"
	], 
	"days-standAlone-abbr": [
		"dew", 
		"aaɓ", 
		"maw", 
		"nje", 
		"naa", 
		"mwd", 
		"hbi"
	], 
	"dateFormat-short": "d/M/yyyy", 
	"dateFormatItem-yMMMEd": "EEE d MMM y", 
	"dateFormat-full": "EEEE d MMMM y", 
	"dateFormatItem-Md": "d/M", 
	"dateFormatItem-yMEd": "EEE d/M/y", 
	"months-format-wide": [
		"siilo", 
		"colte", 
		"mbooy", 
		"seeɗto", 
		"duujal", 
		"korse", 
		"morso", 
		"juko", 
		"siilto", 
		"yarkomaa", 
		"jolal", 
		"bowte"
	], 
	"quarters-format-wide": [
		"Termes 1", 
		"Termes 2", 
		"Termes 3", 
		"Termes 4"
	], 
	"days-format-wide": [
		"dewo", 
		"aaɓnde", 
		"mawbaare", 
		"njeslaare", 
		"naasaande", 
		"mawnde", 
		"hoore-biir"
	], 
	"eraNarrow": [
		"H-I", 
		"C-I"
	]
})