({
	"quarters-format-abbr": [
		"1kv", 
		"2kv", 
		"3kv", 
		"4kv"
	], 
	"dateFormat-medium": "d.MMM.y. G", 
	"dateFormatItem-MMMEd": "E, d.MMM.", 
	"dateFormatItem-yMEd": "EEE, d.M.y.", 
	"dateFormatItem-MEd": "E, d.M.", 
	"dateFormatItem-y": "y.", 
	"dateFormatItem-Md": "d.M.", 
	"dateFormatItem-hm": "hh:mm a", 
	"dateFormatItem-EEEd": "EEE, d.", 
	"months-standAlone-wide": [
		"siječanj", 
		"veljača", 
		"ožujak", 
		"travanj", 
		"svibanj", 
		"lipanj", 
		"srpanj", 
		"kolovoz", 
		"rujan", 
		"listopad", 
		"studeni", 
		"prosinac"
	], 
	"months-standAlone-narrow": [
		"1.", 
		"2.", 
		"3.", 
		"4.", 
		"5.", 
		"6.", 
		"7.", 
		"8.", 
		"9.", 
		"10.", 
		"11.", 
		"12."
	], 
	"days-standAlone-narrow": [
		"n", 
		"p", 
		"u", 
		"s", 
		"č", 
		"p", 
		"s"
	], 
	"dateFormatItem-yQQQ": "QQQ y.", 
	"dateFormat-long": "d. MMMM y. G", 
	"dateFormat-short": "d.M.yyyy.", 
	"dateFormatItem-yMMMEd": "EEE, d.MMM.y.", 
	"months-format-wide": [
		"siječnja", 
		"veljače", 
		"ožujka", 
		"travnja", 
		"svibnja", 
		"lipnja", 
		"srpnja", 
		"kolovoza", 
		"rujna", 
		"listopada", 
		"studenoga", 
		"prosinca"
	], 
	"dateFormatItem-d": "d.", 
	"dateFormatItem-yM": "M.yyyy.", 
	"months-format-abbr": [
		"sij", 
		"velj", 
		"ožu", 
		"tra", 
		"svi", 
		"lip", 
		"srp", 
		"kol", 
		"ruj", 
		"lis", 
		"stu", 
		"pro"
	], 
	"dateFormatItem-h": "hh a", 
	"days-format-wide": [
		"nedjelja", 
		"ponedjeljak", 
		"utorak", 
		"srijeda", 
		"četvrtak", 
		"petak", 
		"subota"
	], 
	"dateFormatItem-yQ": "Q. yyyy.", 
	"dateFormatItem-hms": "hh:mm:ss a", 
	"dateFormatItem-yMMM": "MMM.y.", 
	"dateFormatItem-MMM": "LLL.", 
	"quarters-format-wide": [
		"1. kvartal", 
		"2. kvartal", 
		"3. kvartal", 
		"4. kvartal"
	], 
	"dateFormat-full": "EEEE, d. MMMM y. G", 
	"dateFormatItem-MMMd": "d.MMM.", 
	"days-format-abbr": [
		"ned", 
		"pon", 
		"uto", 
		"sri", 
		"čet", 
		"pet", 
		"sub"
	]
})